(function () {
  const KEY='word_overlord_prototype_v1', AV=['Blaze','Frost','Grace','Louis','Mara','Nova','Orion','Pixie','Rex','Terra'];
  const TIMER=[50,48,46,44,42,40,38,36,34,32];
  const CAMPAIGNS={newcomer:{name:'NEWCOMER',tag:'CAMPAIGN 01',desc:'BEGIN YOUR RISE AS THE WORD OVERLORD',questions:10,starThresholds:[0.50,0.65,0.80]},animals:{name:'ANIMALS',tag:'CAMPAIGN 02 · THEMED',desc:'MASTER THE WILD KINGDOM',questions:8,grade:0,units:[11],lengths:[3,4,5,6,7,8,9,10],starThresholds:[0.65,0.80,0.95]},tourism:{name:'TOURISM',tag:'CAMPAIGN 03 · THEMED',desc:'CONQUER THE WORLD ONE WORD AT A TIME',questions:8,grade:0,units:[17],lengths:[3,4,5,6,7,8,9,10],starThresholds:[0.65,0.80,0.95]}};
  function calcTheoreticalMax(level,c){const lengths=c.lengths||window.WordOverlordLevelConfig.LENGTH_CURVE,diffs=window.WordOverlordLevelConfig.getDifficultyRecipe(level),pts={1:100,2:200,3:300};return lengths.reduce((sum,len,i)=>sum+(pts[diffs[i]]||100)+len*100,0)}
  const ACHIEVEMENTS=[
    {id:'first_step',icon:'⚔',name:'FIRST STEP',desc:'Complete your first level.',reward:500,test:s=>s.completedLevels>=1,progress:s=>[s.completedLevels,1],chain:'next_step'},
    {id:'next_step',icon:'⚔',name:'NEXT STEP',desc:'Complete 20 levels.',reward:1500,test:s=>s.completedLevels>=20,progress:s=>[s.completedLevels,20],chain:'final_step'},
    {id:'final_step',icon:'⚔',name:'FINAL STEP',desc:'Complete 50 levels.',reward:3000,test:s=>s.completedLevels>=50,progress:s=>[s.completedLevels,50],badge:'finalstep'},
    {id:'star_student',icon:'★',name:'STAR STUDENT',desc:'Collect 5 stars.',reward:1000,test:s=>s.totalStars>=5,progress:s=>[s.totalStars,5],chain:'star_lord'},
    {id:'star_lord',icon:'✦',name:'STAR LORD',desc:'Collect 25 stars.',reward:2500,test:s=>s.totalStars>=25,progress:s=>[s.totalStars,25],chain:'star_overlord'},
    {id:'star_overlord',icon:'✦',name:'STAR OVERLORD',desc:'Collect 100 stars.',reward:5000,test:s=>s.totalStars>=100,progress:s=>[s.totalStars,100],badge:'star'},
    {id:'perfection',icon:'◆',name:'PERFECTION',desc:'Earn 3 stars on a level.',reward:1500,test:s=>s.threeStarLevels>=1,progress:s=>[s.threeStarLevels,1],badge:'perfection'},
    {id:'streak_beginner',icon:'⚡',name:'STREAK BEGINNER',desc:'Reach a streak of 5 consecutive correct answers.',reward:1250,test:s=>s.bestStreak>=5,progress:s=>[s.bestStreak,5],chain:'streak_apprentice'},
    {id:'streak_apprentice',icon:'⚡',name:'STREAK APPRENTICE',desc:'Reach a streak of 10 consecutive correct answers.',reward:2500,test:s=>s.bestStreak>=10,progress:s=>[s.bestStreak,10],chain:'streak_master'},
    {id:'streak_master',icon:'⚡',name:'STREAK MASTER',desc:'Reach a streak of 20 consecutive correct answers.',reward:5000,test:s=>s.bestStreak>=20,progress:s=>[s.bestStreak,20],badge:'streak'},
    {id:'perfectionist',icon:'✦',name:'PERFECTIONIST',desc:'Trigger 5 flawless streaks.',reward:2500,test:s=>s.totalPerfectStreaks>=5,progress:s=>[s.totalPerfectStreaks,5],chain:'paragon'},
    {id:'paragon',icon:'✦',name:'PARAGON OF EXCELLENCE',desc:'Trigger 15 flawless streaks.',reward:5000,test:s=>s.totalPerfectStreaks>=15,progress:s=>[s.totalPerfectStreaks,15],chain:'living_legend'},
    {id:'living_legend',icon:'✦',name:'LIVING LEGEND',desc:'Trigger 30 flawless streaks.',reward:10000,test:s=>s.totalPerfectStreaks>=30,progress:s=>[s.totalPerfectStreaks,30]},
    {id:'wild_scholar',icon:'🐾',name:'WILD SCHOLAR',desc:'Complete 5 ANIMALS levels.',reward:1000,test:s=>s.completedByCampaign.animals>=5,progress:s=>[s.completedByCampaign.animals,5]},
    {id:'wild_professor',icon:'🐾',name:'WILD PROFESSOR',desc:'Complete the ANIMALS campaign.',reward:2500,test:s=>(s.campaignWinsCount.animals||0)>=1,progress:s=>[(s.campaignWinsCount.animals||0),1],chain:'wild_sage'},
    {id:'wild_sage',icon:'🐾',name:'WILD SAGE',desc:'Complete the ANIMALS campaign 5 times.',reward:5000,test:s=>(s.campaignWinsCount.animals||0)>=5,progress:s=>[(s.campaignWinsCount.animals||0),5],badge:'zoologist'},
    {id:'world_traveler',icon:'🧳',name:'TRAVELER',desc:'Complete 5 TOURISM levels.',reward:2000,test:s=>s.completedByCampaign.tourism>=5,progress:s=>[s.completedByCampaign.tourism,5],chain:'explorer'},
    {id:'explorer',icon:'🧳',name:'EXPLORER',desc:'Complete the TOURISM campaign.',reward:2500,test:s=>(s.campaignWinsCount.tourism||0)>=1,progress:s=>[(s.campaignWinsCount.tourism||0),1],chain:'adventurer'},
    {id:'adventurer',icon:'🧳',name:'ADVENTURER',desc:'Complete the TOURISM campaign 3 times.',reward:5000,test:s=>(s.campaignWinsCount.tourism||0)>=3,progress:s=>[(s.campaignWinsCount.tourism||0),3],badge:'adventurer'},
    {id:'campaign_conqueror',icon:'♛',name:'CONQUEROR',desc:'Complete an entire campaign.',reward:5000,test:s=>s.completedCampaigns>=1,progress:s=>[s.completedCampaigns,1],chain:'champion'},
    {id:'champion',icon:'♛',name:'CHAMPION',desc:'Complete 5 campaigns.',reward:10000,test:s=>s.totalCampaignCompletions>=5,progress:s=>[s.totalCampaignCompletions,5],chain:'emperor'},
    {id:'emperor',icon:'♛',name:'EMPEROR',desc:'Complete 15 campaigns.',reward:15000,test:s=>s.totalCampaignCompletions>=15,progress:s=>[s.totalCampaignCompletions,15],badge:'conquest'},
    {id:'rising_star',icon:'✶',name:'RISING STAR',desc:'Accumulate a total score of 10,000.',reward:1500,test:s=>s.score>=10000,progress:s=>[Math.min(s.score,10000),10000],chain:'score_baron'},
    {id:'score_baron',icon:'✶',name:'SCORE BARON',desc:'Accumulate a total score of 50,000.',reward:3000,test:s=>s.score>=50000,progress:s=>[Math.min(s.score,50000),50000],chain:'word_overlord'},
    {id:'word_overlord',icon:'♚',name:'WORD OVERLORD',desc:'Accumulate a total score of 100,000.',reward:8000,test:s=>s.score>=100000,progress:s=>[Math.min(s.score,100000),100000],badge:'overlord'},
    {id:'persistent',icon:'◈',name:'PERSISTENT',desc:'Complete 10 runs.',reward:2000,test:s=>s.runsCompleted>=10,progress:s=>[s.runsCompleted,10]},
    {id:'answer_machine',icon:'◈',name:'ANSWER MACHINE',desc:'Give 100 correct answers.',reward:1500,test:s=>s.totalCorrect>=100,progress:s=>[s.totalCorrect,100],chain:'quiz_master'},
    {id:'quiz_master',icon:'◈',name:'QUIZ MASTER',desc:'Give 250 correct answers.',reward:5000,test:s=>s.totalCorrect>=250,progress:s=>[s.totalCorrect,250],chain:'trivia_legend'},
    {id:'trivia_legend',icon:'◈',name:'TRIVIA LEGEND',desc:'Give 500 correct answers.',reward:10000,test:s=>s.totalCorrect>=500,progress:s=>[s.totalCorrect,500],badge:'quizmaster'},
    {id:'iron_guard',icon:'◉',name:'IRON GUARD',desc:'Complete a level without losing a life.',reward:1500,test:s=>s.lifePerfectLevels>=1,progress:s=>[s.lifePerfectLevels,1],chain:'steel_guardian'},
    {id:'steel_guardian',icon:'◉',name:'STEEL GUARDIAN',desc:'Complete 5 levels without losing a life.',reward:10000,test:s=>s.lifePerfectLevels>=5,progress:s=>[s.lifePerfectLevels,5],chain:'sentinel'},
    {id:'sentinel',icon:'◉',name:'SENTINEL',desc:'Complete 10 levels without losing a life.',reward:15000,test:s=>s.lifePerfectLevels>=10,progress:s=>[s.lifePerfectLevels,10],badge:'sentinel'},
    {id:'joker_free',icon:'◉',name:'JOKER FREE',desc:'Complete a level without using any jokers.',reward:1500,test:s=>s.jokerFreeLevels>=1,progress:s=>[s.jokerFreeLevels,1],chain:'really_hate_jokers'},
    {id:'really_hate_jokers',icon:'◉',name:'REALLY HATE JOKERS',desc:'Complete 5 levels without using any jokers.',reward:5000,test:s=>s.jokerFreeLevels>=5,progress:s=>[s.jokerFreeLevels,5],chain:'joker_hater'},
    {id:'joker_hater',icon:'◉',name:'JOKER HATER',desc:'Complete 15 levels without using any jokers.',reward:10000,test:s=>s.jokerFreeLevels>=15,progress:s=>[s.jokerFreeLevels,15],badge:'nojoker'},
  ];
  const ACHIEVEMENT_GROUPS=[
    {id:'milestones',icon:'⚔',label:'MILESTONES',ids:['first_step','next_step','final_step']},
    {id:'star_collection',icon:'★',label:'STAR COLLECTION',ids:['star_student','star_lord','star_overlord','perfection']},
    {id:'streak',icon:'⚡',label:'STREAK MASTER',ids:['streak_beginner','streak_apprentice','streak_master','perfectionist','paragon','living_legend']},
    {id:'campaign_master',icon:'♛',label:'CAMPAIGN MASTER',ids:['campaign_conqueror','champion','emperor','wild_scholar','wild_professor','wild_sage','world_traveler','explorer','adventurer']},
    {id:'score_hunter',icon:'✶',label:'SCORE HUNTER',ids:['rising_star','score_baron','word_overlord']},
    {id:'dedication',icon:'◈',label:'DEDICATION',ids:['persistent','answer_machine','quiz_master','trivia_legend']},
    {id:'perfect_run',icon:'◉',label:'PERFECT RUN',ids:['iron_guard','steel_guardian','sentinel','joker_free','really_hate_jokers','joker_hater']},
  ];
  const PROGRESS_KEYS=['unlockedLevel','pendingUnlockedLevel','stars','bestScores','activeRun','campaignUsedIds','campaignUsedAnswers','campaignScores','campaignComplete','campaignStreak'];
  let save=load(), draft={name:'',grade:7,avatar:'Blaze'}, run=null, selectedLevel=1, achievementsReturn='levels', activeAchievementGroup=null, newlyRevealedId=null;
  function emptyProgress(){return{unlockedLevel:1,pendingUnlockedLevel:null,stars:{},bestScores:{},activeRun:null,campaignUsedIds:[],campaignUsedAnswers:[],campaignScores:{},campaignComplete:false,campaignStreak:0}}
  function fresh(){return{version:3,profile:null,selectedCampaign:null,campaignData:{},...emptyProgress(),achievementScore:0,unlockedAchievements:[],claimedAchievements:[],chainStartStats:{},stats:{bestStreak:0,campaignWins:{},campaignWinsCount:{},runsCompleted:0,totalCorrect:0,totalWrong:0,totalPerfectStreaks:0,lifePerfectLevels:0,jokerFreeLevels:0},liteMode:false,musicVolume:60}}
  function load(){try{let data={...fresh(),...JSON.parse(localStorage.getItem(KEY)||'{}')};data.unlockedAchievements=Array.isArray(data.unlockedAchievements)?data.unlockedAchievements:[];data.claimedAchievements=Array.isArray(data.claimedAchievements)?data.claimedAchievements:[];data.stats={bestStreak:0,campaignWins:{},campaignWinsCount:{},runsCompleted:0,totalCorrect:0,totalWrong:0,totalPerfectStreaks:0,lifePerfectLevels:0,jokerFreeLevels:0,...data.stats};data.stats.campaignWinsCount=data.stats.campaignWinsCount||{};data.stats.campaignWins=data.stats.campaignWins||{};Object.entries(data.campaignData||{}).forEach(([id,p])=>{if(p?.campaignComplete)data.stats.campaignWins[id]=true});if(data.selectedCampaign&&data.campaignComplete)data.stats.campaignWins[data.selectedCampaign]=true;return data}catch(e){return fresh()}}
  function campaign(){return CAMPAIGNS[save.selectedCampaign]||CAMPAIGNS.newcomer}
  function syncCampaign(){if(!save.selectedCampaign)return;save.campaignData=save.campaignData||{};save.campaignData[save.selectedCampaign]=Object.fromEntries(PROGRESS_KEYS.map(k=>[k,save[k]]))}
  function loadCampaign(id){let data=save.campaignData?.[id]||emptyProgress();PROGRESS_KEYS.forEach(k=>save[k]=data[k]===undefined?emptyProgress()[k]:data[k]);run=save.activeRun}
  function store(){save.activeRun=run;syncCampaign();localStorage.setItem(KEY,JSON.stringify(save))}
  function progressMap(){let map={...(save.campaignData||{})};if(save.selectedCampaign)map[save.selectedCampaign]=Object.fromEntries(PROGRESS_KEYS.map(k=>[k,save[k]]));return map}
  function playerScore(){return Object.values(progressMap()).reduce((total,p)=>total+Object.values(p.campaignScores||{}).reduce((sum,x)=>sum+(Number(x)||0),0),0)+(Number(save.achievementScore)||0)}
  function achievementStats(){let map=progressMap(),completedByCampaign={};Object.keys(CAMPAIGNS).forEach(id=>completedByCampaign[id]=Object.keys(map[id]?.stars||{}).length);let stars=Object.values(map).flatMap(p=>Object.values(p.stars||{}));return{completedByCampaign,completedLevels:Object.values(completedByCampaign).reduce((a,b)=>a+b,0),completedCampaigns:Object.keys(save.stats?.campaignWins||{}).length,totalStars:stars.reduce((a,b)=>a+(Number(b)||0),0),threeStarLevels:stars.filter(x=>Number(x)>=3).length,bestStreak:Number(save.stats?.bestStreak)||0,totalPerfectStreaks:Number(save.stats?.totalPerfectStreaks)||0,lifePerfectLevels:Number(save.stats?.lifePerfectLevels)||0,jokerFreeLevels:Number(save.stats?.jokerFreeLevels)||0,runsCompleted:Number(save.stats?.runsCompleted)||0,totalCorrect:Number(save.stats?.totalCorrect)||0,campaignWinsCount:save.stats?.campaignWinsCount||{},totalCampaignCompletions:Object.values(save.stats?.campaignWinsCount||{}).reduce((a,b)=>a+b,0),score:playerScore()}}
  function achievementStatsFor(a){let stats=achievementStats(),baseline=(save.chainStartStats||{})[a.id];if(!baseline)return stats;let adj={...stats};for(let k in baseline){if(typeof adj[k]==='number'&&typeof baseline[k]==='number')adj[k]=Math.max(0,adj[k]-baseline[k]);}return adj;}
  function unlockAchievements(){let prev=new Set(save.unlockedAchievements||[]),claimed=new Set(save.claimedAchievements||[]),unlocked=new Set(prev);ACHIEVEMENTS.forEach(a=>{if(a.test(achievementStatsFor(a)))unlocked.add(a.id)});save.unlockedAchievements=[...unlocked];[...unlocked].filter(id=>!prev.has(id)&&!claimed.has(id)).forEach((id,i)=>{let a=ACHIEVEMENTS.find(x=>x.id===id);if(a)setTimeout(()=>showToast(`🏆 ${a.name} · READY TO CLAIM`,3500),i*600)})}
  function av(name,s='head'){return s?`avatars/AV_Anime_${name}_${s}.webp`:`avatars/AV_Anime_${name}.webp`}
  function show(id){document.querySelectorAll('.wo-screen').forEach(x=>x.classList.remove('open'));if(id)document.getElementById(id).classList.add('open')}
  function markup(){document.body.insertAdjacentHTML('beforeend',`
  <div id="wo-menu" class="wo-screen"><div class="wo-panel"><div class="wo-title">WORD OVERLORD</div><div class="wo-subtitle">EARLY ACCESS v 0.1</div><div id="wo-summary" class="wo-profile-summary"></div><div class="wo-menu-actions"><button class="wo-btn gold" onclick="WO.newGame()">NEW GAME</button><button class="wo-btn" id="wo-cont" onclick="WO.continueGame()">CONTINUE</button><button class="wo-btn ghost" onclick="WO.openSettings()">SETTINGS</button></div></div></div>
  <div id="wo-new" class="wo-screen"><div class="wo-panel wo-new-panel"><div class="wo-title wo-new-title">NEW OVERLORD</div><div class="wo-new-layout"><div class="wo-avatar-preview"><img id="wo-avatar-preview-img"><div id="wo-avatar-preview-name"></div></div><div class="wo-form"><div><label class="wo-label">PLAYER NAME</label><input id="wo-name" class="wo-name-input" maxlength="16" placeholder="ENTER YOUR NAME"></div><div><label class="wo-label">GRADE</label><div class="wo-choice-row" id="wo-grades"></div></div><div><label class="wo-label">AVATAR</label><div class="wo-avatar-grid" id="wo-avatars"></div></div><div id="wo-warn" class="wo-warning"></div><div class="wo-choice-row"><button class="wo-btn ghost" onclick="WO.menu()">BACK</button><button class="wo-btn gold" onclick="WO.confirmNew()">BEGIN</button></div></div></div></div></div>
  <div id="wo-campaigns" class="wo-screen"><div class="wo-panel wo-campaigns-panel"><div class="wo-campaigns-head"><div class="wo-title" style="font-size:64px;text-align:left">SELECT CAMPAIGN</div><div class="wo-achievements-score"><span>SCORE</span><strong id="wo-campaigns-score"></strong></div></div><div class="wo-campaign-select-grid"><button class="wo-campaign-card newcomer" onclick="WO.enterCampaign('newcomer')"><div class="wo-campaign-card-tag">CAMPAIGN 01</div><div class="wo-campaign-card-info"><div class="wo-campaign-card-desc">BEGIN YOUR RISE AS THE WORD OVERLORD</div><div id="wo-newcomer-progress" class="wo-campaign-card-progress"></div><div class="wo-campaign-card-enter">ENTER CAMPAIGN →</div></div></button><button class="wo-campaign-card animals" onclick="WO.enterCampaign('animals')"><div class="wo-campaign-card-tag">CAMPAIGN 02 · THEMED</div><div class="wo-campaign-card-info"><div class="wo-campaign-card-desc">MASTER THE WILD KINGDOM</div><div id="wo-animals-progress" class="wo-campaign-card-progress"></div><div class="wo-campaign-card-enter">ENTER CAMPAIGN →</div></div></button><button class="wo-campaign-card tourism" onclick="WO.enterCampaign('tourism')"><div class="wo-campaign-card-tag">CAMPAIGN 03 · THEMED</div><div class="wo-campaign-card-info"><div class="wo-campaign-card-desc">CONQUER THE WORLD ONE WORD AT A TIME</div><div id="wo-tourism-progress" class="wo-campaign-card-progress"></div><div class="wo-campaign-card-enter">ENTER CAMPAIGN →</div></div></button></div><div class="wo-campaign-menu-actions"><button class="wo-btn ghost" onclick="WO.menu()">MAIN MENU</button><button class="wo-btn" onclick="WO.profile()">PROFILE</button><button class="wo-btn gold" onclick="WO.achievements('campaigns')">ACHIEVEMENTS</button></div></div></div>
  <div id="wo-profile" class="wo-screen"><div class="wo-panel wo-profile-panel"><div class="wo-profile-hero"><img id="wo-profile-avatar"><div><div id="wo-profile-name" class="wo-title" style="font-size:58px;text-align:left"></div><div id="wo-profile-grade" class="wo-profile-grade"></div><div class="wo-profile-score-label">SCORE</div><div id="wo-profile-score" class="wo-profile-score"></div></div></div><div id="wo-profile-stats" class="wo-profile-stats"></div><div class="wo-profile-actions"><button class="wo-profile-info" onclick="WO.earnedBadges()"><span>ACHIEVEMENT BADGES</span><strong id="wo-profile-achievements"></strong><b>?</b></button><button class="wo-profile-info" onclick="WO.completedCampaigns()"><span>CAMPAIGNS COMPLETED</span><strong id="wo-profile-campaigns"></strong><b>?</b></button></div><div class="wo-level-footer"><button class="wo-level-action" onclick="WO.campaigns()">↩ BACK</button></div></div></div>
  <div id="wo-completed-campaigns" class="wo-screen"><div class="wo-panel wo-completed-panel"><div class="wo-title" style="font-size:58px">COMPLETED CAMPAIGNS</div><div id="wo-completed-grid" class="wo-completed-grid"></div><div class="wo-level-footer"><button class="wo-level-action" onclick="WO.profile()">↩ BACK</button></div></div></div>
  <div id="wo-levels" class="wo-screen"><div id="wo-levels-panel" class="wo-panel wo-levels-panel"><div id="wo-levels-title" class="wo-title" style="font-size:58px"></div><div class="wo-levels-layout"><aside class="wo-campaign-profile"><div id="wo-campaign-name" class="wo-campaign-name"></div><img id="wo-campaign-avatar"><div class="wo-campaign-score-label">SCORE</div><div id="wo-campaign-score" class="wo-campaign-score"></div></aside><div id="wo-level-grid" class="wo-level-grid"></div></div><div class="wo-level-footer"><button class="wo-level-action danger" onclick="WO.openResetCampaign()">RESET CAMPAIGN</button><button class="wo-level-action" onclick="WO.campaigns()">↩ BACK</button><button class="wo-level-action gold" onclick="WO.achievements()">🏆 ACHIEVEMENTS</button></div></div></div>
  <div id="wo-achievements" class="wo-screen"><div class="wo-panel wo-achievements-panel"><div class="wo-achievements-head"><div><div class="wo-title" style="font-size:58px;text-align:left">ACHIEVEMENTS</div><div class="wo-achievements-sub">COMPLETE CHALLENGES AND CLAIM SCORE REWARDS</div></div><div class="wo-achievements-score"><span>SCORE</span><strong id="wo-achievements-score"></strong></div></div><div id="wo-ach-tabs" class="wo-ach-tabs"></div><div id="wo-achievements-grid" class="wo-achievements-grid"></div><div class="wo-level-footer"><button class="wo-level-action" onclick="WO.closeAchievements()">↩ BACK</button></div></div></div>
  <div id="wo-reset-campaign" class="wo-screen"><div class="wo-panel wo-reset-panel"><div class="wo-reset-icon">⚠</div><div id="wo-reset-title" class="wo-title" style="font-size:54px"></div><div class="wo-reset-copy">ARE YOU SURE?<br>ALL LEVELS, STARS, SCORES AND CAMPAIGN PROGRESS WILL BE LOST.</div><div class="wo-choice-row wo-reset-actions"><button class="wo-btn ghost" onclick="WO.levels()">CANCEL</button><button class="wo-btn danger" onclick="WO.confirmResetCampaign()">YES, RESET CAMPAIGN</button></div></div></div>
  <div id="wo-level-ready" class="wo-screen"><div class="wo-panel wo-ready-panel"><div id="wo-ready-title" class="wo-title" style="font-size:58px"></div><div class="wo-ready-subtitle">10 QUESTIONS · EARN AT LEAST 1 STAR TO COMPLETE THE LEVEL</div><div id="wo-ready-stars" class="wo-ready-stars"></div><div id="wo-ready-best" class="wo-ready-best"></div><div class="wo-choice-row wo-ready-actions"><button class="wo-btn ghost" onclick="WO.levels()">BACK</button><button class="wo-btn gold" onclick="WO.startSelectedLevel()">START RUN</button></div></div></div>
  <div id="wo-settings" class="wo-screen"><div class="wo-panel" style="max-width:560px"><div class="wo-title" style="font-size:54px">SETTINGS</div><label class="wo-label">MUSIC VOLUME <span id="wo-vol-value"></span></label><input id="wo-vol" type="range" min="0" max="100" step="5" style="width:100%"><label class="wo-label" style="margin-top:20px">LITE MODE</label><div class="wo-choice-row"><button id="wo-lite-on" class="wo-choice" onclick="WO.setLite(true)">ON</button><button id="wo-lite-off" class="wo-choice" onclick="WO.setLite(false)">OFF</button></div><div class="wo-menu-actions" style="margin-top:22px"><button class="wo-btn gold" onclick="WO.closeSettings()">SAVE & BACK</button></div></div></div>
  <div id="wo-result" class="wo-screen"><div class="wo-panel" style="max-width:720px"><div id="wo-result-title" class="wo-title" style="font-size:58px"></div><div id="wo-result-stars" class="wo-result-stars"></div><div id="wo-result-stats" class="wo-result-stats"></div><div class="wo-choice-row wo-result-actions"><button class="wo-btn ghost" onclick="WO.retry()">REPLAY LEVEL</button><button class="wo-btn gold" onclick="WO.levels()">CONTINUE</button></div></div></div>
  <div id="wo-badge-reveal" class="wo-badge-reveal"><div class="wo-badge-reveal-panel"><div class="wo-badge-reveal-label">BADGE UNLOCKED</div><img id="wo-badge-reveal-img" class="wo-badge-reveal-img"><div id="wo-badge-reveal-name" class="wo-badge-reveal-name"></div><button class="wo-btn gold" style="margin-top:24px;min-width:200px" onclick="WO.closeBadgeReveal()">COOL!</button></div></div>
  <div id="wo-badges" class="wo-screen"><div class="wo-panel wo-badges-panel"><div class="wo-title" style="font-size:58px">ACHIEVEMENT BADGES</div><div id="wo-badges-grid" class="wo-badges-grid"></div><div class="wo-level-footer"><button class="wo-level-action" onclick="WO.profile()">↩ BACK</button></div></div></div>
  <div id="wo-flawless" class="wo-flawless"><div>FLAWLESS STREAK</div><span>LUCKY SPIN UNLOCKED</span></div>
  <div id="wo-hud" class="wo-hud"><img id="wo-hud-avatar" class="wo-hud-avatar"><div class="wo-hud-cell"><div id="wo-hud-level" class="wo-hud-value"></div><div class="wo-hud-label">LEVEL</div></div><div class="wo-hud-cell"><div id="wo-hud-q" class="wo-hud-value"></div><div class="wo-hud-label">QUESTION</div></div><div class="wo-hud-cell"><div id="wo-hud-score" class="wo-hud-value"></div><div class="wo-hud-label">SCORE</div></div><div class="wo-progress"><div class="wo-progress-track"><div id="wo-hud-progress" class="wo-progress-fill"></div><div id="wo-pmark-1" class="wo-pmark"></div><div id="wo-pmark-2" class="wo-pmark"></div><div id="wo-pmark-3" class="wo-pmark"></div></div><div class="wo-progress-stars-row"><span id="wo-pstar-1" class="wo-pstar">★</span><span id="wo-pstar-2" class="wo-pstar">★★</span><span id="wo-pstar-3" class="wo-pstar">★★★</span></div></div><div class="wo-hud-cell"><div id="wo-hud-lives" class="wo-hud-value"></div><div class="wo-hud-label">LIVES</div></div><div class="wo-hud-cell"><div id="wo-hud-streak" class="wo-hud-value"></div><div class="wo-hud-label">STREAK</div></div></div>`);let hint=document.getElementById('more-hints-btn');if(hint)hint.insertAdjacentHTML('afterend','<button id="wo-abandon" class="wo-abandon-btn" onclick="WO.abandon()">ABANDON RUN</button>')}
  function menu(){run=null;stopTimer();closeQOverlay();document.getElementById('wo-hud').classList.remove('open');document.getElementById('wo-summary').innerHTML=save.profile?`<img src="${av(save.profile.avatar)}"><div><strong>${save.profile.name}</strong><br>GRADE ${save.profile.grade} · SCORE ${playerScore()}</div>`:'CREATE A PROFILE TO BEGIN';document.getElementById('wo-cont').disabled=!save.profile;show('wo-menu')}
  function choices(){document.getElementById('wo-grades').innerHTML=[6,7,8].map(g=>`<button class="wo-choice${draft.grade===g?' active':''}" onclick="WO.grade(${g})">${g}</button>`).join('');document.getElementById('wo-avatars').innerHTML=AV.map(a=>`<button class="wo-avatar${draft.avatar===a?' active':''}" onclick="WO.avatar('${a}')"><img class="${a==='Nova'||a==='Terra'?'wo-head-flip':''}" src="${av(a)}">${a.toUpperCase()}</button>`).join('');updateAvatarPreview()}
  function updateAvatarPreview(){let img=document.getElementById('wo-avatar-preview-img');if(!img)return;img.src=av(draft.avatar,'');document.getElementById('wo-avatar-preview-name').textContent=draft.avatar.toUpperCase()}
  function newGame(){draft=save.profile?{...save.profile}:{name:'',grade:7,avatar:'Blaze'};document.getElementById('wo-name').value=draft.name;choices();show('wo-new')}
  function confirmNew(){draft.name=document.getElementById('wo-name').value.trim().toUpperCase();if(!draft.name){document.getElementById('wo-warn').textContent='ENTER A PLAYER NAME';return}save={...fresh(),profile:{...draft}};store();campaigns()}
  function campaignSummary(id){let p=id===save.selectedCampaign?save:(save.campaignData?.[id]||emptyProgress()),stars=Object.values(p.stars||{}).reduce((a,b)=>a+b,0),completed=Object.keys(p.stars||{}).length,score=Object.values(p.campaignScores||{}).reduce((a,b)=>a+(Number(b)||0),0);return`${completed}/10 COMPLETED · ${stars} STARS · +${score} SCORE`}
  function campaigns(){stopTimer();closeQOverlay();document.getElementById('wo-hud').classList.remove('open');syncCampaign();document.getElementById('wo-campaigns-score').textContent=playerScore();Object.keys(CAMPAIGNS).forEach(id=>{const wins=save.stats?.campaignWinsCount?.[id]||0,isComplete=!!(save.stats?.campaignWins?.[id]);document.getElementById(`wo-${id}-progress`).innerHTML=campaignSummary(id)+(wins>0?`<br><span class="wo-cc-times">TIMES COMPLETED: ${wins}</span>`:'');const enterEl=document.querySelector(`.wo-campaign-card.${id} .wo-campaign-card-enter`);if(enterEl)enterEl.textContent=isComplete?'↺ REPLAY CAMPAIGN →':'ENTER CAMPAIGN →';});localStorage.setItem(KEY,JSON.stringify(save));show('wo-campaigns')}
  function profile(){unlockAchievements();store();let stats=achievementStats(),img=document.getElementById('wo-profile-avatar');img.src=av(save.profile.avatar);img.classList.toggle('wo-head-flip',save.profile.avatar==='Nova'||save.profile.avatar==='Terra');document.getElementById('wo-profile-name').textContent=save.profile.name;document.getElementById('wo-profile-grade').textContent=`GRADE ${save.profile.grade} · WORD OVERLORD`;document.getElementById('wo-profile-score').textContent=playerScore();document.getElementById('wo-profile-achievements').textContent=(save.claimedAchievements||[]).filter(id=>ACHIEVEMENTS.find(a=>a.id===id&&a.badge)).length+'/'+ACHIEVEMENTS.filter(a=>a.badge).length;document.getElementById('wo-profile-campaigns').textContent=stats.completedCampaigns;let items=[['BEST STREAK',stats.bestStreak],['TOTAL STARS',stats.totalStars],['LEVELS COMPLETED',stats.completedLevels],['3-STAR LEVELS',stats.threeStarLevels],['RUNS COMPLETED',save.stats.runsCompleted],['CORRECT ANSWERS',save.stats.totalCorrect],['WRONG ANSWERS',save.stats.totalWrong]];document.getElementById('wo-profile-stats').innerHTML=items.map(([label,value])=>`<div><strong>${value}</strong><span>${label}</span></div>`).join('');show('wo-profile')}
  function completedCampaigns(){let ids=Object.keys(save.stats?.campaignWins||{}).filter(id=>CAMPAIGNS[id]);document.getElementById('wo-completed-grid').innerHTML=ids.length?ids.map(id=>`<article class="wo-completed-card ${id}" style="background-image:url('charts/${id}.webp')"><span>${CAMPAIGNS[id].name}</span></article>`).join(''):'<div class="wo-completed-empty">NO CAMPAIGNS COMPLETED YET</div>';show('wo-completed-campaigns')}
  function enterCampaign(id){syncCampaign();save.selectedCampaign=id;loadCampaign(id);localStorage.setItem(KEY,JSON.stringify(save));levels()}
  function levels(){stopTimer();closeQOverlay();document.getElementById('wo-hud').classList.remove('open');let c=campaign(),unlocked=save.pendingUnlockedLevel,panel=document.getElementById('wo-levels-panel');document.getElementById('wo-levels-title').textContent=c.name;panel.classList.toggle('animals-theme',save.selectedCampaign==='animals');panel.classList.toggle('tourism-theme',save.selectedCampaign==='tourism');document.getElementById('wo-campaign-name').textContent=save.profile.name;document.getElementById('wo-campaign-avatar').src=av(save.profile.avatar,'');document.getElementById('wo-campaign-score').textContent=playerScore();document.getElementById('wo-level-grid').innerHTML=Array.from({length:10},(_,i)=>{let l=i+1,k=l>save.unlockedLevel,s=save.stars[l]||0,n=l===unlocked,cs=save.campaignScores?.[l];return`<button class="wo-level${k?' locked':''}${n?' newly-unlocked':''}${s===3&&!k?' three-star':''}" ${k?'disabled':''} onclick="WO.selectLevel(${l})">${n?'<div class="wo-new-level-badge">NEW LEVEL</div>':''}<div class="wo-level-num">LEVEL ${l}</div><div class="wo-level-stars">${'★'.repeat(s)}${'☆'.repeat(3-s)}</div><div class="wo-level-score">BEST ${save.bestScores[l]||0} · 1★ ${Math.round(calcTheoreticalMax(l,c)*(c.starThresholds||[0.65])[0])}</div><div class="wo-level-campaign-score">LEVEL SCORE ${cs===undefined?'—':cs}</div></button>`}).join('');show('wo-levels');if(unlocked&&!document.body.dataset.woUnlockSound){document.body.dataset.woUnlockSound=String(unlocked);setTimeout(()=>{if(typeof sfxCorrect==='function')sfxCorrect();document.querySelector('.wo-level.newly-unlocked')?.scrollIntoView({behavior:'smooth',block:'center'})},180)}}
  function selectLevel(level){if(level===save.pendingUnlockedLevel){save.pendingUnlockedLevel=null;delete document.body.dataset.woUnlockSound;store()}selectedLevel=level;let c=campaign(),[_th1,_th2,_th3]=c.starThresholds||[0.65,0.80,0.95],_max=calcTheoreticalMax(level,c),target=Math.round(_max*_th1),two=Math.round(_max*_th2),three=Math.round(_max*_th3),earned=save.stars[level]||0,row=(stars,points,desc)=>`<div class="wo-ready-star${earned>=stars?' completed':''}"><span>${'★'.repeat(stars)}${'☆'.repeat(3-stars)}</span><strong>${points} POINTS</strong><small>${desc}</small>${earned>=stars?'<b class="wo-ready-check">✓</b>':''}</div>`;document.querySelector('.wo-ready-subtitle').textContent=`${c.questions} QUESTIONS · EARN AT LEAST 1 STAR TO COMPLETE THE LEVEL`;document.getElementById('wo-ready-title').textContent=`LEVEL ${level}`;document.getElementById('wo-ready-stars').innerHTML=row(1,target,'COMPLETE THE LEVEL')+row(2,two,'REACH 80% OF YOUR POTENTIAL')+row(3,three,'REACH 95% AND MAX 1 MISTAKE');document.getElementById('wo-ready-best').textContent=`YOUR BEST: ${save.bestScores[level]||0} POINTS`;show('wo-level-ready')}
  function openResetCampaign(){document.getElementById('wo-reset-title').textContent=`RESET ${campaign().name}?`;show('wo-reset-campaign')}
  function confirmResetCampaign(){show('wo-levels');let grid=document.getElementById('wo-level-grid');grid.classList.add('resetting');if(typeof sfxWrong==='function')sfxWrong();setTimeout(()=>{run=null;Object.assign(save,emptyProgress());delete document.body.dataset.woUnlockSound;store();grid.classList.remove('resetting');levels()},1450)}
  function isVisible(a){const pred=ACHIEVEMENTS.find(x=>x.chain===a.id);return!pred||(save.claimedAchievements||[]).includes(pred.id)}
  function renderAchievementGrid(){const rid=newlyRevealedId;newlyRevealedId=null;let g=ACHIEVEMENT_GROUPS.find(x=>x.id===activeAchievementGroup),ids=new Set(g?.ids||[]),unlocked=new Set(save.unlockedAchievements||[]),claimed=new Set(save.claimedAchievements||[]);document.getElementById('wo-ach-tabs').innerHTML=ACHIEVEMENT_GROUPS.map(x=>`<button class="wo-ach-tab${activeAchievementGroup===x.id?' active':''}" onclick="WO.filterAchievements('${x.id}')">${x.icon} ${x.label}</button>`).join('');document.getElementById('wo-achievements-grid').innerHTML=ACHIEVEMENTS.filter(a=>ids.has(a.id)&&isVisible(a)).map(a=>{let ready=unlocked.has(a.id),done=claimed.has(a.id),_as=achievementStatsFor(a),[value,target]=a.progress(_as),pct=ready?100:Math.min(100,Math.round(value/target*100)),isNew=a.id===rid;return`<article data-id="${a.id}" class="wo-achievement ${done?'claimed':ready?'unlocked':'locked'}${isNew?' wo-achievement-new':''}"><div class="wo-achievement-icon">${a.icon}</div><div class="wo-achievement-copy"><h3>${a.name}</h3><p>${a.desc}</p><div class="wo-achievement-progress"><i style="width:${pct}%"></i></div><small>${ready?target:Math.min(value,target)}/${target}</small></div><div class="wo-achievement-reward"><strong>+${a.reward}</strong><span>SCORE</span>${done?'<button disabled>CLAIMED ✓</button>':ready?`<button onclick="WO.claimAchievement('${a.id}')">CLAIM</button>`:'<button disabled>LOCKED</button>'}</div></article>`}).join('')}
  function filterAchievements(id){activeAchievementGroup=id;renderAchievementGrid()}
  function achievements(from='levels'){achievementsReturn=from;if(!activeAchievementGroup)activeAchievementGroup=ACHIEVEMENT_GROUPS[0].id;unlockAchievements();store();document.getElementById('wo-achievements-score').textContent=playerScore();renderAchievementGrid();show('wo-achievements')}
  function closeAchievements(){if(achievementsReturn==='campaigns')campaigns();else if(achievementsReturn==='profile')profile();else levels()}
  function claimAchievement(id){unlockAchievements();let a=ACHIEVEMENTS.find(x=>x.id===id);if(!a||save.claimedAchievements.includes(id)||!save.unlockedAchievements.includes(id))return;save.claimedAchievements.push(id);save.achievementScore=(Number(save.achievementScore)||0)+a.reward;if(a.chain){save.chainStartStats=save.chainStartStats||{};save.chainStartStats[a.chain]=achievementStats();newlyRevealedId=a.chain;}store();if(typeof sfxCorrect==='function')sfxCorrect();showToast(`ACHIEVEMENT CLAIMED · +${a.reward} SCORE`,1800);if(a.badge){showBadgeReveal(a)}else{achievements(achievementsReturn)}}
  function showBadgeReveal(a){document.getElementById('wo-badge-reveal-img').src=`badges/${a.badge}.webp`;document.getElementById('wo-badge-reveal-name').textContent=a.name;document.getElementById('wo-badge-reveal').classList.add('open')}
  function closeBadgeReveal(){document.getElementById('wo-badge-reveal').classList.remove('open');achievements(achievementsReturn)}
  function earnedBadges(){const claimed=save.claimedAchievements||[];const earned=ACHIEVEMENTS.filter(a=>a.badge&&claimed.includes(a.id));document.getElementById('wo-profile-achievements').textContent=earned.length;document.getElementById('wo-badges-grid').innerHTML=earned.length?earned.map(a=>`<div class="wo-badge-item"><img src="badges/${a.badge}.webp"><span>${a.name}</span></div>`).join(''):'<div class="wo-badges-empty">NO BADGES YET</div>';show('wo-badges')}
  function startSelectedLevel(){begin(selectedLevel)}
  function begin(level,resume=false){if(!save.profile)return newGame();if(!resume){let c=campaign();if(save.campaignComplete){save.campaignUsedIds=[];save.campaignUsedAnswers=[];save.campaignComplete=false}let q=WordOverlordQuestionBank.buildLevelQuestions({grade:c.grade===undefined?save.profile.grade:c.grade,units:c.units,level,lengths:c.lengths,excludedIds:save.campaignUsedIds,excludedAnswers:save.campaignUsedAnswers});save.campaignUsedIds=[...new Set([...(save.campaignUsedIds||[]),...q.map(x=>x.id)])];save.campaignUsedAnswers=[...new Set([...(save.campaignUsedAnswers||[]),...q.map(x=>x.answer)])];const carryStreak=save.campaignStreak||0;run={level,index:0,questionIds:q.map(x=>x.id),score:0,lives:3,streak:carryStreak,flawlessStreak:0,bestStreak:carryStreak,correct:0,wrong:0,jokers:3,savedTime:0}}else if(run.flawlessStreak===undefined)run.flawlessStreak=0;show(null);document.getElementById('wo-hud').classList.add('open');resetAbandon(true);store();openQuestion()}
  function openQuestion(){let q=WordOverlordQuestionBank.getById(run.questionIds[run.index]);if(!q)return finish();currentQ=q.id;currentPts={1:100,2:200,3:300}[q.difficulty];answers[currentQ]=q.answer;questionTurkish[currentQ]=q.definitionTr;questionHints[currentQ]=q.image;groupScores[0]=run.score;currentGroup=0;jokerCount[0]=run.jokers;questionShown=false;isLocked=true;revealedIndices=new Set();ilkSonIndices=new Set();jokerFloodIndices=new Set();_jokerUsedThisTurn=false;_jokerTRUsed=false;_jokerIlkSonUsed=false;_visualHintUsed=false;hud();openQOverlay();flashWord(q.definitionEn);buildHexRow(q.answer,true);applyJokerFlood();updateScoreBadge();let sec=TIMER[run.level-1]+(window._wordOverlordTimeBoost?30:0);if(window._wordOverlordTimeBoost)delete window._wordOverlordTimeBoost;startTimer(sec);setTimeout(()=>{questionShown=true;isLocked=false;updateUI()},900)}
  function hud(){let c=campaign();document.getElementById('wo-hud-avatar').src=av(save.profile.avatar);document.getElementById('wo-hud-level').textContent=run.level;document.getElementById('wo-hud-q').textContent=`${Math.min(run.index+1,c.questions)}/${c.questions}`;document.getElementById('wo-hud-score').textContent=run.score;document.getElementById('wo-hud-lives').textContent='♥'.repeat(run.lives);document.getElementById('wo-hud-streak').textContent=run.streak;let [_th1,_th2,_th3]=c.starThresholds||[0.65,0.80,0.95],_max=calcTheoreticalMax(run.level,c),_t1=Math.round(_max*_th1),_t2=Math.round(_max*_th2),_t3=Math.round(_max*_th3),_s1=run.score>=_t1,_s2=run.score>=_t2,_s3=run.score>=_t3,_fill=document.getElementById('wo-hud-progress');_fill.style.width=Math.min(100,run.score/_max*100)+'%';_fill.className='wo-progress-fill'+(_s3?' s3':_s2?' s2':_s1?' s1':'');['wo-pstar-1','wo-pstar-2','wo-pstar-3'].forEach((id,i)=>{let el=document.getElementById(id);if(el)el.classList.toggle('lit',[_s1,_s2,_s3][i])});let _m1=document.getElementById('wo-pmark-1'),_m2=document.getElementById('wo-pmark-2'),_m3=document.getElementById('wo-pmark-3');if(_m1)_m1.style.left=(_th1*100)+'%';if(_m2)_m2.style.left=(_th2*100)+'%';if(_m3)_m3.style.left=(_th3*100)+'%';let _ps1=document.getElementById('wo-pstar-1'),_ps2=document.getElementById('wo-pstar-2'),_ps3=document.getElementById('wo-pstar-3');if(_ps1)_ps1.style.left=(_th1*100)+'%';if(_ps2)_ps2.style.left=(_th2*100)+'%';if(_ps3)_ps3.style.left=(_th3*100)+'%'}
  function complete(ok){let _tl=Math.max(0,window.timeLeft||0);stopTimer();let _fg=window._wheelFlawlessGuard;if(_fg&&ok)delete window._wheelFlawlessGuard;let flawless=ok&&(revealedIndices.size===0||(_fg&&revealedIndices.size<=1));if(ok){let e=getAwardScore();run.score+=e;run.savedTime=(run.savedTime||0)+_tl;run.correct++;run.streak++;run.flawlessStreak=flawless?(run.flawlessStreak||0)+1:0;run.bestStreak=Math.max(run.bestStreak,run.streak)}else{run.wrong++;run.streak=0;run.flawlessStreak=0;run.lives=Math.max(0,run.lives-1)}save.campaignStreak=run.streak;run.jokers=jokerCount[0];run.index++;groupScores[0]=run.score;let wheelReady=run.flawlessStreak>=3&&run.lives>0;if(wheelReady){run.flawlessStreak=0;save.stats.totalPerfectStreaks=(save.stats.totalPerfectStreaks||0)+1;}if(typeof resetWheelTurnFlags==='function')resetWheelTurnFlags();store();hud();closeQOverlay();setTimeout(()=>{if(wheelReady)showFlawlessWheel();else if(run.lives<=0||run.index>=campaign().questions)finish();else openQuestion()},0)}
  function showFlawlessWheel(){let splash=document.getElementById('wo-flawless');splash.classList.add('show');if(typeof sfxCorrect==='function')sfxCorrect();setTimeout(()=>{splash.classList.remove('show');window._wordOverlordWheelCloseHandler=()=>{let _wb=Math.max(0,groupScores[0]-run.score);if(_wb>0){save.achievementScore=(Number(save.achievementScore)||0)+_wb;showToast(`WHEEL BONUS +${_wb} SCORE`,1800);}if(window._wordOverlordExtraLife){delete window._wordOverlordExtraLife;run.lives=Math.min(3,run.lives+1);showToast('❤️ EXTRA LIFE!',1500);}run.jokers=jokerCount[0];groupScores[0]=run.score;store();hud();if(run.lives<=0||run.index>=campaign().questions){if(typeof resetWheelTurnFlags==='function')resetWheelTurnFlags();finish()}else openQuestion()};showWheelOverlay();let name=document.getElementById('wheel-student-name');if(name)name.textContent=`FLAWLESS STREAK · ${save.profile.name}`},1500)}
  function finish(){stopTimer();closeQOverlay();document.getElementById('wo-hud').classList.remove('open');resetAbandon(false);let _fc=campaign(),[_fth1,_fth2,_fth3]=_fc.starThresholds||[0.65,0.80,0.95],_fmax=calcTheoreticalMax(run.level,_fc),s=run.score>=Math.round(_fmax*_fth3)&&run.wrong<=1?3:run.score>=Math.round(_fmax*_fth2)?2:run.score>=Math.round(_fmax*_fth1)?1:0,previousUnlocked=save.unlockedLevel;if(!s)save.campaignStreak=0;if(s){if(run.lives===3)save.stats.lifePerfectLevels=(save.stats.lifePerfectLevels||0)+1;if(run.jokers===3)save.stats.jokerFreeLevels=(save.stats.jokerFreeLevels||0)+1;}save.campaignScores={...(save.campaignScores||{}),[run.level]:Math.max(save.campaignScores?.[run.level]||0,run.score)};save.stats.bestStreak=Math.max(Number(save.stats.bestStreak)||0,run.bestStreak||0);save.stats.runsCompleted=(Number(save.stats.runsCompleted)||0)+1;save.stats.totalCorrect=(Number(save.stats.totalCorrect)||0)+(run.correct||0);save.stats.totalWrong=(Number(save.stats.totalWrong)||0)+(run.wrong||0);if(s){save.unlockedLevel=Math.max(save.unlockedLevel,Math.min(10,run.level+1));if(save.unlockedLevel>previousUnlocked)save.pendingUnlockedLevel=save.unlockedLevel;save.stars[run.level]=Math.max(save.stars[run.level]||0,s);save.bestScores[run.level]=Math.max(save.bestScores[run.level]||0,run.score);if(run.level===10){save.campaignComplete=true;save.stats.campaignWins[save.selectedCampaign]=true;save.stats.campaignWinsCount=save.stats.campaignWinsCount||{};save.stats.campaignWinsCount[save.selectedCampaign]=(save.stats.campaignWinsCount[save.selectedCampaign]||0)+1;}}let _jBonus=run.jokers*200,_tBonus=run.savedTime||0;if(_jBonus>0)save.achievementScore=(Number(save.achievementScore)||0)+_jBonus;if(_tBonus>0)save.achievementScore=(Number(save.achievementScore)||0)+_tBonus;save.activeRun=null;syncCampaign();unlockAchievements();localStorage.setItem(KEY,JSON.stringify(save));document.getElementById('wo-result-title').textContent=s?'LEVEL COMPLETE':'LEVEL FAILED';document.getElementById('wo-result-stars').textContent='★'.repeat(s)+'☆'.repeat(3-s);let _jBonusHtml=_jBonus>0?`<div class="wo-result-stat wo-result-joker-bonus"><strong>+${_jBonus}</strong>JOKER SAVED</div>`:'',_tBonusHtml=_tBonus>0?`<div class="wo-result-stat wo-result-time-bonus"><strong>+${_tBonus}</strong>TIME SAVED</div>`:'';document.getElementById('wo-result-stats').innerHTML=`<div class="wo-result-stat"><strong>${run.score}</strong>LEVEL SCORE</div>${_jBonusHtml}${_tBonusHtml}<div class="wo-result-stat"><strong>${playerScore()}</strong>SCORE</div><div class="wo-result-stat"><strong>${run.correct}</strong>CORRECT</div><div class="wo-result-stat"><strong>${run.bestStreak}</strong>BEST STREAK</div>`;if(s){if(typeof _playSound==='function')_playSound('sounds/levelcomplete.mp3',save.musicVolume/100);else{const _snd=new Audio('sounds/levelcomplete.mp3');_snd.volume=save.musicVolume/100;_snd.play().catch(()=>{});}}show('wo-result')}
  let abandonConfirm=false,abandonTimer=null;
  function resetAbandon(showButton){clearTimeout(abandonTimer);abandonConfirm=false;let btn=document.getElementById('wo-abandon');if(!btn)return;btn.textContent='ABANDON RUN';btn.classList.remove('confirm');btn.classList.toggle('show',showButton)}
  function abandon(){let btn=document.getElementById('wo-abandon');if(!run)return;if(!abandonConfirm){abandonConfirm=true;btn.textContent='CONFIRM ABANDON';btn.classList.add('confirm');clearTimeout(abandonTimer);abandonTimer=setTimeout(()=>resetAbandon(true),2200);return}stopTimer();closeQOverlay();run=null;save.activeRun=null;store();resetAbandon(false);levels()}
  function applyVolume(){if(typeof applyMuteToAll==='function')applyMuteToAll(isMuted)}
  function openSettings(){document.getElementById('wo-vol').value=save.musicVolume;document.getElementById('wo-vol-value').textContent=save.musicVolume+'%';setLite(save.liteMode,false);show('wo-settings')}
  function setLite(x,write=true){save.liteMode=x;document.body.classList.toggle('lite-mode',x);document.getElementById('wo-lite-on')?.classList.toggle('active',x);document.getElementById('wo-lite-off')?.classList.toggle('active',!x);if(write)store()}
  function closeSettings(){save.musicVolume=Number(document.getElementById('wo-vol').value);applyVolume();store();menu()}
  function init(){document.body.classList.add('wo-prototype');markup();if(!save.campaignData)save.campaignData={};if(!save.selectedCampaign&&save.profile){save.selectedCampaign='newcomer';syncCampaign()}window.getWordOverlordMusicVolume=()=>save.musicVolume/100;setLite(save.liteMode,false);applyVolume();document.getElementById('wo-vol').addEventListener('input',e=>{save.musicVolume=Number(e.target.value);document.getElementById('wo-vol-value').textContent=e.target.value+'%';applyVolume();store()});menu()}
  window.WO={menu,newGame,grade:g=>{draft.grade=g;choices()},avatar:a=>{draft.avatar=a;choices()},confirmNew,continueGame:()=>save.activeRun?(run=save.activeRun,begin(run.level,true)):campaigns(),campaigns,profile,completedCampaigns,enterCampaign,levels,selectLevel,startSelectedLevel,openResetCampaign,confirmResetCampaign,achievements,closeAchievements,claimAchievement,filterAchievements,begin,retry:()=>begin(run.level),openSettings,setLite,closeSettings,complete,abandon};
  const oldResolve=window.resolveQuestion,oldWrong=window.wrongAnswerClose,oldExit=window.exitGame;
  window.resolveQuestion=x=>run?complete(!!x):oldResolve(x);window.wrongAnswerClose=()=>run?complete(false):oldWrong();window.exitGame=()=>{if(run){store();stopTimer();closeQOverlay();levels()}else oldExit()};
  window.addEventListener('DOMContentLoaded',init);
})();
