// questions.js — Word Game v3
// Format: [english_def, turkish_def, answer, grade, difficulty(1=easy/2=medium/3=hard), unit, "imagePath (optional)", ["ALT1","ALT2",...] (optional)]
// Answer: UPPERCASE, no spaces ideally (single word)
// difficulty 1=easy → 200 pts max | 2=medium → 400 pts | 3=hard → 600 pts
// grade = sınıf derecesi (e.g. 5, 6, 7, 8)
// imagePath: "../images/GRADE/UNIT/NUM.webp"  →  örnek: "../images/7/10/1.webp"
// [7] alts: optional array of alternative accepted answers — e.g. ["ORANGE JUICE","APPLE JUICE"]
//           image_reveal oyununda da kabul edilir; word_master bu alanı kullanmaz.

const QUESTIONS = [

  
  // ─── GRADE 6 UNIT 1 ──────────────────────────────────────────────────────────
  ["The time a person or animal is alive.","Bir kişinin veya hayvanın hayatta olduğu zaman.","LIFE",6,2,1,"../images/6/1/1.webp"],
  ["To begin something.","Bir şeye başlamak.","START",6,1,1,"../images/6/1/2.webp"],
  ["To end or complete something.","Bir şeyi bitirmek veya tamamlamak.","FINISH",6,1,1,"../images/6/1/3.webp"],
  ["A day from Monday to Friday.","Pazartesiden Cumaya kadar olan bir gün.","WEEKDAY",6,2,1,"../images/6/1/4.webp"],
  ["Saturday and Sunday.","Cumartesi ve Pazar.","WEEKEND",6,2,1,"../images/6/1/5.webp"],
  ["What clocks show in hours and minutes.","Saatlerin saat ve dakika olarak gösterdiği şey.","TIME",6,1,1,"../images/6/1/6.webp"],
  ["The day, month, and year.","Gün, ay ve yıl.","DATE",6,1,1,"../images/6/1/7.webp"],
  ["A thing that shows the time.","Saati gösteren şey.","CLOCK",6,1,1,"../images/6/1/8.webp"],
  ["At all times.","Her zaman.","ALWAYS",6,2,1,"../images/6/1/9.webp"],
  ["Most of the time.","Çoğu zaman.","USUALLY",6,2,1,"../images/6/1/10.webp"],
  ["Most of the time.","Çoğu zaman.","OFTEN",6,2,1,"../images/6/1/11.webp"],
  ["On some occasions.","Bazen.","SOMETIMES",6,2,1,"../images/6/1/12.webp"],
  ["Not very often.","Çok sık değil.","SELDOM",6,3,1,"../images/6/1/13.webp"],
  ["Almost never.","Neredeyse hiç.","RARELY",6,3,1,"../images/6/1/13.webp"],
  ["Not at any time.","Hiçbir zaman.","NEVER",6,2,1,"../images/6/1/14.webp"],
  ["Happening each day.","Her gün gerçekleşen.","EVERY DAY",6,2,1,"../images/6/1/15.webp"],
  ["One time.","Bir kez.","ONCE",6,2,1,"../images/6/1/16.webp"],
  ["Two times.","İki kez.","TWICE",6,2,1,"../images/6/1/17.webp"],
  ["Asking about the frequency of something.","Bir şeyin ne sıklıkla yapıldığını sormak.","HOW OFTEN",6,2,1,"../images/6/1/18.webp"],
  ["The early part of the day.","Günün erken saatleri.","MORNING",6,1,1,"../images/6/1/19.webp"],
  ["The time after midday and before evening.","Öğleden sonra ve akşamdan önce.","AFTERNOON",6,1,1,"../images/6/1/20.webp"],
  ["The part of the day before night.","Günün geceden önceki kısmı.","EVENING",6,1,1,"../images/6/1/21.webp"],
  ["The dark time after evening.","Akşamdan sonraki karanlık zaman.","NIGHT",6,1,1,"../images/6/1/22.webp"],
  ["Fifteen minutes after the hour.","Tam saatin on beş dakika sonrası.","QUARTER PAST",6,2,1,"../images/6/1/23.webp"],
  ["Thirty minutes after the hour.","Tam saatin otuz dakika sonrası.","HALF PAST",6,2,1,"../images/6/1/24.webp"],
  ["Used for exact hours on the clock.","Saatte tam saat için kullanılır.","O CLOCK",6,1,1,"../images/6/1/25.webp"],
  ["The first meal of the day.","Günün ilk öğünü.","BREAKFAST",6,1,1,"../images/6/1/26.webp"],
  ["A meal eaten in the middle of the day.","Günün ortasında yenen öğün.","LUNCH",6,1,1,"../images/6/1/27.webp"],
  ["The main meal eaten in the evening.","Akşamleyin yenen ana öğün.","DINNER",6,1,1,"../images/6/1/28.webp"],
  ["To stop sleeping.","Uyumayı bırakmak.","WAKE UP",6,1,1,"../images/6/1/29.webp"],
  ["To clean your face with water.","Yüzünü suyla temizlemek.","WASH FACE",6,1,1,"../images/6/1/30.webp"],
  ["To clean your teeth with a toothbrush.","Dişlerini diş fırçasıyla temizlemek.","BRUSH TEETH",6,1,1,"../images/6/1/31.webp"],
  ["To put on clothes.","Kıyafet giymek.","GET DRESSED",6,1,1,"../images/6/1/32.webp"],
  ["To get to school.","Okula varmak.","ARRIVE SCHOOL",6,2,1,"../images/6/1/33.webp"],
  ["To learn or review school subjects.","Okul derslerini öğrenmek veya tekrar etmek.","STUDY LESSON",6,1,1,"../images/6/1/34.webp"],
  ["To complete school work at home.","Evde okul ödevini tamamlamak.","DO HOMEWORK",6,1,1,"../images/6/1/34.webp"],
  ["To return to your house.","Evine dönmek.","COME BACK HOME",6,2,1,"../images/6/1/35.webp"],
  ["To exercise at a fitness center.","Spor salonunda egzersiz yapmak.","GO TO GYM",6,2,1,"../images/6/1/36.webp"],
  ["To look at and understand words in a book.","Kitaptaki kelimelere bakıp anlamak.","READ BOOK",6,1,1,"../images/6/1/37.webp"],
  ["To look at television programs.","Televizyon programlarına bakmak.","WATCH TV",6,1,1,"../images/6/1/38.webp"],
  ["To use the internet.","İnterneti kullanmak.","GO ONLINE",6,1,1,"../images/6/1/39.webp"],
  ["To have fun playing video or other games.","Video veya diğer oyunları oynayarak eğlenmek.","PLAY GAMES",6,1,1,"../images/6/1/40.webp"],
  ["To wash your body under running water.","Vücudunu akan su altında yıkamak.","TAKE SHOWER",6,1,1,"../images/6/1/41.webp"],
  ["To wash your body in a bathtub.","Vücudunu küvette yıkamak.","HAVE BATH",6,1,1,"../images/6/1/42.webp"],
  ["To relax for a short time.","Kısa bir süre dinlenmek.","HAVE A REST",6,1,1,"../images/6/1/43.webp"],
  ["To sleep for a short time during the day.","Gün içinde kısa bir süre uyumak.","TAKE A NAP",6,2,1,"../images/6/1/44.webp"],
  ["To spend time with friends.","Arkadaşlarla vakit geçirmek.","MEET FRIENDS",6,1,1,"../images/6/1/45.webp"],
  ["To buy things from stores.","Mağazalardan alışveriş yapmak.","GO SHOPPING",6,1,1,"../images/6/1/46.webp"],
  ["To go to classes or lessons.","Derslere veya kurslara gitmek.","ATTEND COURSE",6,2,1,"../images/6/1/47.webp"],


  // ─── GRADE 6 UNIT 2 ──────────────────────────────────────────────────────────
  ["A round bread people eat for breakfast.","İnsanların kahvaltıda yediği yuvarlak ekmek.","BAGEL",6,1,2,"../images/6/2/1.webp"],
  ["A soft yellow food made from milk.","Sütten yapılan yumuşak sarı yiyecek.","BUTTER",6,2,2,"../images/6/2/2.webp"],
  ["A breakfast food eaten with milk.","Sütle yenen kahvaltı yiyeceği.","CEREAL",6,2,2,"../images/6/2/3.webp"],
  ["A soft French bread shaped like a moon.","Ay şeklinde olan yumuşak Fransız ekmeği.","CROISSANT",6,2,2,"../images/6/2/4.webp"],
  ["A food that comes from chickens.","Tavuklardan gelen yiyecek.","EGG",6,1,2,"../images/6/2/5.webp"],
  ["A drink made from fruits.","Meyvelerden yapılan içecek.","FRUIT JUICE",6,1,2,"../images/6/2/6.webp",["ORANGE JUICE","APPLE JUICE","LEMON JUICE"]],
  ["A sweet food made from fruit and sugar.","Meyve ve şekerden yapılan tatlı yiyecek.","JAM",6,1,2,"../images/6/2/7.webp"],
  ["Eggs cooked together in a pan.","Tavada birlikte pişirilen yumurtalar.","OMELETTE",6,1,2,"../images/6/2/8.webp"],
  ["A small sweet cake.","Küçük tatlı kek.","MUFFIN",6,1,2,"../images/6/2/9.webp"],
  ["A thin round cake cooked in a pan.","Tavada pişirilen ince yuvarlak kek.","PANCAKE",6,1,2,"../images/6/2/10.webp"],
  ["A long meat food people cook and eat.","İnsanların pişirip yediği uzun et yiyeceği.","SAUSAGE",6,2,2,"../images/6/2/11.webp"],
  ["Good and healthy for your body.","Vücudunuz için iyi ve sağlıklı.","NUTRITIOUS",6,3,2,"../images/6/2/12.webp"],
  ["A hot drink made with leaves and water.","Yapraklar ve suyla yapılan sıcak içecek.","TEA",6,1,2,"../images/6/2/13.webp"],
  ["A hot dark drink many adults like.","Pek çok yetişkinin sevdiği sıcak koyu içecek.","COFFEE",6,1,2,"../images/6/2/14.webp"],
  ["A white drink from cows.","İneklerden gelen beyaz içecek.","MILK",6,1,2,"../images/6/2/15.webp"],
  ["A red fruit often used in salads.","Sıklıkla salatalarda kullanılan kırmızı meyve.","TOMATO",6,1,2,"../images/6/2/16.webp"],
  ["A vegetable that grows under the ground.","Toprak altında yetişen bir sebze.","POTATO",6,1,2,"../images/6/2/17.webp"],
  ["A food made from milk.","Sütten yapılan yiyecek.","CHEESE",6,1,2,"../images/6/2/18.webp"],
  ["A type of spicy meat people slice and eat.","İnsanların dilimleyip yediği baharatlı et türü.","SALAMI",6,2,2,"../images/6/2/19.webp"],
  ["A long green vegetable with lots of water.","Bol su içeren uzun yeşil sebze.","CUCUMBER",6,3,2,"../images/6/2/20.webp"],
  ["A sweet food made by bees.","Arılar tarafından yapılan tatlı yiyecek.","HONEY",6,1,2,"../images/6/2/21.webp"],
  ["A baked food made from flour.","Undan yapılan fırın yiyeceği.","BREAD",6,1,2,"../images/6/2/22.webp"],
  ["A strong-smelling white vegetable used in cooking.","Yemek pişirmede kullanılan güçlü kokulu beyaz sebze.","GARLIC",6,2,2,"../images/6/2/23.webp"],
  ["Small seeds people cook and eat.","İnsanların pişirip yediği küçük tohumlar.","BEANS",6,3,2,"../images/6/2/24.webp"],
  ["A healthy plant people eat.","İnsanların yediği sağlıklı bitki.","VEGETABLE",6,2,2,"../images/6/2/25.webp"],
  ["A round vegetable that can make you cry.","Seni ağlatabilecek yuvarlak sebze.","ONION",6,2,2,"../images/6/2/26.webp"],
  ["Fruit that is new and not old.","Yeni ve taze meyve.","FRESH FRUIT",6,2,2,"../images/6/2/27.webp"],
  ["Small green or black fruits people eat.","İnsanların yediği küçük yeşil veya siyah meyveler.","OLIVES",6,1,2,"../images/6/2/28.webp"],
  ["A sweet white thing used in food and drinks.","Yiyecek ve içeceklerde kullanılan tatlı beyaz şey.","SUGAR",6,1,2,"../images/6/2/29.webp"],
  ["A white powder that gives food flavor.","Yiyeceklere lezzet katan beyaz toz.","SALT",6,2,2,"../images/6/2/30.webp"],
  ["Cooked in an oven.","Fırında pişirilmiş.","BAKED",6,2,2,"../images/6/2/31.webp"],
  ["Cooked in hot oil.","Sıcak yağda pişirilmiş.","FRIED",6,3,2,"../images/6/2/32.webp"],
  ["Cooked over fire or heat.","Ateş veya ısı üzerinde pişirilmiş.","GRILLED",6,2,2,"../images/6/2/33.webp"],
  ["Cooked in hot water.","Sıcak suda pişirilmiş.","BOILED",6,3,2,"../images/6/2/34.webp"],
  ["A healthy grain often eaten at breakfast.","Kahvaltıda sıkça yenen sağlıklı tahıl.","OAT",6,3,2,"../images/6/2/35.webp"],
  ["Very tasty and good to eat.","Çok lezzetli ve yemesi güzel.","DELICIOUS",6,2,2,"../images/6/2/36.webp"],
  ["To like one thing more than another.","Bir şeyi diğerinden daha çok sevmek.","PREFER",6,2,2,"../images/6/2/37.webp"],
  ["To like doing something.","Bir şey yapmaktan hoşlanmak.","ENJOY",6,2,2,"../images/6/2/38.webp"],
  ["To make food by heating it.","Isıtarak yemek yapmak.","COOK",6,1,2,"../images/6/2/39.webp"],
  ["To get something by paying money.","Para ödeyerek bir şey almak.","BUY",6,3,2,"../images/6/2/40.webp"],
  ["The flavor of food or drink.","Yiyecek veya içeceğin tadı.","TASTE",6,3,2,"../images/6/2/41.webp"],
  ["To get something ready.","Bir şeyi hazırlamak.","PREPARE",6,3,2,"../images/6/2/42.webp"],
  ["Wanting to eat food.","Yemek yemek istemek.","HUNGRY",6,2,2,"../images/6/2/43.webp"],
  ["Wanting to drink something.","Bir şeyler içmek istemek.","THIRSTY",6,2,2,"../images/6/2/44.webp"],
  ["Following old customs or ways.","Eski gelenek veya yolları takip eden.","TRADITIONAL",6,3,2,"../images/6/2/45.webp"],
  ["Good for your body.","Vücudunuz için iyi olan.","HEALTHY",6,2,2,"../images/6/2/46.webp"],
  ["Bad for your body.","Vücudunuz için kötü olan.","UNHEALTHY",6,2,2,"../images/6/2/47.webp"],
  ["Unhealthy food like chips or burgers.","Cips veya hamburger gibi sağlıksız yiyecek.","JUNK FOOD",6,1,2,"../images/6/2/48.webp"],
  ["A small amount of food between meals.","Öğünler arasında yenen küçük miktar yiyecek.","SNACK",6,1,2,"../images/6/2/49.webp"],
  ["Food prepared to eat at lunch or dinner.","Öğle veya akşam yemeğinde yemek için hazırlanan yiyecek.","MEAL",6,2,2,"../images/6/2/50.webp"],

  // ─── GRADE 6 UNIT 3 ──────────────────────────────────────────────────────────
  ["Full of many people.","Pek çok insanla dolu.","CROWDED",6,2,3,"../images/6/3/1.webp"],
  ["Very active.","Çok meşgul veya hareketli.","BUSY",6,2,3,"../images/6/3/1.webp"],
  ["The busy center of a city.","Bir şehrin yoğun merkezi.","DOWNTOWN",6,2,3,"../images/6/3/2.webp"],
  ["When many cars cannot move on the road.","Araçların yolda hareket edemediği durum.","TRAFFIC JAM",6,1,3,"../images/6/3/3.webp"],
  ["The city or town where you were born.","Doğduğun şehir veya kasaba.","HOMETOWN",6,2,3,"../images/6/3/4.webp"],
  ["A small shop or stall on a street.","Sokaktaki küçük dükkan ya da tezgâh.","KIOSK",6,2,3,"../images/6/3/5.webp"],
  ["To look at two things to see how they are different.","İki şeye bakıp farklılıklarını görmek.","COMPARE",6,2,3,"../images/6/3/6.webp"],
  ["To give something to someone for money.","Birine para karşılığında bir şey vermek.","SELL",6,2,3,"../images/6/3/7.webp"],
  ["A very tall building in a city.","Şehirdeki çok yüksek bina.","SKYSCRAPER",6,2,3,"../images/6/3/8.webp"],
  ["A road in a town or city.","Kasaba veya şehirdeki yol.","STREET",6,1,3,"../images/6/3/9.webp"],
  ["A very small town in the countryside.","Kırsaldaki çok küçük yerleşim yeri.","VILLAGE",6,2,3,"../images/6/3/10.webp"],
  ["A place bigger than a village but smaller than a city.","Köyden büyük, şehirden küçük bir yer.","TOWN",6,1,3,"../images/6/3/11.webp"],
  ["A large place with many people and buildings.","Pek çok insan ve bina olan büyük bir yer.","CITY",6,1,3,"../images/6/3/12.webp"],
  ["To give food to a person or animal.","Bir kişiye veya hayvana yemek vermek.","FEED",6,1,3,"../images/6/3/13.webp"],
  ["A place where animals are kept and crops are grown.","Hayvanların bakıldığı ve ürün yetiştirildiği yer.","FARM",6,1,3,"../images/6/3/14.webp"],
  ["An apartment where people live.","İnsanların yaşadığı daire.","FLAT",6,3,3,"../images/6/3/15.webp"],
  ["At this time.","Şu anda.","NOW",6,2,3,"../images/6/3/16.webp"],
  ["At this exact moment.","Tam şu an.","RIGHT NOW",6,2,3,"../images/6/3/16.webp"],
  ["Happening at this time.","Şu anda olan.","AT THE MOMENT",6,3,3,"../images/6/3/16.webp"],
  ["The area around your home.","Evinizin çevresindeki alan.","NEIGHBORHOOD",6,3,3,"../images/6/3/17.webp"],
  ["Higher in quality than before.","Öncekinden daha iyi kalitede.","BETTER",6,2,3,"../images/6/3/6.webp"],
  ["Lower in quality than before.","Öncekinden daha kötü kalitede.","WORSE",6,2,3,"../images/6/3/6.webp"],
  ["Fun and pleasant to do.","Yapmaktan keyif alınan ve hoş.","ENJOYABLE",6,2,3,"../images/6/3/20.webp"],
  ["Making you feel calm and rested.","Sizi sakin ve dinlenmiş hissettiren.","RELAXING",6,2,3,"../images/6/3/21.webp"],
  ["A line of people waiting for something.","Bir şey için bekleyen insan sırası.","QUEUE",6,3,3,"../images/6/3/22.webp"],
  ["People standing one after another waiting.","Sırayla bekleyen insanlar.","LINE",6,3,3,"../images/6/3/22.webp"],
  ["An open area in a city surrounded by buildings.","Şehirde binalarla çevrili açık alan.","SQUARE",6,3,3,"../images/6/3/23.webp"],
  ["A structure with walls and a roof where people live or work.","Duvarları ve çatısı olan yapı.","BUILDING",6,3,3,"../images/6/3/24.webp"],
  ["An outdoor area with equipment for children to play.","Çocukların oynaması için ekipman olan açık alan.","PLAYGROUND",6,2,3,"../images/6/3/25.webp"],
  ["Feeling nice, relaxed, and at ease.","Rahat ve huzurlu hissetmek.","COMFORTABLE",6,2,3,"../images/6/3/26.webp"],
  ["To go from one side of the road to the other.","Yolun bir tarafından diğerine geçmek.","CROSS",6,2,3,"../images/6/3/27.webp"],
  ["The number of people living in a place.","Bir yerde yaşayan insan sayısı.","POPULATION",6,3,3,"../images/6/3/28.webp"],
  ["Money you pay regularly to live in a place.","Bir yerde yaşamak için düzenli ödediğin para.","RENT",6,3,3,"../images/6/3/29.webp"],
  ["To stay in a place until something happens.","Bir şey olana kadar bir yerde kalmak.","WAIT",6,2,3,"../images/6/3/30.webp"],
  ["To get something ready.","Bir şeyi hazırlamak.","PREPARE",6,3,3,"../images/6/3/31.webp"],
  ["The way of living in a village or countryside.","Köyde veya kırsalda yaşama biçimi.","COUNTRY LIFE",6,2,3,"../images/6/3/32.webp"],
  ["Very pretty to look at.","Bakması çok güzel.","BEAUTIFUL",6,1,3,"../images/6/3/33.webp"],
  ["Not nice to look at.","Bakması hoş olmayan, çirkin.","UGLY",6,1,3,"../images/6/3/34.webp"],
  ["Higher than usual from bottom to top.","Alttan üste normalden yüksek, uzun boylu.","TALL",6,1,3,"../images/6/3/35.webp"],
  ["Greater than usual from one end to the other.","Bir uçtan diğerine normalden uzun.","LONG",6,1,3,"../images/6/3/35.webp"],
  ["Not tall or not long.","Kısa.","SHORT",6,1,3,"../images/6/3/36.webp"],
  ["Far above the ground.","Yerden çok yukarıda.","HIGH",6,2,3,"../images/6/3/37.webp"],
  ["Near or close to the ground.","Yere yakın veya alçakta.","LOW",6,2,3,"../images/6/3/38.webp"],
  ["Not dirty, tidy and fresh.","Kirli değil, düzenli ve temiz.","CLEAN",6,1,3,"../images/6/3/39.webp"],
  ["Not clean, with mud or stains.","Temiz değil, çamurlu veya lekeli.","DIRTY",6,1,3,"../images/6/3/40.webp"],
  ["Costs a lot of money.","Çok para tutar.","EXPENSIVE",6,3,3,"../images/6/3/41.webp"],
  ["Does not cost much money.","Fazla para tutmaz, ucuz.","CHEAP",6,2,3,"../images/6/3/42.webp"],
  ["Large in size.","Büyük boyutlu.","BIG",6,1,3,"../images/6/3/43.webp"],
  ["Very big in size.","Çok büyük boyutlu.","LARGE",6,2,3,"../images/6/3/43.webp"],
  ["Little in size.","Küçük boyutlu.","SMALL",6,1,3,"../images/6/3/44.webp"],
  ["Full of loud sounds.","Yüksek seslerle dolu.","NOISY",6,2,3,"../images/6/3/45.webp"],
  ["Without much noise or sound.","Fazla gürültü veya ses olmadan.","QUIET",6,2,3,"../images/6/3/46.webp"],
  ["Not safe, able to cause harm.","Güvenli olmayan, zarar verebilecek.","DANGEROUS",6,2,3,"../images/6/3/47.webp"],
  ["Free from danger.","Tehlikeden uzak.","SAFE",6,2,3,"../images/6/3/48.webp"],
  ["Nice or positive.","İyi veya olumlu.","GOOD",6,1,3,"../images/6/3/49.webp"],
  ["Not good.","İyi olmayan, kötü.","BAD",6,1,3,"../images/6/3/50.webp"],
  ["Making you feel very happy and interested.","Sizi çok mutlu ve heyecanlı hissettiren.","EXCITING",6,2,3,"../images/6/3/51.webp"],
  ["Not interesting or fun.","İlginç veya eğlenceli olmayan.","BORING",6,1,3,"../images/6/3/52.webp"],

  // ─── GRADE 6 UNIT 4 ──────────────────────────────────────────────────────────
  ["Weather when the sun is shining brightly in the sky.","Güneşin gökyüzünde parlak şekilde parladığı hava durumu.","SUNNY",6,1,4,"../images/6/4/1.webp"],
  ["Weather when rain is falling from the sky.","Gökten yağmurun yağdığı hava durumu.","RAINY",6,1,4,"../images/6/4/2.webp"],
  ["Weather with some clouds but also some sun.","Hem bulutların hem de güneşin olduğu hava durumu.","PARTLY CLOUDY",6,2,4,"../images/6/4/3.webp"],
  ["Weather with thick mist that makes it hard to see.","Görmeyi zorlaştıran yoğun sis nedeniyle oluşan hava durumu.","FOGGY",6,2,4,"../images/6/4/4.webp"],
  ["Weather when the wind is blowing strongly.","Rüzgarın güçlü şekilde estiği hava durumu.","WINDY",6,1,4,"../images/6/4/5.webp"],
  ["Weather that is extremely cold.","Çok soğuk olan hava durumu.","FREEZING",6,2,4,"../images/6/4/6.webp"],
  ["Weather that is extremely cold.","Çok soğuk olan hava durumu.","CHILLY",6,3,4,"../images/6/4/6.webp"],
  ["A bright flash of light seen in the sky during a storm.","Fırtına sırasında gökyüzünde görülen parlak ışık çakması.","LIGHTNING",6,3,4,"../images/6/4/7.webp"],
  ["A loud rumbling sound heard after lightning in the sky.","Gökyüzündeki şimşekten sonra duyulan güçlü gürültü.","THUNDER",6,3,4,"../images/6/4/8.webp"],
  ["Weather with strong wind and heavy rain together.","Güçlü rüzgar ve şiddetli yağmurun birlikte olduğu hava.","STORMY",6,3,4,"../images/6/4/9.webp"],
  ["Weather that feels pleasantly hot, not too much.","Hoş ve çok sıcak olmayan hava durumu.","WARM",6,1,4,"../images/6/4/10.webp"],
  ["Weather that feels very nice and enjoyable.","Çok güzel ve keyifli hissettiren hava durumu.","PLEASANT",6,3,4,"../images/6/4/10.webp"],
  ["Weather that is neither too hot nor too cold.","Ne çok sıcak ne de çok soğuk olan ılıman hava.","MILD",6,3,4,"../images/6/4/10.webp"],
  ["Weather with a very high temperature.","Sıcaklığın çok yüksek olduğu hava durumu.","HOT",6,1,4,"../images/6/4/13.webp"],
  ["Weather with a low temperature, needing warm clothes.","Düşük sıcaklıklı, sıcak kıyafet gerektiren hava.","COLD",6,1,4,"../images/6/4/14.webp"],
  ["Weather that is slightly cold but comfortable.","Biraz soğuk ama rahat hissettiren hava durumu.","COOL",6,2,4,"../images/6/4/15.webp"],
  ["Weather when small balls of ice fall from the sky.","Küçük buz toplarının gökten düştüğü hava durumu.","HAILING",6,3,4,"../images/6/4/16.webp"],
  ["Weather that is wonderful and amazing.","Harika ve mükemmel olan hava durumu.","FABULOUS",6,3,4,"../images/6/4/17.webp"],
  ["The condition of the air outside at a particular time.","Belirli bir anda dışarıdaki havanın durumu.","WEATHER",6,2,4,"../images/6/4/18.webp"],
  ["A measure of how hot or cold the air is.","Havanın ne kadar sıcak veya soğuk olduğunu gösteren ölçüm.","TEMPERATURE",6,3,4,"../images/6/4/19.webp"],
  ["A unit used to measure temperature.","Sıcaklığı ölçmek için kullanılan birim.","DEGREE",6,2,4,"../images/6/4/22.webp"],
  ["To have a physical or emotional sensation.","Fiziksel veya duygusal bir his yaşamak.","FEEL",6,2,4,"../images/6/4/23.webp"],
  ["A figure made from packed snow that looks like a person.","Sıkıştırılmış kardan yapılan, insana benzeyen şekil.","SNOWMAN",6,1,4,"../images/6/4/25.webp"],
  ["A surface that is very smooth and easy to slide or fall on.","Çok kaygan ve üzerinde kaymayı kolaylaştıran yüzey.","SLIPPERY",6,3,4,"../images/6/4/26.webp"],
  ["A strong feeling such as happiness, sadness, or anger.","Mutluluk, üzüntü veya öfke gibi güçlü bir his.","EMOTION",6,3,4,"../images/6/4/23.webp"],
  ["Feeling joyful and pleased about something.","Bir şey hakkında neşeli ve memnun hissetmek.","HAPPY",6,1,4,"../images/6/4/28.webp"],
  ["Feeling very annoyed or cross about something.","Bir şey hakkında çok kızgın veya sinirli hissetmek.","ANGRY",6,2,4,"../images/6/4/29.webp"],
  ["Feeling unhappy or sorrowful.","Mutsuz veya üzgün hissetmek.","SAD",6,2,4,"../images/6/4/30.webp"],
  ["Feeling unhappy or sorrowful.","Mutsuz veya üzgün hissetmek.","UPSET",6,2,4,"../images/6/4/30.webp"],
  ["Feeling uninterested because there is nothing exciting to do.","Heyecanlı bir şey olmadığı için ilgisiz ve sıkılmış hissetmek.","BORED",6,1,4,"../images/6/4/31.webp"],
  ["Feeling uninterested because there is nothing exciting to do.","Heyecanlı bir şey olmadığı için ilgisiz ve sıkılmış hissetmek.","DULL",6,2,4,"../images/6/4/31.webp"],
  ["Having feelings that change quickly and often.","Sık sık ve hızlıca değişen duygulara sahip olmak.","MOODY",6,3,4,"../images/6/4/32.webp"],
  ["Having a lot of energy and enthusiasm.","Çok enerjik ve hevesli hissetmek.","ENERGETIC",6,2,4,"../images/6/4/33.webp"],
  ["Feeling that you need to rest or sleep.","Dinlenmek veya uyumak isteyecek kadar yorgun hissetmek.","TIRED",6,1,4,"../images/6/4/34.webp"],
  ["Feeling like you want to fall asleep soon.","Yakında uyuyakalacakmış gibi hissetmek.","SLEEPY",6,1,4,"../images/6/4/35.webp"],
  ["Feeling shock because something unexpected happened.","Beklenmedik bir şey olduğu için şaşırmış hissetmek.","SURPRISED",6,2,4,"../images/6/4/36.webp"],
  ["Feeling fear because of something frightening.","Korkutucu bir şey nedeniyle korku hissetmek.","SCARED",6,2,4,"../images/6/4/37.webp"],
  ["Feeling fear because of something frightening.","Korkutucu bir şey nedeniyle korku hissetmek.","AFRAID",6,3,4,"../images/6/4/37.webp"],
  ["Feeling anxious because you think something might go wrong.","Bir şeylerin ters gidebileceğini düşünerek endişeli hissetmek.","WORRIED",6,3,4,"../images/6/4/38.webp"],
  ["Feeling nervous and uneasy about something uncertain.","Belirsiz bir şey hakkında gergin ve tedirgin hissetmek.","ANXIOUS",6,3,4,"../images/6/4/38.webp"],
  ["Feeling tense and worried before doing something important.","Önemli bir şey yapmadan önce gergin ve tedirgin hissetmek.","NERVOUS",6,3,4,"../images/6/4/38.webp"],
  ["Feeling very bad or unwell in body or mind.","Beden veya ruh olarak çok kötü hissetmek.","TERRIBLE",6,3,4,"../images/6/4/41.webp"],
  ["Feeling very bad or unwell in body or mind.","Beden veya ruh olarak çok kötü hissetmek.","AWFUL",6,2,4,"../images/6/4/41.webp"],
  ["One of the four parts of the year with different weather.","Farklı hava durumlarına sahip yılın dört bölümünden biri.","SEASON",6,1,4,"../images/6/4/42.webp"],
  ["The season when flowers bloom and weather gets warmer.","Çiçeklerin açtığı ve havanın ısındığı mevsim.","SPRING",6,1,4,"../images/6/4/43.webp"],
  ["The hottest season of the year when we go swimming.","Yılın en sıcak mevsimi, denize girdiğimiz zaman.","SUMMER",6,1,4,"../images/6/4/44.webp"],
  ["The season when leaves fall from the trees.","Yaprakların ağaçlardan döküldüğü mevsim.","AUTUMN",6,2,4,"../images/6/4/45.webp"],
  ["The season when leaves fall from the trees.","Yaprakların ağaçlardan döküldüğü mevsim.","FALL",6,2,4,"../images/6/4/45.webp"],
  ["The coldest season of the year, often with snow.","Yılın en soğuk mevsimi, genellikle kar yağar.","WINTER",6,1,4,"../images/6/4/46.webp"],
  ["A device that opens up to protect you from rain.","Yağmurdan korunmak için açılan araç.","UMBRELLA",6,2,4,"../images/6/4/47.webp"],
  ["A waterproof coat worn to stay dry in the rain.","Yağmurda kuru kalmak için giyilen su geçirmez ceket.","RAINCOAT",6,2,4,"../images/6/4/48.webp"],
  ["Warm gloves that cover all your fingers together.","Tüm parmaklarınızı birlikte örten sıcak eldivenler.","MITTENS",6,3,4,"../images/6/4/49.webp"],
  ["Strong shoes worn on feet in rainy or snowy weather.","Yağmurlu veya karlı havalarda ayaklara giyilen sağlam ayakkabı.","BOOTS",6,1,4,"../images/6/4/50.webp"],

  // ─── GRADE 6 UNIT 5 ──────────────────────────────────────────────────────────
  ["An outdoor festival with games, rides, and entertainment.","Oyunlar, atraksiyonlar ve eğlencenin olduğu açık hava festivali.","CARNIVAL",6,2,5,"../images/6/5/1.webp"],
  ["An outdoor event with games, food, and fun activities.","Oyunlar, yiyecekler ve eğlenceli etkinlikler bulunan açık hava etkinliği.","FAIR",6,2,5,"../images/6/5/1.webp"],
  ["A large park with exciting rides and attractions.","Heyecanlı atraksiyonlar ve binişlerin bulunduğu büyük park.","AMUSEMENT PARK",6,2,5,"../images/6/5/1.webp"],
  ["A large park with exciting rides and attractions.","Heyecanlı atraksiyonlar ve binişlerin bulunduğu büyük park.","FUNFAIR",6,2,5,"../images/6/5/1.webp"],
  ["A small piece of paper or card that lets you enter a place.","Bir yere girmeni sağlayan küçük kağıt veya kart.","TICKET",6,2,5,"../images/6/5/4.webp"],
  ["A small coin-like object used to play games at a fair.","Fuarda oyun oynamak için kullanılan küçük madeni para benzeri nesne.","TOKEN",6,2,5,"../images/6/5/5.webp"],
  ["Your personal view or thought about something.","Bir şey hakkındaki kişisel görüşünüz veya düşünceniz.","OPINION",6,3,5,"../images/6/5/6.webp"],
  ["The framework of bones that supports the body.","Vücudu destekleyen kemik iskeleti.","SKELETON",6,2,5,"../images/6/5/7.webp"],
  ["A scary or strange imaginary creature.","Korkutucu veya garip hayali bir yaratık.","MONSTER",6,2,5,"../images/6/5/8.webp"],
  ["A scary or strange imaginary creature.","Korkutucu veya garip hayali bir yaratık.","CREATURE",6,2,5,"../images/6/5/8.webp"],
  ["Not afraid of anything.","Hiçbir şeyden korkmayan.","FEARLESS",6,3,5,"../images/6/5/9.webp"],
  ["An area with many games and rides for children to enjoy.","Çocukların keyif alması için pek çok oyun ve atraksiyon olan alan.","PLAYGROUND",6,1,5,"../images/6/5/10.webp"],
  ["A person who goes to a place to see or experience it.","Bir yeri görmek veya deneyimlemek için giden kişi.","VISITOR",6,3,5,"../images/6/5/11.webp"],
  ["A board or notice that gives information or directions.","Bilgi veya yön gösteren tahta veya duyuru.","SIGN",6,3,5,"../images/6/5/12.webp"],
  ["To share the same opinion as someone else.","Başkasıyla aynı görüşü paylaşmak.","AGREE",6,2,5,"../images/6/5/13.webp"],
  ["To have a different opinion from someone else.","Başkasından farklı bir görüşe sahip olmak.","DISAGREE",6,2,5,"../images/6/5/14.webp"],
  ["A funny performer who makes people laugh with jokes and tricks.","Şakalar ve numaralarla insanları güldüren komik sanatçı.","CLOWN",6,1,5,"../images/6/5/15.webp"],
  ["Something you win in a competition or game.","Bir yarışma veya oyunda kazandığınız şey.","PRIZE",6,2,5,"../images/6/5/16.webp"],
  ["A performer who does amazing tricks that seem like magic.","Sihir gibi görünen harika numaralar yapan sanatçı.","MAGICIAN",6,2,5,"../images/6/5/17.webp"],
  ["A show where people watch acrobats, clowns, and animals perform.","İnsanların akrobatları, palyaçoları ve hayvanları izlediği gösteri.","CIRCUS",6,2,5,"../images/6/5/18.webp"],
  ["A sweet fluffy pink sugary snack sold at fairs.","Fuarlarda satılan tatlı ve kabarık pembe şekerli atıştırmalık.","COTTON CANDY",6,2,5,"../images/6/5/19.webp"],
  ["The money you pay to get into a place.","Bir yere girmek için ödediğiniz para.","ENTRANCE FEE",6,3,5,"../images/6/5/20.webp"],
  ["A way out of a building or area.","Bir bina veya alandan çıkış yolu.","EXIT",6,1,5,"../images/6/5/21.webp"],
  ["Moving or happening at great speed.","Büyük bir hızla hareket eden veya gerçekleşen.","FAST",6,1,5,"../images/6/5/22.webp"],
  ["Moving or happening at a very low speed.","Çok düşük bir hızda hareket eden veya gerçekleşen.","SLOW",6,1,5,"../images/6/5/23.webp"],
  ["Small cars at an amusement park that gently bump into each other.","Eğlence parkında birbirlerine hafifçe çarpan küçük arabalar.","BUMPER CAR",6,1,5,"../images/6/5/24.webp"],
  ["A fairground ride with horses or seats that goes around in circles.","Atlar veya koltukların daireler çizerek döndüğü lunapark atraksiyonu.","CARROUSEL",6,2,5,"../images/6/5/25.webp"],
  ["A dark spooky ride at a fair with scary ghost effects.","Fuarda hayalet efektleriyle dolu karanlık ve ürkütücü biniş.","GHOST TRAIN",6,1,5,"../images/6/5/26.webp"],
  ["A very fast ride with steep drops at an amusement park.","Eğlence parkında sarp düşüşler içeren çok hızlı bir biniş.","ROLLER COASTER",6,1,5,"../images/6/5/27.webp"],
  ["A giant wheel that turns slowly at a fairground.","Fuarda yavaşça dönen dev çark atraksiyonu.","FERRIS WHEEL",6,2,5,"../images/6/5/28.webp"],
  ["A fairground ride with chairs that swing out while spinning.","Dönerken koltuklarının dışa fırladığı lunapark atraksiyonu.","WAVE SWINGER",6,3,5,"../images/6/5/29.webp"],
  ["Making people feel very scared and frightened.","İnsanları çok korkutan ve ürküten.","TERRIFYING",6,3,5,"../images/6/5/30.webp"],
  ["Making you want to find out more about it.","Hakkında daha fazla bilmek istemenizi sağlayan.","INTERESTING",6,3,5,"../images/6/5/31.webp"],
  ["Fun and pleasant to do or experience.","Yapmaktan veya deneyimlemekten keyif alınan.","ENJOYABLE",6,2,5,"../images/6/5/32.webp"],
  ["Fun and pleasant to do or experience.","Yapmaktan veya deneyimlemekten keyif alınan.","FUN",6,1,5,"../images/6/5/32.webp"],
  ["Very exciting and full of action.","Çok heyecanlı ve aksiyonla dolu.","THRILLING",6,3,5,"../images/6/5/34.webp"],
  ["Extremely good and impressive.","Son derece iyi ve etkileyici.","FANTASTIC",6,2,5,"../images/6/5/35.webp"],
  ["Feeling very happy and enthusiastic about something coming.","Gelecek bir şey hakkında çok mutlu ve hevesli hissetmek.","EXCITED",6,2,5,"../images/6/5/39.webp"],
  ["Very bad, unpleasant, or frightening.","Çok kötü, nahoş veya korkutucu.","HORRIBLE",6,3,5,"../images/6/5/40.webp"],
  ["Much better than expected, very impressive.","Beklenenden çok daha iyi, çok etkileyici.","AMAZING",6,2,5,"../images/6/5/35.webp"],

  // ─── GRADE 6 UNIT 6 ──────────────────────────────────────────────────────────
  ["A person who designs and plans buildings.","Binaları tasarlayan ve planlayan kişi.","ARCHITECT",6,2,6,"../images/6/6/1.webp"],
  ["A person who does office tasks and helps a manager.","Ofis görevleri yapan ve yöneticiye yardım eden kişi.","SECRETARY",6,2,6,"../images/6/6/2.webp"],
  ["A person who makes bread and cakes.","Ekmek ve kek yapan kişi.","BAKER",6,2,6,"../images/6/6/3.webp"],
  ["A person whose job is to prepare and cook food.","İşi yemek hazırlamak ve pişirmek olan kişi.","COOK",6,1,6,"../images/6/6/4.webp"],
  ["A person whose job is to prepare and cook food.","İşi yemek hazırlamak ve pişirmek olan kişi.","CHEF",6,1,6,"../images/6/6/4.webp"],
  ["A person who leads and makes decisions for a team or company.","Bir ekip veya şirkete liderlik eden ve karar veren kişi.","MANAGER",6,2,6,"../images/6/6/5.webp"],
  ["A person who leads and makes decisions for a team or company.","Bir ekip veya şirkete liderlik eden ve karar veren kişi.","DIRECTOR",6,2,6,"../images/6/6/5.webp"],
  ["A person who studies and discovers new things about the world.","Dünya hakkında yeni şeyler araştıran ve keşfeden kişi.","SCIENTIST",6,2,6,"../images/6/6/6.webp"],
  ["A person who checks and treats people's teeth.","İnsanların dişlerini kontrol eden ve tedavi eden kişi.","DENTIST",6,1,6,"../images/6/6/7.webp"],
  ["A person who repairs cars and machines.","Araba ve makineleri onaran kişi.","MECHANIC",6,2,6,"../images/6/6/8.webp"],
  ["A person who manages and takes care of the home and family.","Evi ve aileyi yöneten ve onlara bakan kişi.","HOUSEWIFE",6,2,6,"../images/6/6/9.webp"],
  ["A person whose job is to drive a vehicle.","İşi araç kullanmak olan kişi.","DRIVER",6,1,6,"../images/6/6/10.webp"],
  ["A person whose job is to sell products to customers.","İşi müşterilere ürün satmak olan kişi.","SALESWOMAN",6,3,6,"../images/6/6/11.webp"],
  ["A person who has stopped working because of age.","Yaşı nedeniyle çalışmayı bırakan kişi.","RETIRED",6,3,6,"../images/6/6/12.webp"],
  ["A person who designs and builds bridges, machines, or structures.","Köprüler, makineler veya yapılar tasarlayan ve inşa eden kişi.","ENGINEER",6,2,6,"../images/6/6/13.webp"],
  ["A person who serves food and drinks to customers in a restaurant.","Restoranda müşterilere yiyecek ve içecek servisi yapan kişi.","WAITRESS",6,2,6,"../images/6/6/14.webp"],
  ["A person whose job is to put out fires and rescue people.","İşi yangın söndürmek ve insanları kurtarmak olan kişi.","FIREFIGHTER",6,2,6,"../images/6/6/15.webp"],
  ["A person who grows crops and raises animals on a farm.","Çiftlikte bitki yetiştiren ve hayvan besleyen kişi.","FARMER",6,1,6,"../images/6/6/16.webp"],
  ["A person who does a job, usually with their hands.","Genellikle elleriyle bir iş yapan kişi.","WORKER",6,2,6,"../images/6/6/17.webp"],
  ["A person who cuts and sells meat.","Et kesen ve satan kişi.","BUTCHER",6,1,6,"../images/6/6/18.webp"],
  ["A person who cuts and styles people's hair.","İnsanların saçlarını kesen ve şekillendiren kişi.","HAIRDRESSER",6,2,6,"../images/6/6/19.webp"],
  ["A person who performs roles in movies, TV, or theatre.","Film, TV veya tiyatroda rol oynayan kişi.","ACTRESS",6,2,6,"../images/6/6/20.webp"],
  ["Another word for the job or work a person does.","Bir kişinin yaptığı iş veya meslek için başka bir kelime.","OCCUPATION",6,3,6,"../images/6/6/21.webp"],
  ["A person who helps people with legal problems in court.","İnsanlara mahkemede hukuki sorunlarında yardım eden kişi.","LAWYER",6,2,6,"../images/6/6/22.webp"],
  ["A person who performs songs for an audience.","Bir kitleye şarkı söyleyen kişi.","SINGER",6,2,6,"../images/6/6/23.webp"],
  ["A person who cares for and assists sick or injured people.","Hasta veya yaralı kişilere bakan ve yardım eden kişi.","NURSE",6,1,6,"../images/6/6/24.webp"],
  ["A doctor who treats and cares for animals.","Hayvanları tedavi eden ve onlara bakan doktor.","VET",6,1,6,"../images/6/6/25.webp"],
  ["A type of job that requires special training or education.","Özel eğitim veya eğitim gerektiren iş türü.","PROFESSION",6,3,6,"../images/6/6/21.webp"],
  ["A person whose job is to educate and teach students.","İşi öğrencileri eğitmek ve öğretmek olan kişi.","TEACHER",6,1,6,"../images/6/6/27.webp"],
  ["A person who examines and treats sick people.","Hasta insanları muayene eden ve tedavi eden kişi.","DOCTOR",6,1,6,"../images/6/6/28.webp"],
  ["A person who owns or runs a business.","Bir işletmenin sahibi olan veya onu yöneten kişi.","BUSINESSMAN",6,3,6,"../images/6/6/29.webp"],
  ["To make something work again after it has broken.","Bozulduktan sonra bir şeyi tekrar çalışır hale getirmek.","REPAIR",6,2,6,"../images/6/6/8.webp"],
  ["To make something work again after it has broken.","Bozulduktan sonra bir şeyi tekrar çalışır hale getirmek.","FIX",6,2,6,"../images/6/6/8.webp"],
  ["To look at something carefully to check or study it.","Kontrol etmek veya incelemek için bir şeye dikkatle bakmak.","EXAMINE",6,3,6,"../images/6/6/25.webp"],
  ["What a waiter does when listening to what a customer wants to eat.","Bir garsonun müşterinin ne yemek istediğini dinlerken yaptığı şey.","TAKE ORDER",6,3,6,"../images/6/6/33.webp"],
  ["The day before today.","Bugünden önceki gün.","YESTERDAY",6,1,6,""],
  ["The week before the current week.","Şu anki haftadan önceki hafta.","LAST WEEK",6,2,6,""],
  ["Two months before the present time.","Şu andan iki ay öncesi.","2 MONTHS AGO",6,2,6,""],
  ["What happens when a baby comes into the world.","Bir bebeğin dünyaya geldiğinde olan şey.","BORN",6,2,6,"../images/6/6/38.webp"],
  ["The specific day, month, and year when someone was born.","Birinin doğduğu belirli gün, ay ve yıl.","DATE OF BIRTH",6,2,6,"../images/6/6/39.webp"],

  // ─── GRADE 6 UNIT 7 ──────────────────────────────────────────────────────────
  ["Traveling on water with a boat.","Tekneyle su üzerinde seyahat etme.","SAILING",6,2,7,"../images/6/7/1.webp"],
  ["A winter sport done by moving on snow with long skis.","Uzun kayaklarla karda kayarak yapılan kış sporu.","SKIING",6,1,7,"../images/6/7/2.webp"],
  ["A small shelter to stay in when camping.","Kamp yaparken içinde kalınan küçük barınak.","TENT",6,1,7,"../images/6/7/3.webp"],
  ["An activity done by sleeping in a tent in nature.","Doğada çadırda uyuyarak yapılan aktivite.","CAMPING",6,1,7,"../images/6/7/4.webp"],
  ["Traveling on a river with a rubber boat.","Lastik botla nehirde seyahat etme.","RAFTING",6,1,7,"../images/6/7/5.webp"],
  ["A small building children make at the beach for fun.","Çocukların plajda eğlence için kumdan yaptığı küçük yapı.","SANDCASTLE",6,3,7,"../images/6/7/6.webp"],
  ["Swimming underwater with special air equipment.","Özel hava tüpü ekipmanıyla su altında yüzme.","SCUBA DIVING",6,1,7,"../images/6/7/7.webp"],
  ["Flying in the air with a parachute.","Paraşütle havada uçma.","PARAGLIDING",6,2,7,"../images/6/7/8.webp"],
  ["Walking for a long time in nature.","Doğada uzun süre yürüyüş yapma.","HIKING",6,1,7,"../images/6/7/9.webp"],
  ["A touristic tour to see interesting places.","İlginç yerleri görmek için yapılan turistik gezi.","SIGHTSEEING",6,3,7,"../images/6/7/10.webp"],
  ["A place with many trees.","İçinde pek çok ağaç bulunan alan.","FOREST",6,1,7,"../images/6/7/11.webp"],
  ["The colorful part of a plant.","Bitkinin renkli bölümü.","FLOWER",6,2,7,"../images/6/7/12.webp"],
  ["A large area of water.","Büyük su kütlesi.","LAKE",6,2,7,"../images/6/7/13.webp"],
  ["Long water moving across land.","Kara boyunca akan uzun su kütlesi.","RIVER",6,2,7,"../images/6/7/14.webp"],
  ["A very high hill.","Yüksek bir doğal arazi oluşumu.","MOUNTAIN",6,2,7,"../images/6/7/15.webp"],
  ["A sandy place near the sea.","Deniz kenarındaki kumluk alan.","BEACH",6,1,7,"../images/6/7/16.webp"],
  ["The area near the sea.","Denizin kenarındaki alanın ismi.","SEASIDE",6,2,7,"../images/6/7/16.webp"],
  ["To collect fruit from trees or plants.","Ağaçlardan veya bitkilerden meyve toplama.","PICK FRUIT",6,1,7,"../images/6/7/17.webp"],

  // ─── GRADE 6 UNIT 8 ──────────────────────────────────────────────────────────
  ["A person who writes books or stories. Other name for WRITER","Kitap yazan kişi. WRITER kelimesinin diğer adı.","AUTHOR",6,3,8,"../images/6/8/1.webp"],
  ["To take something for a short time.","Bir şeyi kısa bir süre için almak.","BORROW",6,3,8,"../images/6/8/2.webp"],
  ["To give something for a short time.","Bir şeyi kısa bir süre için vermek.","LEND",6,3,8,"../images/6/8/3.webp"],
  ["A place to put books in.","Kitap koymak için kullanılan eşya.","BOOK SHELF",6,1,8,"../images/6/8/4.webp"],
  ["You can find new words and their meanings in it","Kelimelerin anlamlarını açıklayan kitap.","DICTIONARY",6,3,8,"../images/6/8/5.webp"],
  ["A place to read or borrow books.","Kitap okuduğumuz veya ödünç aldığımız yer.","LIBRARY",6,1,8,"../images/6/8/6.webp"],
  ["A colorful book with articles and pictures.","Makaleler ve resimler içeren renkli yayın.","MAGAZINE",6,2,8,"../images/6/8/7.webp"],
  ["Writing with rhythm and feelings.","Ritim ve duygularla yazılan yazı türü.","POETRY",6,3,8,"../images/6/8/8.webp"],
  ["Papers with daily news.","Günlük haberlerin yer aldığı basılı kağıt.","NEWSPAPER",6,2,8,"../images/6/8/9.webp"],
  ["A long story book.","Uzun hikâye kitabı.","NOVEL",6,2,8,"../images/6/8/10.webp"],
  ["Facing across from something.","Bir şeyin karşısında yer alan.","OPPOSITE",6,2,8,"../images/6/8/11.webp"],
  ["At the back of something.","Bir şeyin arkasında yer alan.","BEHIND",6,1,8,"../images/6/8/12.webp"],
  ["In the middle of two things.","İki şeyin ortasında.","BETWEEN",6,2,8,"../images/6/8/13.webp"],
  ["Very near/beside something.","Bir şeyin hemen yanında veya yakınında.","NEXT TO",6,2,8,"../images/6/8/14.webp"],
  ["Below something.","Bir şeyin aşağısında.","UNDER",6,1,8,"../images/6/8/15.webp"],
  ["Above something.","Bir şeyin üzerinde.","OVER",6,2,8,"../images/6/8/16.webp"],

  