const singularPluralsFunction = {
  id: "singular-plurals",
  grade: 5,
  unit: 1,
  title: "Singular and Plural Nouns",
  description: "Using one noun or more than one noun.",
  exercises: ["ride-with-hannah-singular-plurals", "singular-plural-choice", "sort-it"],
  sentences: [
    { id: "one-cat", focus: "SINGULAR", referenceType: "ONE", sentence: "a cat", highlight: "cat", singular: "cat", plural: "cats", answer: "cat", exerciseSentence: "I can see a ___ in the garden.", imagePath: "images/singular-plurals/01-one-cat.webp", visualBrief: "One cat sitting in a garden." },
    { id: "two-cats", focus: "PLURAL", referenceType: "MORE THAN ONE", sentence: "two cats", highlightStem: "cat", highlightSuffix: "s", suffixClass: "ending-s", singular: "cat", plural: "cats", answer: "cats", exerciseSentence: "I can see two ___ in the garden.", imagePath: "images/singular-plurals/02-two-cats.webp", visualBrief: "Two cats sitting together in a garden." },
    { id: "one-box", focus: "SINGULAR", referenceType: "ONE", sentence: "a box", highlight: "box", singular: "box", plural: "boxes", answer: "box", exerciseSentence: "There is a ___ on the table.", imagePath: "images/singular-plurals/03-one-box.webp", visualBrief: "One box on a table." },
    { id: "three-boxes", focus: "PLURAL", referenceType: "MORE THAN ONE", sentence: "three boxes", highlightStem: "box", highlightSuffix: "es", suffixClass: "ending-es", singular: "box", plural: "boxes", answer: "boxes", exerciseSentence: "There are three ___ on the table.", imagePath: "images/singular-plurals/04-three-boxes.webp", visualBrief: "Three boxes on a table.", ruleNote: "Çoğu isme -s eklenir: cat -> cats. Sonu -s, -ss, -sh, -ch, -x veya -o ile biten kelimelere -es eklenir: box -> boxes." },
    { id: "one-baby", focus: "SINGULAR", referenceType: "ONE", sentence: "a baby", highlight: "baby", singular: "baby", plural: "babies", answer: "baby", exerciseSentence: "A ___ is sleeping.", imagePath: "images/singular-plurals/05-one-baby.webp", visualBrief: "One baby sleeping peacefully.", ruleNote: "Sonu sessiz harf + y ile biten kelimelerde y düşer ve -ies eklenir: baby -> babies." },
    { id: "two-babies", focus: "PLURAL", referenceType: "MORE THAN ONE", sentence: "two babies", highlightStem: "bab", highlightSuffix: "ies", suffixClass: "ending-ies", singular: "baby", plural: "babies", answer: "babies", exerciseSentence: "Two ___ are sleeping.", imagePath: "images/singular-plurals/06-two-babies.webp", visualBrief: "Two babies sleeping peacefully." },
    { id: "one-book", focus: "SINGULAR", referenceType: "ONE", sentence: "a book", highlight: "book", singular: "book", plural: "books", answer: "book", exerciseSentence: "There is a ___ on the desk.", imagePath: "images/singular-plurals/07-one-book.webp", visualBrief: "One book on a classroom desk." },
    { id: "two-books", focus: "PLURAL", referenceType: "MORE THAN ONE", sentence: "two books", highlightStem: "book", highlightSuffix: "s", suffixClass: "ending-s", singular: "book", plural: "books", answer: "books", exerciseSentence: "There are two ___ on the desk.", imagePath: "images/singular-plurals/08-two-books.webp", visualBrief: "Two books on a classroom desk." },
    { id: "one-bus", focus: "SINGULAR", referenceType: "ONE", sentence: "a bus", highlight: "bus", singular: "bus", plural: "buses", answer: "bus", exerciseSentence: "A ___ is at the bus stop.", imagePath: "images/singular-plurals/09-one-bus.webp", visualBrief: "One bus at a bus stop." },
    { id: "two-buses", focus: "PLURAL", referenceType: "MORE THAN ONE", sentence: "two buses", highlightStem: "bus", highlightSuffix: "es", suffixClass: "ending-es", singular: "bus", plural: "buses", answer: "buses", exerciseSentence: "Two ___ are at the bus stop.", imagePath: "images/singular-plurals/10-two-buses.webp", visualBrief: "Two buses at a bus stop." },
    { id: "one-city", focus: "SINGULAR", referenceType: "ONE", sentence: "a city", highlight: "city", singular: "city", plural: "cities", answer: "city", exerciseSentence: "This is a busy ___.", imagePath: "images/singular-plurals/11-one-city.webp", visualBrief: "One busy city with tall buildings." },
    { id: "two-cities", focus: "PLURAL", referenceType: "MORE THAN ONE", sentence: "two cities", highlightStem: "cit", highlightSuffix: "ies", suffixClass: "ending-ies", singular: "city", plural: "cities", answer: "cities", exerciseSentence: "These are two busy ___.", imagePath: "images/singular-plurals/12-two-cities.webp", visualBrief: "Two different busy cities." },
    { id: "one-woman", focus: "SINGULAR", referenceType: "ONE", sentence: "a woman", highlight: "woman", singular: "woman", plural: "women", answer: "woman", exerciseSentence: "A ___ is waiting for the bus.", imagePath: "images/singular-plurals/13-one-woman.webp", visualBrief: "One woman waiting at a bus stop.", ruleNote: "Bazı isimlerde -s, -es veya -ies kuralı kullanılmaz. Bunlar düzensiz çoğullardır ve çoğul halleri ezberlenir: woman -> women, man -> men, tooth -> teeth, child -> children." },
    { id: "two-women", focus: "PLURAL", referenceType: "MORE THAN ONE", sentence: "two women", highlightStem: "wo", highlightSuffix: "men", suffixClass: "ending-irregular", singular: "woman", plural: "women", answer: "women", exerciseSentence: "Two ___ are waiting for the bus.", imagePath: "images/singular-plurals/14-two-women.webp", visualBrief: "Two women waiting at a bus stop." },
    { id: "one-man", focus: "SINGULAR", referenceType: "ONE", sentence: "a man", highlight: "man", singular: "man", plural: "men", answer: "man", exerciseSentence: "A ___ is riding a bicycle.", imagePath: "images/singular-plurals/15-one-man.webp", visualBrief: "One man riding a bicycle." },
    { id: "two-men", focus: "PLURAL", referenceType: "MORE THAN ONE", sentence: "two men", highlightStem: "m", highlightSuffix: "en", suffixClass: "ending-irregular", singular: "man", plural: "men", answer: "men", exerciseSentence: "Two ___ are riding bicycles.", imagePath: "images/singular-plurals/16-two-men.webp", visualBrief: "Two men riding bicycles." },
    { id: "one-tooth", focus: "SINGULAR", referenceType: "ONE", sentence: "a tooth", highlight: "tooth", singular: "tooth", plural: "teeth", answer: "tooth", exerciseSentence: "A ___ is hurting.", imagePath: "images/singular-plurals/17-one-tooth.webp", visualBrief: "One tooth shown in a simple dental illustration." },
    { id: "two-teeth", focus: "PLURAL", referenceType: "MORE THAN ONE", sentence: "two teeth", highlightStem: "t", highlightSuffix: "eeth", suffixClass: "ending-irregular", singular: "tooth", plural: "teeth", answer: "teeth", exerciseSentence: "Two ___ are hurting.", imagePath: "images/singular-plurals/18-two-teeth.webp", visualBrief: "Two teeth shown in a simple dental illustration." },
    { id: "one-child", focus: "SINGULAR", referenceType: "ONE", sentence: "a child", highlight: "child", singular: "child", plural: "children", answer: "child", exerciseSentence: "A ___ is reading a book.", imagePath: "images/singular-plurals/19-one-child.webp", visualBrief: "One child reading a book." },
    { id: "two-children", focus: "PLURAL", referenceType: "MORE THAN ONE", sentence: "two children", highlightStem: "child", highlightSuffix: "ren", suffixClass: "ending-irregular", singular: "child", plural: "children", answer: "children", exerciseSentence: "Two ___ are reading books.", imagePath: "images/singular-plurals/20-two-children.webp", visualBrief: "Two children reading books together." }
  ]
};

window.functionModules = window.functionModules || [];
window.functionModules.push(singularPluralsFunction);
