const pronounSnapExercise = window.exerciseActivityModules.pronounSnap({
  id: "pronoun-snap",
  title: "PRONOUN SNAP",
  supports(functionModule) {
    return functionModule.id === "to-be-present";
  },
  units: [1, 2],
  roundDurationMs: 2000,
  roundCount: 20,
  rounds: [
    { pronoun: "he", imagePath: "images/pronoun_snap/10he.webp" },
    { pronoun: "they", imagePath: "images/pronoun_snap/10they.webp" },
    { pronoun: "she", imagePath: "images/pronoun_snap/11she.webp" },
    { pronoun: "they", imagePath: "images/pronoun_snap/12they.webp" },
    { pronoun: "he", imagePath: "images/pronoun_snap/13he.webp" },
    { pronoun: "they", imagePath: "images/pronoun_snap/13they.webp" },
    { pronoun: "she", imagePath: "images/pronoun_snap/14she.webp" },
    { pronoun: "they", imagePath: "images/pronoun_snap/14they.webp" },
    { pronoun: "they", imagePath: "images/pronoun_snap/15they.webp" },
    { pronoun: "they", imagePath: "images/pronoun_snap/16they.webp" },
    { pronoun: "it", imagePath: "images/pronoun_snap/17it.webp" },
    { pronoun: "they", imagePath: "images/pronoun_snap/17they.webp" },
    { pronoun: "they", imagePath: "images/pronoun_snap/18they.webp" },
    { pronoun: "she", imagePath: "images/pronoun_snap/19she.webp" },
    { pronoun: "they", imagePath: "images/pronoun_snap/19they.webp" },
    { pronoun: "he", imagePath: "images/pronoun_snap/1he.webp" },
    { pronoun: "they", imagePath: "images/pronoun_snap/1they.webp" },
    { pronoun: "they", imagePath: "images/pronoun_snap/20they.webp" },
    { pronoun: "they", imagePath: "images/pronoun_snap/21they.webp" },
    { pronoun: "she", imagePath: "images/pronoun_snap/22she.webp" },
    { pronoun: "they", imagePath: "images/pronoun_snap/22they.webp" },
    { pronoun: "it", imagePath: "images/pronoun_snap/23it.webp" },
    { pronoun: "they", imagePath: "images/pronoun_snap/23they.webp" },
    { pronoun: "they", imagePath: "images/pronoun_snap/24they.webp" },
    { pronoun: "it", imagePath: "images/pronoun_snap/25it.webp" },
    { pronoun: "she", imagePath: "images/pronoun_snap/25she.webp" },
    { pronoun: "he", imagePath: "images/pronoun_snap/26he.webp" },
    { pronoun: "she", imagePath: "images/pronoun_snap/26she.webp" },
    { pronoun: "they", imagePath: "images/pronoun_snap/26they.webp" },
    { pronoun: "he", imagePath: "images/pronoun_snap/27he.webp" },
    { pronoun: "it", imagePath: "images/pronoun_snap/27it.webp" },
    { pronoun: "it", imagePath: "images/pronoun_snap/28it.webp" },
    { pronoun: "they", imagePath: "images/pronoun_snap/28they.webp" },
    { pronoun: "he", imagePath: "images/pronoun_snap/29he.webp" },
    { pronoun: "it", imagePath: "images/pronoun_snap/29it.webp" },
    { pronoun: "he", imagePath: "images/pronoun_snap/2he.webp" },
    { pronoun: "they", imagePath: "images/pronoun_snap/2they.webp" },
    { pronoun: "he", imagePath: "images/pronoun_snap/30he.webp" },
    { pronoun: "it", imagePath: "images/pronoun_snap/30it.webp" },
    { pronoun: "he", imagePath: "images/pronoun_snap/31he.webp" },
    { pronoun: "it", imagePath: "images/pronoun_snap/31it.webp" },
    { pronoun: "she", imagePath: "images/pronoun_snap/31she.webp" },
    { pronoun: "it", imagePath: "images/pronoun_snap/32it.webp" },
    { pronoun: "he", imagePath: "images/pronoun_snap/33he.webp" },
    { pronoun: "she", imagePath: "images/pronoun_snap/34she.webp" },
    { pronoun: "they", imagePath: "images/pronoun_snap/34they.webp" },
    { pronoun: "he", imagePath: "images/pronoun_snap/35he.webp" },
    { pronoun: "she", imagePath: "images/pronoun_snap/37she.webp" },
    { pronoun: "they", imagePath: "images/pronoun_snap/38they.webp" },
    { pronoun: "he", imagePath: "images/pronoun_snap/39he.webp" },
    { pronoun: "she", imagePath: "images/pronoun_snap/3she.webp" },
    { pronoun: "he", imagePath: "images/pronoun_snap/40he.webp" },
    { pronoun: "it", imagePath: "images/pronoun_snap/41it.webp" },
    { pronoun: "she", imagePath: "images/pronoun_snap/41she.webp" },
    { pronoun: "she", imagePath: "images/pronoun_snap/42she.webp" },
    { pronoun: "they", imagePath: "images/pronoun_snap/43they.webp" },
    { pronoun: "they", imagePath: "images/pronoun_snap/45they.webp" },
    { pronoun: "they", imagePath: "images/pronoun_snap/46they.webp" },
    { pronoun: "it", imagePath: "images/pronoun_snap/49it.webp" },
    { pronoun: "he", imagePath: "images/pronoun_snap/4he.webp" },
    { pronoun: "she", imagePath: "images/pronoun_snap/51she.webp" },
    { pronoun: "it", imagePath: "images/pronoun_snap/54it.webp" },
    { pronoun: "they", imagePath: "images/pronoun_snap/55they.webp" },
    { pronoun: "they", imagePath: "images/pronoun_snap/56they.webp" },
    { pronoun: "they", imagePath: "images/pronoun_snap/57they.webp" },
    { pronoun: "he", imagePath: "images/pronoun_snap/58he.webp" },
    { pronoun: "he", imagePath: "images/pronoun_snap/59he.webp" },
    { pronoun: "it", imagePath: "images/pronoun_snap/60it.webp" },
    { pronoun: "it", imagePath: "images/pronoun_snap/61it.webp" },
    { pronoun: "it", imagePath: "images/pronoun_snap/62it.webp" },
    { pronoun: "it", imagePath: "images/pronoun_snap/63it.webp" },
    { pronoun: "she", imagePath: "images/pronoun_snap/64she.webp" },
    { pronoun: "she", imagePath: "images/pronoun_snap/65she.webp" },
    { pronoun: "she", imagePath: "images/pronoun_snap/66she.webp" },
    { pronoun: "they", imagePath: "images/pronoun_snap/67they.webp" },
    { pronoun: "he", imagePath: "images/pronoun_snap/6he.webp" },
    { pronoun: "it", imagePath: "images/pronoun_snap/7it.webp" },
    { pronoun: "it", imagePath: "images/pronoun_snap/8it.webp" },
    { pronoun: "they", imagePath: "images/pronoun_snap/9they.webp" }
  ]
});

window.exerciseModules = window.exerciseModules || [];
window.exerciseModules.push(pronounSnapExercise);
