// sp_questions.js — Word Reveal SP — Bağımsız Soru Havuzu
// ════════════════════════════════════════════════════════════════════════════
//
// Bu dosya word_reveal SP versiyonu için bağımsız soru bankasıdır.
// Orijinal questions.js ile bağlantısı yoktur — özgürce genişletebilirsin.
//
// Yeni kelime eklemek:
//   Formatı: ['İngilizce tanım', 'Türkçe karşılık', 'CEVAP', grade, catId, 'görsel_yolu', ['alternatif']]
//   grade: 1=6.sınıf  2=7.sınıf  3=8.sınıf  (sıralama seviye zorluğunu belirler)
//
// Görsel klasör yapısı:
//   Mevcut görseller → ../images/0/11/, ../images/6/2/, ../images/7/1/ vb.
//   Yeni SP görselleri → ../images/sp/catId/N.webp
//
// ⚠️  Image path'ler questions.js grade-0 catId entries'inden doğrudan alınmıştır.
//     Boş numara atlamalarına dikkat et — +1 ile tahmin YAPMA, dosyadan bak.
//
// ════════════════════════════════════════════════════════════════════════════

const SP_CATEGORY_NAMES = {
  11: '🐾 Animals',
  12: '🍔 Food & Drinks',
  13: '👤 Appearance & Personality',
  14: '⚽ Sports & Equipment',
  15: '🏙️ Places in Town',
  16: '💼 Occupations',
};

const SP_CATEGORY_THUMBS = {
  11: 'animals.webp',
  12: 'foodanddrinks.webp',
  13: 'appandpers.webp',
  14: 'sportsequip.webp',
  15: 'places.webp',
  16: 'jobs.webp',
};

const SP_WORDS = [

  // ══════════════════════════════════════════════════════════════════════════
  // CAT 11 — Animals  (47 mevcut + 3 eklenecek = 50 → 5 level × 10)
  // ══════════════════════════════════════════════════════════════════════════
  // ── Mevcut görseller → ../images/0/11/ ───────────────────────────────────
  // NOT: 0/11/ klasöründe 4.webp ve 14.webp yoktur — diğerleri atlayarak devam eder.
  ['A large bird of prey', 'Büyük bir yırtıcı kuş', 'EAGLE', 1, 11, '../images/0/11/1.webp', []],
  ['The largest land animal', 'Karadaki en büyük hayvan', 'ELEPHANT', 1, 11, '../images/0/11/2.webp', []],
  ['A reptile with no legs', 'Yılan', 'SNAKE', 1, 11, '../images/0/11/3.webp', []],
  ['The tallest animal', 'En uzun boylu hayvan', 'GIRAFFE', 1, 11, '../images/0/11/5.webp', []],
  ['A colourful talking bird', 'Renkli ve konuşabilen bir kuş', 'PARROT', 1, 11, '../images/0/11/6.webp', []],
  ['The king of the jungle', 'Ormanların kralı', 'LION', 1, 11, '../images/0/11/7.webp', []],
  ['A slow reptile with a shell', 'Kabuğu olan yavaş bir sürüngen', 'TURTLE', 1, 11, '../images/0/11/8.webp', []],
  ['A water animal with fins', 'Yüzgeçleri olan su hayvanlarının tümünün ismi', 'FISH', 1, 11, '../images/0/11/9.webp', []],
  ['A big striped wild cat', 'Çizgili büyük bir vahşi kedi', 'TIGER', 1, 11, '../images/0/11/10.webp', []],
  ['A very intelligent and friendly sea animal', 'Çok zeki ve dost canlısı bir deniz balığı', 'DOLPHIN', 1, 11, '../images/0/11/11.webp', []],
  ['A large dangerous sea predator', 'Büyük ve tehlikeli bir deniz avcısı', 'SHARK', 1, 11, '../images/0/11/12.webp', []],
  ['The largest ocean mammal', 'Okyanuslardaki en büyük memeli', 'WHALE', 1, 11, '../images/0/11/13.webp', []],
  ['A large reptile with big teeth', 'Büyük dişleri olan bir sürüngen', 'ALLIGATOR', 1, 11, '../images/0/11/15.webp', ['CROCODILE']],
  ['A fast hunting bird', 'Hızlı avlanan bir kuş', 'FALCON', 1, 11, '../images/0/11/16.webp', []],
  ['The fastest land animal', 'Karadaki en hızlı hayvan', 'CHEETAH', 1, 11, '../images/0/11/17.webp', []],
  ['A large reptile found in rivers', 'Nehirlerde yaşayan büyük bir sürüngen', 'CROCODILE', 1, 11, '../images/0/11/18.webp', ['ALLIGATOR']],
  ['An animal that jumps and has a pouch', 'Zıplayan ve kesesi olan bir hayvan', 'KANGAROO', 1, 11, '../images/0/11/19.webp', []],
  ['A small scaly reptile', 'Küçük pullu bir sürüngen', 'LIZARD', 1, 11, '../images/0/11/20.webp', []],
  ['A large animal that loves mud', 'Çamuru seven büyük bir hayvan', 'HIPPO', 1, 11, '../images/0/11/21.webp', ['HIPPOPOTAMUS']],
  ['A very tall bird that cannot fly', 'Uçamayan çok uzun bacak bir kuş', 'OSTRICH', 1, 11, '../images/0/11/22.webp', []],
  ['A large animal with a horn', 'Anlında boynuzu olan büyük bir hayvan', 'RHINO', 1, 11, '../images/0/11/23.webp', ['RHINOCEROS']],
  ['A large furry animal that hibernates', 'Kış uykusuna yatan büyük ve tüylü bir hayvan', 'BEAR', 1, 11, '../images/0/11/25.webp', []],
  ['A clever orange wild animal', 'Zeki turuncu bir vahşi hayvan', 'FOX', 1, 11, '../images/0/11/27.webp', []],
  ['A clever tree-climbing animal', 'Ağaçlara tırmanabilen zeki bir hayvan', 'MONKEY', 1, 11, '../images/0/11/28.webp', []],
  ['A stubborn animal used for carrying', 'Yük taşımak için kullanılan inatçı bir hayvan', 'DONKEY', 1, 11, '../images/0/11/29.webp', []],
  ['An animal with antlers', 'Geyik', 'DEER', 1, 11, '../images/0/11/30.webp', []],
  ['A small fluffy animal with long ears', 'Uzun kulaklı küçük ve tüylü bir hayvan', 'RABBIT', 1, 11, '../images/0/11/31.webp', []],
  ['A desert animal with humps', 'Hörgüçleri olan bir çöl hayvanı', 'CAMEL', 1, 11, '../images/0/11/32.webp', []],
  ['A farm animal that gives milk', 'Süt veren bir çiftlik hayvanı', 'GOAT', 1, 11, '../images/0/11/33.webp', []],
  ['A woolly farm animal', 'Yünlü bir çiftlik hayvanı', 'SHEEP', 1, 11, '../images/0/11/34.webp', []],
  ['A large animal that gives milk', 'Süt veren büyük bir hayvan', 'COW', 1, 11, '../images/0/11/35.webp', []],
  ['An animal people ride', 'İnsanların bindiği bir hayvan', 'HORSE', 1, 11, '../images/0/11/36.webp', []],
  ['A pink farm animal that loves mud', 'Pembe renkli, çamur seven bir hayvanı', 'PIG', 1, 11, '../images/0/11/37.webp', []],
  ['A farm bird that lays eggs', 'Yumurta yapan bir çiftlik kuşu', 'CHICKEN', 1, 11, '../images/0/11/38.webp', []],
  ['A water bird that quacks', 'Vak vaklayan bir su kuşu', 'DUCK', 1, 11, '../images/0/11/39.webp', []],
  ['A flying insect that makes honey', 'Bal yapan uçan bir böcek', 'BEE', 1, 11, '../images/0/11/45.webp', []],
  ['A colourful flying insect', 'Renkli bir uçan böcek', 'BUTTERFLY', 1, 11, '../images/0/11/46.webp', []],
  ['A tiny insect that works in colonies', 'Koloniler halinde yaşayan küçük bir böcek', 'ANT', 1, 11, '../images/0/11/48.webp', []],
  ['An amphibian that jumps and croaks', 'Zıplayan ve vıraklayan bir amfibi', 'FROG', 1, 11, '../images/0/11/49.webp', []],
  ['A white bear from the Arctic', 'Kuzey Kutbu\'ndan beyaz bir ayı', 'POLAR BEAR', 2, 11, '../images/0/11/24.webp', []],
  ['A wild dog-like animal', 'Köpeğe benzeyen vahşi bir hayvan', 'WOLF', 2, 11, '../images/0/11/26.webp', []],
  ['A graceful white water bird', 'Zarif beyaz bir su kuşu', 'SWAN', 2, 11, '../images/0/11/40.webp', []],
  ['A marine animal with flippers', 'Yüzgeçleri olan bir deniz hayvanı', 'SEAL', 2, 11, '../images/0/11/41.webp', []],
  ['A sea creature with eight arms', 'Sekiz kola sahip bir deniz canlısı', 'OCTOPUS', 2, 11, '../images/0/11/42.webp', []],
  ['A sea creature with claws', 'Kıskaçları olan bir deniz canlısı', 'CRAB', 2, 11, '../images/0/11/43.webp', []],
  ['A flying mammal active at night', 'Geceleri aktif olan uçan bir hayvan', 'BAT', 2, 11, '../images/0/11/44.webp', []],
  ['An eight-legged creature', 'Sekiz bacaklı bir canlı', 'SPIDER', 2, 11, '../images/0/11/47.webp', []],
  ['A black and white bird that swims but cannot fly', 'Yüzen fakat uçamayan siyah beyaz bir kuş', 'PENGUIN', 1, 11, '../images/sp/11/1.webp', []],
  ['A tall pink bird that stands on one leg', 'Tek ayak üzerinde duran uzun pembe bir kuş', 'FLAMINGO', 2, 11, '../images/sp/11/2.webp', []],
  ['A small nocturnal animal covered in spines', 'Dikenlerle kaplı küçük gececil bir hayvan', 'HEDGEHOG', 2, 11, '../images/sp/11/3.webp', []],

  // ══════════════════════════════════════════════════════════════════════════
  // CAT 12 — Food & Drinks  (27 + 14 + 10 = 51 → 5 level × 10, son kelime buffer)
  // ══════════════════════════════════════════════════════════════════════════
  // ── Mevcut görseller → ../images/6/2/ ────────────────────────────────────

  ['A ring-shaped bread roll', 'Halka şeklinde bir ekmek türü', 'BAGEL', 1, 12, '../images/6/2/1.webp', []],
  ['A yellow spread made from cream', 'Kremadan yapılan sarı bir sürülebilir yiyecek', 'BUTTER', 1, 12, '../images/6/2/2.webp', []],
  ['Grain flakes eaten for breakfast', 'Kahvaltıda yenilen tahıl gevrekleri', 'CEREAL', 1, 12, '../images/6/2/3.webp', []],
  ['A flaky crescent-shaped pastry', 'Hilal şeklinde kat kat bir hamur işi', 'CROISSANT', 2, 12, '../images/6/2/4.webp', []],
  ['A food laid by a bird', 'Bir kuş tarafından bırakılan yiyecek', 'EGG', 1, 12, '../images/6/2/5.webp', []],
  ['A drink squeezed from fruit', 'Meyvelerin sıkılmasıyla elde edilen bir içecek', 'FRUIT JUICE', 1, 12, '../images/6/2/6.webp', []],
  ['A sweet spread made from fruit', 'Meyvelerden yapılan tatlı bir sürülebilir yiyecek', 'JAM', 1, 12, '../images/6/2/7.webp', []],
  ['Beaten eggs cooked flat in a pan', 'Çırpılmış yumurtaların tavada pişirilmiş hali', 'OMELETTE', 1, 12, '../images/6/2/8.webp', []],
  ['A small sweet cake', 'Küçük tatlı bir kek', 'MUFFIN', 1, 12, '../images/6/2/9.webp', []],
  ['A flat cake cooked on a griddle', 'Düz bir yüzeyde pişirilen ince bir kek', 'PANCAKE', 1, 12, '../images/6/2/10.webp', []],
  ['A long meat product from pork', 'Domuz etinden yapılan uzun bir et ürünü', 'SAUSAGE', 1, 12, '../images/6/2/11.webp', []],
  ['A hot drink made from dried leaves', 'Kurutulmuş yapraklardan yapılan sıcak bir içecek', 'TEA', 1, 12, '../images/6/2/13.webp', []],
  ['A hot drink made from roasted beans', 'Kavrulmuş çekirdeklerden yapılan sıcak bir içecek', 'COFFEE', 1, 12, '../images/6/2/14.webp', []],
  ['A white drink from cows', 'İneklerden elde edilen beyaz bir içecek', 'MILK', 1, 12, '../images/6/2/15.webp', []],
  ['A red vegetable used in salads', 'Salatalarda kullanılan kırmızı bir sebze', 'TOMATO', 1, 12, '../images/6/2/16.webp', []],
  ['A starchy underground vegetable', 'Toprak altında yetişen nişastalı bir sebze', 'POTATO', 1, 12, '../images/6/2/17.webp', []],
  ['A dairy product made from milk', 'Sütten yapılan bir süt ürünü', 'CHEESE', 1, 12, '../images/6/2/18.webp', []],
  ['Cured meat sliced thin', 'İnce dilimlenmiş işlenmiş et ürünü', 'SALAMI', 1, 12, '../images/6/2/19.webp', []],
  ['A long green vegetable', 'Uzun yeşil bir sebze', 'CUCUMBER', 1, 12, '../images/6/2/20.webp', []],
  ['A sweet golden liquid made by bees', 'Arılar tarafından yapılan tatlı altın renkli bir sıvı', 'HONEY', 1, 12, '../images/6/2/21.webp', []],
  ['A baked food made from flour', 'Undan yapılan fırınlanmış bir yiyecek', 'BREAD', 1, 12, '../images/6/2/22.webp', []],
  ['A strong-smelling bulb used in cooking', 'Yemeklerde kullanılan keskin kokulu bir bitki', 'GARLIC', 1, 12, '../images/6/2/23.webp', []],
  ['Small seeds used in soups and stews', 'Çorba ve yemeklerde kullanılan küçük tohumlar', 'BEANS', 1, 12, '../images/6/2/24.webp', []],
  ['A vegetable that makes you cry when you cut it', 'Kesildiğinde ağlatan bir sebze', 'ONION', 1, 12, '../images/6/2/26.webp', []],
  ['Small oval fruits used in Mediterranean food', 'Akdeniz mutfağında kullanılan küçük oval meyveler', 'OLIVES', 1, 12, '../images/6/2/28.webp', []],
  ['White crystals that sweeten food', 'Yiyecekleri tatlandıran beyaz kristaller', 'SUGAR', 1, 12, '../images/6/2/29.webp', []],
  ['A mineral used to season food', 'Yemeklere tat vermek için kullanılan bir mineral', 'SALT', 1, 12, '../images/6/2/30.webp', []],
  ['A grain used for porridge', 'Yulaf lapasında kullanılan bir tahıl', 'OAT', 1, 12, '../images/0/12/35.webp', ['OATS']],
  ['A red or green fruit that grows on trees', 'Ağaçlarda yetişen kırmızı veya yeşil bir meyve', 'APPLE', 1, 12, '../images/0/12/36.webp', []],
  ['A long yellow tropical fruit', 'Uzun sarı tropikal bir meyve', 'BANANA', 1, 12, '../images/0/12/37.webp', []],
  ['A round orange citrus fruit', 'Yuvarlak turuncu bir turunçgil', 'ORANGE', 1, 12, '../images/0/12/38.webp', []],
  ['A small red sweet fruit', 'Küçük kırmızı tatlı bir meyve', 'STRAWBERRY', 1, 12, '../images/0/12/39.webp', []],
  ['An orange root vegetable', 'Turuncu renkli bir kök sebze', 'CARROT', 1, 12, '../images/0/12/40.webp', []],
  ['A yellow grain eaten on a cob', 'Koçan üzerinde yenilen sarı bir tahıl', 'CORN', 1, 12, '../images/0/12/41.webp', ['MAIZE']],
  ['A grain cooked in water', 'Suda pişirilen bir tahıl', 'RICE', 1, 12, '../images/0/12/42.webp', []],
  ['Italian noodles served with sauce', 'Sosla servis edilen İtalyan eriştesi', 'PASTA', 2, 12, '../images/0/12/43.webp', []],
  ['A clear liquid essential for life', 'Yaşam için gerekli berrak bir sıvı', 'WATER', 1, 12, '../images/0/12/44.webp', []],
  ['A sweet baked dessert with layers', 'Katmanlardan oluşan tatlı fırınlanmış bir tatlı', 'CAKE', 1, 12, '../images/0/12/45.webp', []],
  ['A small flat dry sweet snack', 'Küçük, düz ve kuru tatlı bir atıştırmalık', 'BISCUIT', 1, 12, '../images/0/12/46.webp', ['COOKIE']],
  ['A sweet brown food made from cocoa', 'Kakaodan yapılan tatlı kahverengi bir yiyecek', 'CHOCOLATE', 1, 12, '../images/0/12/47.webp', []],
  ['A frozen sweet dessert in a cone', 'Külah içinde servis edilen dondurulmuş tatlı bir tatlı', 'ICE CREAM', 1, 12, '../images/0/12/48.webp', []],
  ['A large green fruit with red flesh', 'İçi kırmızı olan büyük yeşil bir meyve', 'WATERMELON', 1, 12, '../images/sp/12/1.webp', []],
  ['Small round fruit that grows in clusters', 'Salkımlar halinde büyüyen küçük yuvarlak bir meyve', 'GRAPE', 1, 12, '../images/sp/12/2.webp', []],
  ['A small round red stone fruit', 'Küçük yuvarlak kırmızı çekirdekli bir meyve', 'CHERRY', 1, 12, '../images/sp/12/3.webp', []],
  ['A round flat bread topped with cheese and tomato', 'Peynir ve domatesle kaplı yuvarlak yassı bir ekmek', 'PIZZA', 1, 12, '../images/sp/12/4.webp', []],
  ['A bun filled with a meat patty', 'İçinde et köftesi bulunan bir sandviç ekmeği', 'HAMBURGER', 1, 12, '../images/sp/12/5.webp', []],
  ['Bread filled with various ingredients', 'Çeşitli malzemelerle doldurulmuş ekmek', 'SANDWICH', 1, 12, '../images/sp/12/6.webp', []],
  ['A liquid dish made by cooking vegetables or meat', 'Sebze veya et pişirilerek yapılan sıvı bir yemek', 'SOUP', 1, 12, '../images/sp/12/7.webp', []],
  ['A dish of raw vegetables', 'Çiğ sebzelerden oluşan bir yemek', 'SALAD', 1, 12, '../images/sp/12/8.webp', []],
  ['A thick creamy dairy product', 'Koyu kıvamlı ve kremamsı bir süt ürünü', 'YOGHURT', 2, 12, '../images/sp/12/9.webp', ['YOGURT']],
  ['A fungus used in cooking', 'Yemeklerde kullanılan bir mantar türü', 'MUSHROOM', 2, 12, '../images/sp/12/10.webp', []],

  // ══════════════════════════════════════════════════════════════════════════
  // CAT 13 — Appearance & Personality  (54 kelime → 6 level × 9)
  // ══════════════════════════════════════════════════════════════════════════
  // ── Mevcut görseller → ../images/7/1/ ─────────────────────────────────────
  // NOT: 7/1/ içinde 15=APPEARANCE ve 16=PERSONALITY var — bizim kelimelerimiz değil, atla.
  //      24=GET ON WELL var — bizim değil, atla. CLEVER 17'de, PLUMP 18'de vb.
  ['Good-looking or pleasing', 'Çekici veya hoş görünen', 'ATTRACTIVE', 1, 13, '../images/7/1/1.webp', []],
  ['Tending to drop or break things', 'Sık sık bir şeyleri düşüren veya kıran', 'CLUMSY', 1, 13, '../images/7/1/2.webp', []],
  ['Relaxed and not easily upset', 'Rahat ve kolay kolay sinirlenmeyen', 'EASYGOING', 1, 13, '../images/7/1/3.webp', []],
  ['Often unable to remember things', 'Sık sık bir şeyleri hatırlayamayan', 'FORGETFUL', 1, 13, '../images/7/1/4.webp', []],
  ['Willing to give freely', 'Vermeye istekli olan', 'GENEROUS', 1, 13, '../images/7/1/5.webp', []],
  ['Always telling the truth', 'Her zaman doğruyu söyleyen', 'HONEST', 1, 13, '../images/7/1/6.webp', []],
  ['Enjoying social interaction', 'Sosyal etkileşimden hoşlanan', 'OUTGOING', 1, 13, '../images/7/1/7.webp', []],
  ['Having more body weight than ideal', 'İdealden daha fazla kiloya sahip olan', 'OVERWEIGHT', 1, 13, '../images/7/1/8.webp', []],
  ['Always arriving on time', 'Her zaman zamanında gelen', 'PUNCTUAL', 2, 13, '../images/7/1/9.webp', []],
  ['Caring only about yourself', 'Sadece kendini düşünen', 'SELFISH', 1, 13, '../images/7/1/10.webp', []],
  ['Thin and well-shaped', 'İnce ve düzgün yapılı', 'SLIM', 1, 13, '../images/7/1/11.webp', []],
  ['Not willing to change', 'Değişmeye istekli olmayan', 'STUBBORN', 1, 13, '../images/7/1/12.webp', []],
  ['Caring about others\' feelings', 'Başkalarının duygularını önemseyen', 'THOUGHTFUL', 1, 13, '../images/7/1/13.webp', []],
  ['Having a strong muscular body', 'Güçlü ve kaslı bir vücuda sahip olan', 'WELL BUILT', 2, 13, '../images/7/1/14.webp', []],
  ['Quick to learn and understand', 'Hızlı öğrenen ve anlayan', 'CLEVER', 2, 13, '../images/7/1/17.webp', []],
  ['Slightly fat in a round way', 'Biraz kilolu ve yuvarlak yapılı', 'PLUMP', 2, 13, '../images/7/1/18.webp', []],
  ['Showing a high level of ability', 'Yüksek düzeyde zekâya sahip olan', 'INTELLIGENT', 1, 13, '../images/7/1/19.webp', []],
  ['Having great height', 'Uzun boya sahip olan', 'TALL', 1, 13, '../images/7/1/20.webp', []],
  ['Behaving in a respectful way', 'Saygılı bir şekilde davranan', 'POLITE', 1, 13, '../images/7/1/21.webp', []],
  ['Liking other people', 'İnsanları seven ve onlarla iyi geçinen', 'FRIENDLY', 1, 13, '../images/7/1/22.webp', []],
  ['Happy and positive', 'Mutlu ve olumlu olan', 'CHEERFUL', 1, 13, '../images/7/1/23.webp', []],
  ['Having fair or golden hair', 'Sarı veya açık renk saçlara sahip olan', 'BLOND', 1, 13, '../images/7/1/25.webp', []],
  ['Having waves or spirals in hair', 'Saçları kıvrımlı veya bukleli olan', 'CURLY', 1, 13, '../images/7/1/26.webp', []],
  ['Can be counted on', 'Güvenilebilen', 'RELIABLE', 2, 13, '../images/7/1/27.webp', []],
  ['Hair hanging flat without curls', 'Saçları kıvrımsız ve düz olan', 'STRAIGHT', 1, 13, '../images/7/1/28.webp', []],
  ['Hair with gentle curves', 'Saçları hafif kıvrımlı olan', 'WAVY', 1, 13, '../images/7/1/29.webp', []],
  ['Having no hair on the head', 'Başında saç olmayan', 'BALD', 2, 13, '../images/7/1/30.webp', []],
  ['Short and thick in body shape', 'Kısa ve tıknaz bir vücut yapısına sahip olan', 'STUMPY', 3, 13, '../images/7/1/31.webp', []],
  ['Reluctant to spend or give', 'Harcamaya veya vermeye isteksiz olan', 'STINGY', 3, 13, '../images/7/1/32.webp', []],
  ['Hair grown on the upper lip', 'Üst dudakta çıkan yüz kılları', 'MOUSTACHE', 2, 13, '../images/7/1/33.webp', []],
  ['Enjoying the company of others', 'Başkalarının arkadaşlığından hoşlanan', 'SOCIABLE', 2, 13, '../images/7/1/34.webp', []],
  ['Willing to try new or risky things', 'Yeni veya riskli şeyler denemeye istekli olan', 'ADVENTUROUS', 2, 13, '../images/7/1/35.webp', []],
  ['Having a natural skill or ability', 'Doğal bir yeteneğe sahip olan', 'TALENTED', 2, 13, '../images/7/1/36.webp', []],
  ['Facial hair grown on the chin', 'Çenede çıkan yüz kılları', 'BEARD', 2, 13, '../images/7/1/37.webp', []],
  ['Very attractive to look at', 'Bakması çok güzel olan', 'BEAUTIFUL', 1, 13, '../images/7/1/38.webp', []],
  ['Wearing spectacles', 'Gözlük takan', 'GLASSES', 1, 13, '../images/7/1/39.webp', []],
  ['Good-looking (usually a man)', 'Yakışıklı görünen (genellikle erkek)', 'HANDSOME', 1, 13, '../images/7/1/40.webp', []],
  ['Between young and old in age', 'Yaş olarak genç ile yaşlı arasında olan', 'MIDDLE AGED', 2, 13, '../images/7/1/41.webp', []],
  ['Not attractive in appearance', 'Görünüş olarak çekici olmayan', 'UGLY', 2, 13, '../images/7/1/42.webp', []],
  ['Fashionable and impressive', 'Havalı ve etkileyici görünen', 'COOL', 1, 13, '../images/8/1/3.webp', []],
  ['Behaving as if better than others', 'Kendisini başkalarından üstün gören', 'ARROGANT', 3, 13, '../images/8/1/25.webp', []],
  ['Concerned about others\' feelings', 'Başkalarının duygularını önemseyen', 'CARING', 2, 13, '../images/8/1/26.webp', []],
  ['Unhappy about others\' advantages', 'Başkalarının sahip olduklarını kıskanan', 'JEALOUS', 2, 13, '../images/8/1/37.webp', []],
  ['Very relaxed and easy-going', 'Çok rahat ve kolay geçinen', 'LAID BACK', 3, 13, '../images/8/1/10.webp', []],
  ['Unkind or unpleasant', 'Kaba veya hoş olmayan', 'MEAN', 2, 13, '../images/8/1/38.webp', []],
  ['Calm and free from tension', 'Sakin ve gerginlikten uzak', 'RELAXED', 2, 13, '../images/8/1/10.webp', []],
  ['Acting in a secret or dishonest way', 'Gizli veya dürüst olmayan şekilde davranan', 'SNEAKY', 3, 13, '../images/8/1/44.webp', []],
  ['Cannot be depended on', 'Güvenilemeyen', 'UNRELIABLE', 3, 13, '../images/8/1/56.webp', []],
  ['Having a strong will to succeed', 'Başarmak için güçlü bir isteğe sahip olan', 'DETERMINED', 3, 13, '../images/8/1/49.webp', []],
  ['Funny and entertaining', 'Komik ve eğlendirici', 'AMUSING', 3, 13, '../images/8/1/23.webp', []],
  ['Stylish and trendy', 'Şık ve modaya uygun', 'FASHIONABLE', 3, 13, '../images/8/2/3.webp', []],
  ['A person who is very studious', 'Ders çalışmayı çok seven bir kişi', 'NERD', 3, 13, '../images/8/2/14.webp', []],
  ['A person who thinks they are superior', 'Kendisini üstün gören bir kişi', 'SNOB', 3, 13, '../images/8/2/10.webp', []],
  ['Treating everything as important', 'Her şeyi önemli gören', 'SERIOUS', 2, 13, '../images/8/2/9.webp', []],

  // ══════════════════════════════════════════════════════════════════════════
  // CAT 14 — Sports & Equipment  (30 mevcut + 20 eklenecek = 50 → 5 level × 10)
  // ══════════════════════════════════════════════════════════════════════════

  ['Travelling on a boat using wind', 'Rüzgâr gücüyle bir teknede seyahat etme', 'SAILING', 2, 14, '../images/6/7/1.webp', []],
  ['Sliding down snow on boards', 'Kayaklarla kar üzerinde kayma', 'SKIING', 1, 14, '../images/6/7/2.webp', []],
  ['Sleeping outdoors in a tent', 'Bir çadırda açık havada uyuma', 'CAMPING', 1, 14, '../images/6/7/4.webp', []],
  ['Going down a river in a raft', 'Bir sal ile nehirden aşağı gitme', 'RAFTING', 2, 14, '../images/6/7/5.webp', []],
  ['Diving under water with a tank', 'Tüple suyun altında dalış yapma', 'SCUBA DIVING', 2, 14, '../images/6/7/7.webp', []],
  ['Gliding through the air with a parachute', 'Bir paraşütle havada süzülme', 'PARAGLIDING', 3, 14, '../images/6/7/8.webp', []],
  ['Walking long distances in nature', 'Doğada uzun mesafeler yürüme', 'HIKING', 1, 14, '../images/6/7/9.webp', []],
  ['The feathered object hit in badminton', 'Badmintonda vurulan tüylü nesne', 'SHUTTLECOCK', 2, 14, '../images/7/2/11.webp', []],
  ['Protective glasses for swimming', 'Yüzmede kullanılan koruyucu gözlük', 'GOGGLES', 1, 14, '../images/7/2/16.webp', []],
  ['Shooting arrows at a target', 'Hedefe ok atma sporu', 'ARCHERY', 2, 14, '../images/7/2/17.webp', []],
  ['Hand protectors used in boxing', 'Boksta kullanılan el koruyucuları', 'GLOVES', 1, 14, '../images/7/2/18.webp', []],
  ['A circular ring used in gymnastics', 'Jimnastikte kullanılan dairesel halka', 'HOOP', 2, 14, '../images/7/2/20.webp', []],
  ['A combat sport where you grapple', 'Rakiple tutuşarak yapılan bir dövüş sporu', 'WRESTLING', 2, 14, '../images/7/2/21.webp', []],
  ['Head protection used in cycling', 'Bisiklette kullanılan baş koruması', 'HELMET', 1, 14, '../images/7/2/24.webp', []],
  ['Running at a slow steady pace', 'Yavaş ve düzenli tempoda koşma', 'JOGGING', 1, 14, '../images/7/2/30.webp', []],
  ['Moving on ice with blades', 'Bıçaklı patenlerle buz üzerinde hareket etme', 'SKATING', 1, 14, '../images/7/2/31.webp', ['ICE SKATING']],
  ['Moving on wheels with boots', 'Tekerlekli patenlerle hareket etme', 'ROLLERBLADING', 2, 14, '../images/7/2/32.webp', []],
  ['The seat on a horse or bicycle', 'At veya bisiklet üzerindeki oturma bölümü', 'SADDLE', 2, 14, '../images/7/2/35.webp', []],
  ['Jumping off a bridge with elastic', 'Esnek bir halatla köprüden atlama', 'BUNGEE JUMPING', 3, 14, '../images/8/6/1.webp', []],
  ['Playing hockey under water', 'Suyun altında hokey oynama', 'UNDERWATER HOCKEY', 3, 14, '../images/8/6/3.webp', []],
  ['Paddling a small boat with one oar', 'Tek kürekle küçük bir tekneyi kullanma', 'CANOEING', 3, 14, '../images/8/6/4.webp', []],
  ['Jumping from a plane and free-falling', 'Bir uçaktan atlayıp serbest düşüş yapma', 'SKY DIVING', 3, 14, '../images/8/6/5.webp', []],
  ['Hiking on long mountain trails', 'Uzun dağ patikalarında yürüyüş yapma', 'TREKKING', 3, 14, '../images/8/6/10.webp', []],
  ['Exploring underground caves', 'Yer altındaki mağaraları keşfetme', 'CAVING', 3, 14, '../images/8/6/12.webp', []],
  ['Skiing taken to a mountain by helicopter', 'Bir dağa helikopterle çıkarılıp kayak yapma', 'HELI SKIING', 3, 14, '../images/8/6/13.webp', []],
  ['Gliding with a fabric wing like a kite', 'Uçurtmaya benzer kumaş bir kanatla süzülme', 'HANG GLIDING', 3, 14, '../images/8/6/15.webp', []],
  ['Paddling an enclosed small boat', 'Kapalı yapılı küçük bir tekneyi kürekle kullanma', 'KAYAKING', 3, 14, '../images/8/6/17.webp', []],
  ['Driving very fast cars in races', 'Yarışlarda çok hızlı arabalar kullanma', 'MOTOR RACING', 3, 14, '../images/8/6/7.webp', []],
  ['Climbing up the face of a rock', 'Bir kayanın yüzeyine tırmanma', 'ROCK CLIMBING', 3, 14, '../images/8/6/20.webp', []],
  ['Riding and doing tricks on a board with wheels', 'Tekerlekli bir tahta üzerinde sürüş yapıp hareketler sergileme', 'SKATEBOARDING', 2, 14, '../images/8/6/21.webp', []],
  ['A team sport played with a round ball and two goals', 'Yuvarlak bir top ve iki kale ile oynanan takım sporu', 'FOOTBALL', 1, 14, '../images/sp/14/1.webp', ['SOCCER']],
  ['A team sport where you score by putting a ball through a hoop', 'Topu çembere atarak sayı kazanılan bir takım sporu', 'BASKETBALL', 1, 14, '../images/sp/14/2.webp', []],
  ['A sport where you hit a ball over a net with a racket', 'Raketle topu ağın üzerinden vurduğunuz bir spor', 'TENNIS', 1, 14, '../images/sp/14/3.webp', []],
  ['A team sport where you hit a ball over a high net', 'Topun yüksek bir ağın üzerinden vurulduğu takım sporu', 'VOLLEYBALL', 1, 14, '../images/sp/14/4.webp', []],
  ['Moving through water using your arms and legs', 'Kollarınızı ve bacaklarınızı kullanarak suda hareket etme', 'SWIMMING', 1, 14, '../images/sp/14/5.webp', []],
  ['Moving fast on foot in a race', 'Bir yarışta ayakla hızlı hareket etme', 'RUNNING', 1, 14, '../images/sp/14/6.webp', ['JOGGING']],
  ['Riding a two-wheeled vehicle', 'İki tekerlekli bir araç sürme', 'CYCLING', 1, 14, '../images/sp/14/7.webp', []],
  ['A combat sport where you punch your opponent', 'Rakibinize yumruk attığınız bir dövüş sporu', 'BOXING', 2, 14, '../images/sp/14/8.webp', []],
  ['A sport with acrobatic moves on a mat or beam', 'Minder veya denge aleti üzerinde akrobatik hareketler yapılan bir spor', 'GYMNASTICS', 2, 14, '../images/sp/14/9.webp', []],
  ['Tennis played on a small table with a small bat', 'Küçük bir masada ve küçük bir raketle oynanan tenis', 'TABLE TENNIS', 1, 14, '../images/sp/14/10.webp', ['PING PONG']],
  ['A racket sport where you hit a shuttlecock', 'Bir raketle ve tüylü topla oynanan spor', 'BADMINTON', 1, 14, '../images/sp/14/11.webp', []],
  ['A sport where you hit a small ball into holes', 'Küçük bir topun deliklere atılmaya çalışıldığı spor', 'GOLF', 2, 14, '../images/sp/14/12.webp', []],
  ['A sport where you lift heavy weights', 'Ağırlıkların kaldırıldığı bir spor', 'WEIGHTLIFTING', 2, 14, '../images/sp/14/13.webp', []],
  ['A Japanese martial art using throws', 'Fırlatma teknikleri kullanılan Japon dövüş sanatı', 'JUDO', 2, 14, '../images/sp/14/14.webp', []],
  ['A Japanese martial art using kicks and punches', 'Tekme ve yumrukların kullanıldığı Japon dövüş sanatı', 'KARATE', 1, 14, '../images/sp/14/15.webp', []],
  ['Riding waves on a board in the sea', 'Denizde bir tahta üzerinde dalgalar üzerinde kayma', 'SURFING', 2, 14, '../images/sp/14/16.webp', []],
  ['A sword-fighting sport', 'Kılıçlarla yapılan bir spor', 'FENCING', 3, 14, '../images/sp/14/17.webp', []],
  ['Throwing small pointed arrows at a circular target', 'Küçük sivri okları dairesel bir hedefe atma', 'DARTS', 2, 14, '../images/sp/14/18.webp', []],
  ['A sport played on ice or grass with a stick and puck', 'Bir sopa ve disk ile buzda veya çimde oynanan spor', 'HOCKEY', 2, 14, '../images/sp/14/19.webp', ['ICE HOCKEY']],
  ['A sport where you roll a heavy ball to knock down pins', 'Ağır bir topu yuvarlayarak lobutları devirmeye çalışılan spor', 'BOWLING', 1, 14, '../images/sp/14/20.webp', []],

  // ══════════════════════════════════════════════════════════════════════════
  // CAT 15 — Places in Town  (44 mevcut + 6 eklenecek = 50 → 5 level × 10)
  // ══════════════════════════════════════════════════════════════════════════
  // ── Mevcut görseller — path'ler questions.js grade-0 cat-15'ten doğrulandı ─
  ['The central business area of a city', 'Bir şehrin ticaret ve iş merkezinin bulunduğu bölge', 'DOWNTOWN', 1, 15, '../images/6/3/2.webp', []],
  ['A very tall building', 'Çok yüksek bir bina', 'SKYSCRAPER', 1, 15, '../images/6/3/8.webp', []],
  ['A road in a town with houses', 'Kasaba veya şehirde evlerin bulunduğu yol', 'STREET', 1, 15, '../images/6/1/9.webp', []],
  ['A place where crops and animals are raised', 'Tarım ürünlerinin yetiştirildiği ve hayvanların beslendiği yer', 'FARM', 1, 15, '../images/6/3/14.webp', []],
  ['An apartment in a building', 'Bir binadaki daire', 'FLAT', 3, 15, '../images/6/3/15.webp', []],
  ['An open public area in a town', 'Bir şehirdeki açık kamusal alan', 'SQUARE', 3, 15, '../images/6/3/23.webp', []],
  ['An outdoor area with swings for children', 'Çocuklar için salıncakların bulunduğu açık alan', 'PLAYGROUND', 1, 15, '../images/6/3/25.webp', []],
  ['A small stall selling newspapers', 'Gazete satılan küçük bir satış noktası', 'KIOSK', 1, 15, '../images/6/3/5.webp', []],
  ['The building for local government', 'Yerel yönetimin bulunduğu bina', 'CITY HALL', 2, 15, '../images/7/8/1.webp', []],
  ['Where firefighters work', 'İtfaiyecilerin çalıştığı yer', 'FIRE STATION', 1, 15, '../images/7/8/2.webp', []],
  ['A shop selling fresh vegetables and fruit', 'Taze sebze ve meyve satan dükkân', 'GREENGROCER', 1, 15, '../images/7/8/3.webp', []],
  ['A shop selling children\'s toys', 'Çocuk oyuncakları satan dükkân', 'TOY SHOP', 1, 15, '../images/7/8/4.webp', []],
  ['A regional government building', 'Bölgesel yönetim binası', 'GOVERNORSHIP', 2, 15, '../images/7/8/5.webp', []],
  ['A place where films are shown', 'Filmlerin gösterildiği yer', 'MOVIE THEATER', 1, 15, '../images/7/8/6.webp', ['CINEMA']],
  ['A shop selling footwear', 'Ayakkabı satan dükkân', 'SHOE SHOP', 2, 15, '../images/7/8/7.webp', []],
  ['A large building with many shops', 'Birçok dükkânın bulunduğu büyük bina', 'SHOPPING MALL', 1, 15, '../images/7/8/9.webp', []],
  ['Where planes take off and land', 'Uçakların kalkıp indiği yer', 'AIRPORT', 2, 15, '../images/7/8/10.webp', []],
  ['Where the police work', 'Polislerin çalıştığı yer', 'POLICE STATION', 1, 15, '../images/7/8/11.webp', []],
  ['A place with rides and fun activities', 'Eğlence araçları ve aktivitelerin bulunduğu yer', 'AMUSEMENT PARK', 1, 15, '../images/7/8/14.webp', ['FUN FAIR']],
  ['A building where sick people are treated', 'Hasta insanların tedavi edildiği bina', 'HOSPITAL', 1, 15, '../images/7/8/15.webp', []],
  ['A shop selling newspapers and magazines', 'Gazete ve dergi satan dükkân', 'NEWSAGENT', 1, 15, '../images/7/8/16.webp', []],
  ['A building displaying paintings and sculptures', 'Resim ve heykellerin sergilendiği bina', 'ART GALLERY', 1, 15, '../images/7/8/17.webp', ['MUSEUM']],
  ['A place where you borrow books', 'Kitap ödünç alınan yer', 'LIBRARY', 1, 15, '../images/7/8/18.webp', []],
  ['A shop that sells books', 'Kitap satan dükkân', 'BOOKSHOP', 1, 15, '../images/7/8/19.webp', ['BOOK STORE']],
  ['A shop where bread is made and sold', 'Ekmeğin yapıldığı ve satıldığı yer', 'BAKERY', 1, 15, '../images/7/8/20.webp', []],
  ['A place with wild animals for public viewing', 'Vahşi hayvanların sergilendiği yer', 'ZOO', 1, 15, '../images/7/8/21.webp', []],
  ['A shop where medicines are sold', 'İlaçların satıldığı dükkân', 'PHARMACY', 1, 15, '../images/7/8/23.webp', ['CHEMIST']],
  ['A shop selling flowers', 'Çiçek satan dükkân', 'FLORIST', 1, 15, '../images/7/8/24.webp', []],
  ['A shop selling food and household items', 'Gıda ve ev ihtiyaçları satan dükkân', 'GROCER', 1, 15, '../images/7/8/25.webp', []],
  ['A doctor for teeth', 'Dişlerle ilgilenen doktor', 'DENTIST', 1, 15, '../images/7/8/26.webp', []],
  ['A shop that sells meat', 'Et satan dükkân', 'BUTCHER', 1, 15, '../images/7/8/27.webp', []],
  ['A vertical structure enclosing an area', 'Bir alanı çevreleyen dikey yapı', 'WALL', 3, 15, '../images/8/7/1.webp', []],
  ['A building for religious worship', 'İbadet amacıyla kullanılan bina', 'TEMPLE', 3, 15, '../images/8/7/2.webp', []],
  ['A structure built to remember an event', 'Bir olayı hatırlatmak için yapılan yapı', 'MONUMENT', 3, 15, '../images/8/7/4.webp', []],
  ['A place where a dead person is buried', 'Ölü bir kişinin gömüldüğü yer', 'TOMB', 3, 15, '../images/8/7/5.webp', []],
  ['A tall narrow structure', 'Uzun ve dar bir yapı', 'TOWER', 3, 15, '../images/8/7/8.webp', []],
  ['A large grand residence for royalty', 'Kraliyet ailesi için yapılmış büyük ve gösterişli konut', 'PALACE', 3, 15, '../images/8/7/10.webp', []],
  ['A structure that sprays water', 'Su püskürten bir yapı', 'FOUNTAIN', 3, 15, '../images/8/7/11.webp', []],
  ['A figure made from stone or metal', 'Taş veya metalden yapılmış bir figür', 'STATUE', 3, 15, '../images/8/7/13.webp', []],
  ['A Muslim place of worship', 'Müslümanların ibadet ettiği yer', 'MOSQUE', 3, 15, '../images/8/7/15.webp', []],
  ['A large fortified building from history', 'Tarihten kalma büyük ve korunaklı yapı', 'CASTLE', 3, 15, '../images/8/7/16.webp', []],
  ['A place where people are buried', 'İnsanların gömüldüğü yer', 'CEMETERY', 3, 15, '../images/8/7/18.webp', []],
  ['A structure built over a river or gap', 'Bir nehir veya boşluğun üzerine yapılan yapı', 'BRIDGE', 3, 15, '../images/8/7/19.webp', []],
  ['A Christian place of worship', 'Hristiyanların ibadet ettiği yer', 'CHURCH', 3, 15, '../images/8/7/20.webp', []],
  ['A large arena where sports events are held', 'Spor etkinliklerinin düzenlendiği büyük bir arena', 'STADIUM', 1, 15, '../images/sp/15/1.webp', []],
  ['A building where children go to learn', 'Çocukların öğrenmek için gittiği bir bina', 'SCHOOL', 1, 15, '../images/sp/15/2.webp', []],
  ['A place where you keep and borrow money', 'Paranızı sakladığınız ve çektiğiniz bir yer', 'BANK', 1, 15, '../images/sp/15/3.webp', []],
  ['A place where passengers wait for a bus', 'Yolcuların otobüs beklediği bir yer', 'BUS STOP', 1, 15, '../images/sp/15/4.webp', []],
  ['A place where you send letters and parcels', 'Mektup ve paket gönderdiğiniz bir yer', 'POST OFFICE', 2, 15, '../images/sp/15/5.webp', []],
  ['A place where you fill your car with fuel', 'Aracınıza yakıt doldurduğunuz bir yer', 'PETROL STATION', 2, 15, '../images/sp/15/6.webp', ['GAS STATION']],

  // ══════════════════════════════════════════════════════════════════════════
  // CAT 16 — Occupations  (28 mevcut + 22 eklenecek = 50 → 5 level × 10)
  // ══════════════════════════════════════════════════════════════════════════
  // ── Mevcut görseller — path'ler questions.js grade-0 cat-16'dan doğrulandı ─
  ['A person who designs buildings', 'Binalar tasarlayan bir kişi', 'ARCHITECT', 1, 16, '../images/6/6/1.webp', []],
  ['A person who manages office correspondence', 'Ofis yazışmalarını yöneten bir kişi', 'SECRETARY', 1, 16, '../images/6/6/2.webp', []],
  ['A person who makes and sells bread', 'Ekmek yapan ve satan bir kişi', 'BAKER', 1, 16, '../images/6/6/3.webp', []],
  ['A person who prepares food in a kitchen', 'Mutfakta yemek hazırlayan bir kişi', 'COOK', 1, 16, '../images/6/6/4.webp', ['CHEF']],
  ['A person in charge of a company', 'Bir şirketten sorumlu olan kişi', 'MANAGER', 1, 16, '../images/6/6/5.webp', ['DIRECTOR']],
  ['A person who does scientific research', 'Bilimsel araştırmalar yapan bir kişi', 'SCIENTIST', 2, 16, '../images/6/6/6.webp', []],
  ['A doctor who treats teeth', 'Dişleri tedavi eden bir doktor', 'DENTIST', 1, 16, '../images/6/6/7.webp', []],
  ['A person who repairs engines and machines', 'Motorları ve makineleri tamir eden bir kişi', 'MECHANIC', 1, 16, '../images/6/6/8.webp', []],
  ['A person who stays home to care for family', 'Ailesine bakmak için evde kalan bir kişi', 'HOUSEWIFE', 1, 16, '../images/6/6/9.webp', []],
  ['A person who drives a vehicle', 'Bir araç kullanan kişi', 'DRIVER', 1, 16, '../images/6/6/10.webp', []],
  ['A woman who sells things in a shop', 'Bir mağazada ürün satan kadın', 'SALESWOMAN', 1, 16, '../images/6/6/11.webp', []],
  ['A person who no longer works', 'Artık çalışmayan bir kişi', 'RETIRED', 1, 16, '../images/6/6/12.webp', []],
  ['A person who designs machines or structures', 'Makineler veya yapılar tasarlayan bir kişi', 'ENGINEER', 1, 16, '../images/6/6/13.webp', []],
  ['A woman who serves food in a restaurant', 'Bir restoranda yemek servisi yapan kadın', 'WAITRESS', 1, 16, '../images/6/6/14.webp', []],
  ['A person who puts out fires', 'Yangınları söndüren bir kişi', 'FIREFIGHTER', 1, 16, '../images/6/6/15.webp', []],
  ['A person who grows crops and raises animals', 'Tarım ürünleri yetiştiren ve hayvan bakan bir kişi', 'FARMER', 1, 16, '../images/6/6/16.webp', []],
  ['A person who does physical or manual labour', 'Bedensel veya el işi yapan bir kişi', 'WORKER', 1, 16, '../images/6/6/17.webp', []],
  ['A person who sells meat', 'Et satan bir kişi', 'BUTCHER', 1, 16, '../images/6/6/18.webp', []],
  ['A person who cuts and styles hair', 'Saç kesen ve şekillendiren bir kişi', 'HAIRDRESSER', 1, 16, '../images/6/6/19.webp', []],
  ['A woman who performs in films or theatre', 'Film veya tiyatroda rol alan bir kadın', 'ACTRESS', 1, 16, '../images/6/6/20.webp', []],
  ['A person who represents clients in court', 'Mahkemede müvekkillerini temsil eden bir kişi', 'LAWYER', 1, 16, '../images/6/6/22.webp', []],
  ['A person who performs music with their voice', 'Sesiyle müzik yapan bir kişi', 'SINGER', 1, 16, '../images/6/6/23.webp', ['MUSICIAN']],
  ['A person who cares for patients in hospital', 'Hastanedeki hastalarla ilgilenen bir kişi', 'NURSE', 1, 16, '../images/6/6/24.webp', []],
  ['A doctor who treats animals', 'Hayvanları tedavi eden bir doktor', 'VET', 1, 16, '../images/6/6/25.webp', []],
  ['A person who educates students', 'Öğrencileri eğiten bir kişi', 'TEACHER', 1, 16, '../images/6/6/27.webp', []],
  ['A person who treats illness', 'Hastalıkları tedavi eden bir kişi', 'DOCTOR', 1, 16, '../images/6/6/28.webp', []],
  ['A person who runs a business', 'Bir işletmeyi yöneten kişi', 'BUSINESSMAN', 2, 16, '../images/6/6/29.webp', []],
  ['A person who designs machines or structures', 'Makineler veya yapılar tasarlayan bir kişi', 'ENGINEER', 2, 16, '../images/7/7/27.webp', []],
  ['A person who flies an aircraft', 'Uçak kullanan bir kişi', 'PILOT', 1, 16, '../images/sp/16/1.webp', []],
  ['A person who enforces the law', 'Suçluları yakalayan kişi', 'POLICEMAN', 1, 16, '../images/sp/16/2.webp', ['POLICE OFFICER']],
  ['A person who makes decisions in a court of law', 'Mahkemede karar veren kişi', 'JUDGE', 2, 16, '../images/sp/16/3.webp', []],
  ['A person who writes news for a newspaper', 'Gazete için haber yazan kişi', 'JOURNALIST', 2, 16, '../images/sp/16/4.webp', ['REPORTER']],
  ['A person who takes pictures professionally', 'Fotoğrafçı', 'PHOTOGRAPHER', 2, 16, '../images/sp/16/5.webp', []],
  ['A person who works at a till in a shop', 'Bir mağazada kasada çalışan bir kişi', 'CASHIER', 1, 16, '../images/sp/16/6.webp', []],
  ['A person who works on a ship', 'Bir gemide çalışan bir kişi', 'SAILOR', 2, 16, '../images/sp/16/7.webp', []],
  ['A person who serves in the military', 'Orduda görev yapan bir kişi', 'SOLDIER', 1, 16, '../images/sp/16/8.webp', []],
  ['A person who looks after a garden', 'Bir bahçeyle ilgilenen bir kişi', 'GARDENER', 1, 16, '../images/sp/16/9.webp', []],
  ['A person who paints pictures or walls', 'Resim yapan kişi', 'PAINTER', 1, 16, '../images/sp/16/10.webp', []],
  ['A person who fixes water pipes', 'Su borularını tamir eden bir kişi', 'PLUMBER', 2, 16, '../images/sp/16/11.webp', []],
  ['A person who installs and repairs electrical systems', 'Elektrik sistemlerini kuran ve tamir eden bir kişi', 'ELECTRICIAN', 2, 16, '../images/sp/16/12.webp', []],
  ['A person who travels to space', 'Uzaya seyahat eden bir kişi', 'ASTRONAUT', 2, 16, '../images/sp/16/13.webp', []],
  ['A man who serves food in a restaurant', 'Bir restoranda yemek servisi yapan bir erkek', 'WAITER', 1, 16, '../images/sp/16/14.webp', []],
  ['A person who delivers letters', 'Mektup dağıtan bir kişi', 'POSTMAN', 1, 16, '../images/sp/16/15.webp', ['MAILMAN']],
  ['A person who makes and repairs clothes', 'Kıyafet diken ve tamir eden bir kişi', 'TAILOR', 2, 16, '../images/sp/16/16.webp', []],
  ['A man who performs in films or theatre', 'Film veya tiyatroda rol alan bir erkek', 'ACTOR', 1, 16, '../images/sp/16/17.webp', []],
  ['A person who plays a musical instrument', 'Bir müzik aleti çalan bir kişi', 'MUSICIAN', 2, 16, '../images/sp/16/18.webp', ['SINGER']],
  ['A person who manages financial records', 'Mali kayıtları yöneten bir kişi', 'ACCOUNTANT', 3, 16, '../images/sp/16/19.webp', []],
  ['A person who investigates crimes', 'Suçları araştıran bir kişi', 'DETECTIVE', 2, 16, '../images/sp/16/20.webp', []],
  ['A person who works in a library', 'Bir kütüphanede çalışan bir kişi', 'LIBRARIAN', 2, 16, '../images/sp/16/21.webp', []],
  ['A person who prepares and sells medicines', 'İlaç hazırlayan ve satan bir kişi', 'PHARMACIST', 2, 16, '../images/sp/16/22.webp', []],

];

// window'a bağla — sp_campaigns.js ve SP sistem buna erişir
window.SP_WORDS          = SP_WORDS;
window.SP_CATEGORY_NAMES = SP_CATEGORY_NAMES;
window.SP_CATEGORY_THUMBS = SP_CATEGORY_THUMBS;
