export const DEFAULT_CONFIG = {
    usePlaceholderAssets: false,
    designWidth: 1920,
    designHeight: 1080,
    speed: {
        current: 360,
        target: 360,
        acceleration: 900
    },
    audio: {
        forest: {
            src: "./assets/sounds/forest.mp3",
            volume: 0.45,
            loop: true
        }
    },
    environment: {
        sharedWidth: 1920,
        sharedHeight: 1280,
        sharedY: -200,
        baseScale: 1,
        horizonY: 445,
        groundLineY: 890
    },
    overlays: {
        viewportBoundary: false,
        horizonGuide: false,
        groundContactLine: false,
        hannahAnchorPoint: false,
        hannahSpriteBounds: false,
        environmentCanvasBounds: false,
        segmentSeams: false
    },
    layers: [
        {
            id: "distant_sky_layer",
            label: "Sky",
            src: "./assets/backgrounds/distant_sky_layer.png",
            placeholder: "sky",
            sourceWidth: 1774,
            sourceHeight: 887,
            renderWidth: 1920,
            renderHeight: 1080,
            x: 0,
            y: 0,
            xOffset: 0,
            yOffset: 0,
            scale: 1,
            speedMultiplier: 0,
            zIndex: 0,
            opacity: 1,
            enabled: true,
            scroll: false
        },
        {
            id: "distant_clouds_layer",
            label: "Clouds",
            src: "./assets/backgrounds/distant_clouds_seamless_layer.png",
            placeholder: "clouds",
            sourceWidth: 1536,
            sourceHeight: 1024,
            renderWidth: 1920,
            renderHeight: 1280,
            x: 0,
            y: -200,
            xOffset: 0,
            yOffset: 0,
            scale: 1,
            speedMultiplier: 0.04,
            zIndex: 10,
            opacity: 1,
            enabled: true,
            scroll: true,
            alternateFlip: false
        },
        {
            id: "distant_mountain_layer",
            label: "Mountains",
            src: "./assets/backgrounds/distant_mountain_layer.png",
            placeholder: "mountains",
            sourceWidth: 1536,
            sourceHeight: 1024,
            renderWidth: 1920,
            renderHeight: 1280,
            x: 0,
            y: -200,
            xOffset: 0,
            yOffset: 0,
            scale: 1,
            speedMultiplier: 0.1,
            zIndex: 20,
            opacity: 1,
            enabled: false,
            scroll: true
        },
        {
            id: "composite_distant_landscape_layer",
            label: "Distant landscape composite",
            src: "./assets/backgrounds/composite_distant_landscape_seamless_layer.png",
            placeholder: "mountains",
            sourceWidth: 1536,
            sourceHeight: 1024,
            renderWidth: 1920,
            renderHeight: 1280,
            x: 0,
            y: -200,
            xOffset: 0,
            yOffset: 0,
            scale: 1,
            speedMultiplier: 0.16,
            zIndex: 25,
            opacity: 1,
            enabled: true,
            scroll: true,
            alternateFlip: false
        },
        {
            id: "far_forest_layer",
            label: "Far forest",
            src: "./assets/backgrounds/far_forest_layer.png",
            placeholder: "farForest",
            sourceWidth: 1536,
            sourceHeight: 1024,
            renderWidth: 1920,
            renderHeight: 1280,
            x: 0,
            y: -200,
            xOffset: 0,
            yOffset: 0,
            scale: 1,
            speedMultiplier: 0.18,
            zIndex: 30,
            opacity: 1,
            enabled: false,
            scroll: true
        },
        {
            id: "midground_trees_layer",
            label: "Midground trees",
            src: "./assets/backgrounds/midground_trees_layer.png",
            placeholder: "midgroundTrees",
            sourceWidth: 1536,
            sourceHeight: 1024,
            renderWidth: 1920,
            renderHeight: 1280,
            x: 0,
            y: -200,
            xOffset: 0,
            yOffset: 0,
            scale: 1,
            speedMultiplier: 0.38,
            zIndex: 40,
            opacity: 1,
            enabled: false,
            scroll: true
        },
        {
            id: "near_bushes_layer",
            label: "Near bushes",
            src: "./assets/backgrounds/near_bushes_and_grass_layer.png",
            expectedSrc: "./assets/backgrounds/near_bushes_layer.png",
            placeholder: "nearBushes",
            sourceWidth: 1536,
            sourceHeight: 1024,
            renderWidth: 1920,
            renderHeight: 1280,
            x: 0,
            y: -200,
            xOffset: 0,
            yOffset: 0,
            scale: 1,
            speedMultiplier: 0.68,
            zIndex: 50,
            opacity: 1,
            enabled: false,
            scroll: true
        },
        {
            id: "roadside_details_layer",
            label: "Roadside details",
            src: "./assets/backgrounds/roadside_details_layer.png",
            placeholder: "roadsideDetails",
            sourceWidth: 1536,
            sourceHeight: 1024,
            renderWidth: 1920,
            renderHeight: 1280,
            x: 0,
            y: -200,
            xOffset: 0,
            yOffset: 0,
            scale: 1,
            speedMultiplier: 0.88,
            zIndex: 60,
            opacity: 1,
            enabled: false,
            scroll: true
        },
        {
            id: "composite_mid_roadside_layer",
            label: "Mid roadside composite",
            src: "./assets/backgrounds/composite_mid_roadside_seamless_layer.png",
            placeholder: "nearBushes",
            sourceWidth: 1536,
            sourceHeight: 1024,
            renderWidth: 1920,
            renderHeight: 1280,
            x: 0,
            y: -200,
            xOffset: 0,
            yOffset: 0,
            scale: 1,
            speedMultiplier: 0.72,
            zIndex: 58,
            opacity: 1,
            enabled: true,
            scroll: true,
            alternateFlip: false
        },
        {
            id: "ground_layer",
            label: "Ground",
            src: "./assets/backgrounds/cycling_path_layer.png",
            expectedSrc: "./assets/backgrounds/ground_layer.png",
            placeholder: "ground",
            sourceWidth: 1536,
            sourceHeight: 1024,
            renderWidth: 1920,
            renderHeight: 1280,
            x: 0,
            y: -200,
            xOffset: 0,
            yOffset: 105,
            scale: 1,
            speedMultiplier: 1,
            zIndex: 70,
            opacity: 1,
            enabled: true,
            scroll: true,
            alternateFlip: false
        },
        {
            id: "foreground_vegetation_layer",
            label: "Foreground vegetation",
            src: "./assets/backgrounds/foreground_vegetation_dense_layer.png",
            placeholder: "foreground",
            sourceWidth: 1536,
            sourceHeight: 1024,
            renderWidth: 1920,
            renderHeight: 1280,
            x: 0,
            y: -200,
            xOffset: 0,
            yOffset: 110,
            scale: 1,
            speedMultiplier: 1.28,
            zIndex: 100,
            opacity: 1,
            enabled: true,
            scroll: true,
            alternateFlip: false
        }
    ],
    character: {
        anchorX: 0.3,
        groundY: 0.824,
        wheelContactOffsetX: 138,
        wheelContactOffsetY: 705,
        scale: 0.8,
        visualYOffset: 260,
        jumpHeight: 155,
        jumpHangPower: 0.58,
        bobAmplitude: 0,
        bobFrequency: 0,
        tiltAmplitude: 0,
        zIndex: 90,
        shadow: {
            enabled: false,
            zIndex: 65,
            width: 228,
            height: 42,
            xOffset: 8,
            yOffset: -6,
            opacity: 0.28
        },
        states: {
            ride: {
                src: "./assets/characters/hannah_ride_manual_atlas.png?v=1",
                frameCount: 8,
                columns: 8,
                fps: 11,
                loop: true,
                sourceWidth: 2184,
                sourceHeight: 724,
                frameWidth: 273,
                frameHeight: 724,
                runtimeSourceWidth: 2184,
                frameRects: [
                    { x: 0, y: 0, width: 273, height: 724 },
                    { x: 273, y: 0, width: 273, height: 724 },
                    { x: 546, y: 0, width: 273, height: 724 },
                    { x: 819, y: 0, width: 273, height: 724 },
                    { x: 1092, y: 0, width: 273, height: 724 },
                    { x: 1365, y: 0, width: 273, height: 724 },
                    { x: 1638, y: 0, width: 273, height: 724 },
                    { x: 1911, y: 0, width: 273, height: 724 }
                ],
                chromaKey: {
                    enabled: false,
                    color: [247, 2, 245],
                    tolerance: 72,
                    feather: 24
                }
            },
            jump: {
                src: "./assets/characters/hannah_jump_manual_atlas.png?v=1",
                frameCount: 4,
                columns: 4,
                fps: 8,
                loop: false,
                sourceWidth: 1196,
                sourceHeight: 724,
                frameWidth: 299,
                frameHeight: 724,
                runtimeSourceWidth: 1196
            },
            idleFallback: {
                src: "./assets/characters/hannah1.png",
                frameCount: 1,
                sourceWidth: 1536,
                sourceHeight: 1024
            }
        }
    },
    debug: {
        panelVisible: true,
        warningsVisible: true,
        updateInterval: 0.25
    }
};

export function cloneConfig() {
    return structuredClone(DEFAULT_CONFIG);
}
