(() => {
const { GAME_CONFIG, createRandomItemPicker, getPlayableItems, distributeBalanced, getLockedClassroom, getPresentStudents, getRosterPointAwards, transferRosterPoints, activePlayer, advanceTurn, answerQuestion, applyListeningStreak, canUseJoker, chooseNoSubtitles, consumeJoker, continueRound, createGameState, getEvidenceLine, hasCompleteEvidence, recordVideoPlay, revealSubtitles, setDifficulty, startQuestion, activateAnswerEvidenceHighlight, activateTranscriptEvidenceHighlight, animateScoreAward, celebrateActivePortrait, concealVideo, els, hideEvidenceView, loadQuestion, playEchoSegment, playEvidenceSegment, renderFinal, renderGame, renderJokers, renderRoundScores, renderSetup, resetQuestionView, restoreQuestionOverlays, setDifficultySelection, setTimer, showAnswers, showDecision, showEvidenceView, showFeedback, showScreen, showTranscript, showVideoPlayback, suspendQuestionOverlays, updateWatchCounter, playAnswerSound, showLeaderboard, duckBackgroundMusic, nextBackgroundTrack, previousBackgroundTrack, restoreBackgroundMusic, startBackgroundMusic, toggleBackgroundMusic } = window.LeagueListening;

const $ = (selector) => document.querySelector(selector);
const studentMode = Boolean(window.__oliviasMovieMemoriesStudentMode);
const publishedVideoCount = (window.LEAGUE_OF_LISTENING_ITEMS || []).filter((item) => item?.status === "published").length;
$("#published-video-count").textContent = publishedVideoCount;
let groupCount = studentMode ? 1 : 2;
let groupNames = studentMode ? ["STUDENT", "TEAM 2", "TEAM 3"] : ["TEAM 1", "TEAM 2", "TEAM 3"];
let setupGroups = [[], [], []];
let classroomId = "";
let state = null;
let evidencePlayed = false;
let evidenceAdvancePending = false;
let evidenceSkipRequested = false;
let answerRevealTimer = 0;
const teacherHistoryStorageKey = "oliviasMovieMemoriesTeacherHistoryV1";
const liteModeStorageKey = "oliviasMovieMemoriesLiteModeV1";
const finalAudio = new Audio("assets/sounds/final.mp3");
const characterChoices = ["ava", "benjamin", "chloe", "daniel", "david", "ella", "emma", "ethan", "hannah", "jack", "lucas", "mia", "noah", "olivia", "victoria", "zoe"];

function activeSetupGroups() { return setupGroups.slice(0, groupCount); }
function syncSetup() { renderSetup(activeSetupGroups(), groupNames.slice(0, groupCount)); els.start.disabled = activeSetupGroups().some((group) => !group.length); }
function playableItemsOrWarn() { if (getPlayableItems(window.LEAGUE_OF_LISTENING_ITEMS).length) return true; alert("There are no playable listening items yet. Complete the transcript, options and correct answer in scripts.js."); return false; }
function requestGameFullscreen() { if (!document.fullscreenElement) document.documentElement.requestFullscreen?.().catch(() => {}); }
function setLiteMode(enabled) { document.body.classList.toggle("lite-mode", enabled); $("#lite-mode-button").textContent = enabled ? "LITE ✓" : "LITE"; $("#lite-mode-button").setAttribute("aria-pressed", String(enabled)); localStorage.setItem(liteModeStorageKey, enabled ? "1" : "0"); }

function prepareStudentMode() {
  if (!studentMode) return;
  let profile = {};
  try { profile = JSON.parse(localStorage.getItem("fpStudentProfile") || "{}"); } catch (_) {}
  const avatarName = String(profile.avatar || "").trim();
  const avatarPath = avatarName ? `../word_overlord/avatars/AV_Anime_${avatarName}_head.webp` : "";
  const studentName = String(profile.name || "STUDENT").trim() || "STUDENT";
  groupNames[0] = studentName.toUpperCase();
  setupGroups[0] = [{ name: studentName, avatarPath }];
  document.querySelectorAll("[data-group-count]").forEach((button) => { button.hidden = true; });
  const groupCard = document.querySelector(".setup-card:first-child");
  if (groupCard) groupCard.hidden = true;
  const rosterCard = document.querySelector(".setup-card:nth-child(2)");
  if (rosterCard) rosterCard.hidden = true;
  $("#reset-video-history-button").hidden = true;
  $("#scores-button").hidden = true;
  $("#lite-mode-button").hidden = true;
  const settingsCard = document.querySelector(".settings-card");
  if (settingsCard) {
    settingsCard.querySelector(".eyebrow").textContent = "OLIVIA'S MOVIE MEMORIES";
    settingsCard.querySelector("h2").textContent = "Start watching";
    settingsCard.querySelector(".muted").textContent = "Watch a memory, listen closely, then choose your answer.";
    settingsCard.querySelector('[for="game-mode"]').hidden = true;
    els.gameMode.hidden = true;
  }
}

function openRosterPicker() { const room = getLockedClassroom(); if (!room) { els.rosterStatus.textContent = "Lock a classroom from the Teacher HUD roster first."; return; } const present = getPresentStudents(room).length; if (!present) { els.rosterStatus.textContent = `${room.name || "CLASS"} has no present students today.`; return; } setupGroups = distributeBalanced(room, groupCount).concat([[]]).slice(0, 3); classroomId = room.id; els.rosterStatus.textContent = `${room.name}: ${present} present students balanced across teams.`; syncSetup(); }

function isCharacterBasedMode() { return !studentMode && state?.gameMode === "character"; }
function beginGame() { if (studentMode && !window.OliviaMemoryJourney?.begin?.()) return; if (!playableItemsOrWarn()) return; requestGameFullscreen(); const picker = createRandomItemPicker(window.LEAGUE_OF_LISTENING_ITEMS); state = createGameState({ groups: activeSetupGroups(), groupNames: groupNames.slice(0, groupCount), itemPicker: picker, roundLimit: Infinity }); state.gameMode = studentMode ? "classic" : els.gameMode.value; showScreen("game"); showAnnouncement(); startBackgroundMusic(); }
function showCharacterSelection(statusMessage = "") { const availableCharacters = state.itemPicker.availableCharacterIds?.() || new Set(); const choices = characterChoices.filter((id) => availableCharacters.has(id)); if (!choices.length) { loadCurrentQuestion(startQuestion(state), statusMessage); return; } const player = activePlayer(state).student; els.characterMessage.textContent = statusMessage || `${player.name}, choose a character for this video.`; els.characterGrid.innerHTML = choices.map((id) => `<button class="character-choice" type="button" data-character-id="${id}"><img src="assets/avatars/${id}.webp" alt="${id}"><strong>${id.toUpperCase()}</strong></button>`).join(""); els.characterDialog.hidden = false; }
function showAnnouncement(statusMessage = "") { if (isCharacterBasedMode() && !state.itemPicker.hasPendingPriority?.()) return showCharacterSelection(statusMessage); loadCurrentQuestion(startQuestion(state), statusMessage); }
function loadCurrentQuestion(item, statusMessage = "") { clearTimeout(answerRevealTimer); answerRevealTimer = 0; evidencePlayed = false; evidenceAdvancePending = false; evidenceSkipRequested = false; if (!item) { els.videoStatus.textContent = "No playable videos are available."; els.fallback.hidden = false; els.fallback.querySelector("strong").textContent = "No playable videos are available."; els.playVideo.hidden = true; return; } renderGame(state, activePlayer(state)); els.instruction.textContent = "Listen carefully."; loadQuestion(item); if (studentMode) { setDifficulty(state, "medium"); setDifficultySelection("medium"); els.playVideo.hidden = false; els.playVideo.disabled = false; els.videoStatus.textContent = "Start the first listen."; } updateWatchCounter(0); if (statusMessage) els.videoStatus.textContent = statusMessage; }
function replaceMissingVideo() { const failedId = state?.question?.id; if (!failedId || state.phase !== "video") return; state.itemPicker.remove?.(failedId); showAnnouncement("Video unavailable. Choose another character."); }
function retryVideoFromR2() { const remoteSrc = els.video.dataset.remoteFallbackSrc; if (location.protocol !== "file:" || !remoteSrc || els.video.dataset.remoteFallbackUsed) return false; els.video.dataset.remoteFallbackUsed = "true"; els.video.src = remoteSrc; els.video.load(); els.videoStatus.textContent = "Local video unavailable. Loading from R2…"; return true; }
function closeVideoHistoryResetDialog() { $("#reset-video-history-dialog").hidden = true; }
function resetVideoHistory() { localStorage.removeItem(teacherHistoryStorageKey); location.reload(); }
let segmentFinished = false;
let segmentFrameId = 0;
function parseVideoTime(value) { if (typeof value === "number" && Number.isFinite(value)) return value; const match = String(value ?? "").trim().match(/^(\d+):(\d{2}(?:\.\d{1,3})?)$/); return match ? Number(match[1]) * 60 + Number(match[2]) : null; }
function stopSegmentMonitor() { if (segmentFrameId) cancelAnimationFrame(segmentFrameId); segmentFrameId = 0; }
function getField(object, name) { return Object.entries(object || {}).find(([key]) => key.toLowerCase() === name.toLowerCase())?.[1]; }
function monitorVideoSegment() { stopSegmentMonitor(); const endAt = parseVideoTime(getField(state?.question, "videoEnd")); if (endAt == null) return; const checkEnd = () => { if (els.video.currentTime >= endAt) return finishVideoSegment(); segmentFrameId = requestAnimationFrame(checkEnd); }; segmentFrameId = requestAnimationFrame(checkEnd); }
function finishVideoSegment() { if (segmentFinished || state?.phase !== "video") return; segmentFinished = true; stopSegmentMonitor(); els.video.pause(); restoreBackgroundMusic(); concealVideo(); updateWatchCounter(state.videoPlays); els.answerNow.hidden = true; els.answerNow.disabled = true; els.overrideReplay.disabled = false; showDecision(); renderJokers(state); }
function playVideo(isOverride = false) { if (!state || !state.difficulty || (!isOverride && !recordVideoPlay(state))) return; segmentFinished = false; els.decisionOverlay.hidden = true; els.replay.hidden = true; els.replay.disabled = true; els.answerNow.hidden = false; els.answerNow.disabled = false; els.overrideReplay.disabled = true; updateWatchCounter(state.videoPlays); els.replay.disabled = true; showVideoPlayback(); els.fallback.hidden = true; els.playVideo.hidden = true; const startAt = parseVideoTime(getField(state.question, "videoStart")) ?? 0; const slowTimeActive = state.slowTime && state.groups[state.groupIndex]?.jokers?.used.includes("slowTime"); els.videoStatus.textContent = slowTimeActive ? "Video playing in slow mode…" : isOverride ? "Override replay in use." : "Video playing…"; const startSegment = () => { els.video.currentTime = startAt; els.video.playbackRate = slowTimeActive ? .8 : 1; els.video.play().then(monitorVideoSegment).catch(() => { restoreBackgroundMusic(); if (!isOverride) state.videoPlays -= 1; updateWatchCounter(state.videoPlays); els.answerNow.hidden = true; els.answerNow.disabled = true; els.playVideo.hidden = false; els.fallback.hidden = false; els.videoStatus.textContent = "The video could not start. Try again."; }); }; if (els.video.readyState >= HTMLMediaElement.HAVE_METADATA) startSegment(); else els.video.addEventListener("loadedmetadata", startSegment, { once: true }); }
function beginAnswerPhase(withSubtitles) { if (withSubtitles) { revealSubtitles(state); showTranscript(state.question.transcript); } else chooseNoSubtitles(state); els.decisionOverlay.hidden = true; els.answerOverlay.hidden = false; els.answers.hidden = true; els.videoStatus.textContent = "Get ready…"; clearTimeout(answerRevealTimer); answerRevealTimer = setTimeout(() => { answerRevealTimer = 0; if (!state || state.phase !== "answer" || state.answered) return; showAnswers(state.question, state.difficulty); startTimer(); }, 1000); }
function announceToast(message, type) { window.ToastManager?.show(message, type, 3600); }
function announceStreak(group, streakResult) { if (streakResult.bonusPoints) announceToast(`🔥 ${group.name}: 3 LISTENING STREAK · +${streakResult.bonusPoints} BONUS!`); if (streakResult.freeJoker) announceToast(`⚡ ${group.name}: 5 LISTENING STREAK · ONE FREE JOKER!`); }
function startTimer(reset = true) { clearInterval(state.timerId); if (reset) state.secondsLeft = GAME_CONFIG.answerSeconds; setTimer(state.secondsLeft); state.timerId = setInterval(() => { state.secondsLeft -= 1; setTimer(state.secondsLeft); if (state.secondsLeft <= 0) { clearInterval(state.timerId); state.timerId = null; const result = answerQuestion(state, "__timeout__"); const streakResult = applyListeningStreak(state, result); if (studentMode) { window.StudentGame?.onListeningWrong?.(); window.OliviaMemoryJourney?.recordResult?.({ correct: false, subtitlesShown: state.subtitlesShown, points: 0, bonusPoints: 0, streak: activePlayer(state).group.streak }); } playAnswerSound(false); showFeedback(state.question, result, true); renderJokers(state); announceStreak(activePlayer(state).group, streakResult); if (!studentMode) setTimeout(() => showLeaderboard(state), 2000); } }, 1000); renderJokers(state); }
async function runEvidenceReplay() { const snapshot = suspendQuestionOverlays(); const fullTranscriptEvidence = state.question?.evidenceStart == null && state.question?.evidenceEnd == null && state.question?.evidenceSentence == null; const playbackRate = els.video.playbackRate; els.evidenceReplay.disabled = true; els.next.hidden = true; showEvidenceView(getEvidenceLine(state.question), fullTranscriptEvidence); els.videoStatus.textContent = !hasCompleteEvidence(state.question) ? "Full video evidence replay…" : "Evidence replay…"; els.video.playbackRate = 1; await playEvidenceSegment(els.video, state.question); els.video.playbackRate = playbackRate; restoreBackgroundMusic(); hideEvidenceView(); restoreQuestionOverlays(snapshot); activateTranscriptEvidenceHighlight(state.question); activateAnswerEvidenceHighlight(state.question, state.question.correctOptionId); els.evidenceReplay.disabled = false; els.evidenceReplay.textContent = "▶ EVIDENCE REPLAY"; els.next.hidden = false; els.next.disabled = false; els.next.textContent = "CONTINUE →"; els.videoStatus.textContent = "Evidence replay complete."; }
function selectAnswer(event) { const optionId = event.currentTarget.dataset.answer; clearInterval(state.timerId); state.timerId = null; const result = answerQuestion(state, optionId); if (result) { evidencePlayed = false; evidenceAdvancePending = false; const group = activePlayer(state).group; if (studentMode && result.correct) { const teacherPoints = result.points; result.points = (state.subtitlesShown ? 1 : 2) * (result.doubleOrNothing ? 2 : 1); group.score += result.points - teacherPoints; activePlayer(state).student.score += result.points - teacherPoints; } else if (result.correct) { const timeBonus = Math.max(0, state.secondsLeft); result.points += timeBonus; group.score += timeBonus; activePlayer(state).student.score += timeBonus; } const streakResult = applyListeningStreak(state, result); if (studentMode) { if (result.correct) window.StudentGame?.onListeningCorrect?.(result.points); else window.StudentGame?.onListeningWrong?.(); if (streakResult.bonusPoints) { group.score -= streakResult.bonusPoints; streakResult.bonusPoints = 1; window.StudentGame?.awardListeningBonus?.(1); } window.OliviaMemoryJourney?.recordResult?.({ correct: result.correct, subtitlesShown: state.subtitlesShown, points: result.points, bonusPoints: streakResult.bonusPoints || 0, streak: group.streak }); } playAnswerSound(result.correct); if (result.correct) { animateScoreAward(event.currentTarget, state.groupIndex, result.points, group.score); celebrateActivePortrait(); } showFeedback(state.question, result); renderJokers(state); announceStreak(group, streakResult); } }
async function handleEvidenceControl() { if (!state?.answered || evidenceAdvancePending) return; evidenceSkipRequested = false; await runEvidenceReplay(); evidencePlayed = true; if (evidenceSkipRequested) { evidenceSkipRequested = false; handleNextControl(); } }
function handleNextControl() { if (!state?.answered || !evidencePlayed) return nextTurn(); if (evidenceAdvancePending) return; evidenceAdvancePending = true; els.evidenceReplay.disabled = true; els.next.disabled = true; els.feedback.hidden = true; if (studentMode) return nextTurn(); showLeaderboard(state); setTimeout(nextTurn, 3100); }
async function useEchoJoker() { if (!canUseJoker(state, "echo") || state.videoPlays < 1 || !["video", "answer"].includes(state.phase)) return; const previousPhase = state.phase; const timerWasRunning = previousPhase === "answer" && Boolean(state.timerId); if (!consumeJoker(state, "echo")) return; if (timerWasRunning) { clearInterval(state.timerId); state.timerId = null; } els.overrideReplay.disabled = true; const snapshot = suspendQuestionOverlays(); state.phase = "jokerEcho"; renderJokers(state); showVideoPlayback(); els.videoStatus.textContent = "Echo Joker replay…"; announceToast(`🔊 ${activePlayer(state).group.name}: ECHO JOKER!`); await playEchoSegment(els.video, state.question); restoreBackgroundMusic(); concealVideo(); state.phase = previousPhase; restoreQuestionOverlays(snapshot); if (previousPhase === "video") els.overrideReplay.disabled = false; els.videoStatus.textContent = previousPhase === "answer" ? "Choose your answer." : "Choose how to answer."; if (timerWasRunning) startTimer(false); else renderJokers(state); }
function useTimeFreezeJoker() { if (state?.phase !== "answer" || !state.timerId || !consumeJoker(state, "timeFreeze")) return; state.secondsLeft += GAME_CONFIG.timeFreezeSeconds; setTimer(state.secondsLeft); renderJokers(state); announceToast(`⏱ ${activePlayer(state).group.name}: TIME FREEZE · +${GAME_CONFIG.timeFreezeSeconds} SECONDS!`); }
function useDoubleOrNothingJoker() { if (state?.phase !== "answer" || state.answered || !consumeJoker(state, "doubleOrNothing")) return; state.doubleOrNothing = true; renderJokers(state); announceToast(`×2 ${activePlayer(state).group.name}: DOUBLE OR NOTHING!`); }
function useSlowTimeJoker() { if (state?.phase !== "video" || !els.video.paused || !consumeJoker(state, "slowTime")) return; state.slowTime = true; els.video.playbackRate = .8; renderJokers(state); announceToast(`◔ ${activePlayer(state).group.name}: SLOW TIME · 80% VIDEO SPEED!`); }
function nextTurn() { if (studentMode) { if (window.OliviaMemoryJourney?.shouldComplete?.()) { clearInterval(state?.timerId); restoreBackgroundMusic(); showScreen("setup"); window.OliviaMemoryJourney.complete(); return; } showAnnouncement(); return; } const next = advanceTurn(state); if (next === "roundComplete") { showScreen("round"); els.roundTitle.textContent = `ROUND ${state.round} COMPLETE`; els.roundMessage.textContent = "Every player has had one turn. Start another round or finish the game."; renderRoundScores(state); } else showAnnouncement(); }
function finishGame() { showScreen("final"); renderFinal(state, getRosterPointAwards(state.groups, GAME_CONFIG.rosterPointRatio)); duckBackgroundMusic(); finalAudio.currentTime = 0; finalAudio.play().catch(() => {}); if (typeof FinalScreen !== "undefined") { FinalScreen.start(); FinalScreen.applyRays(document.querySelector(".winner-ann")); } }

document.querySelectorAll("[data-group-count]").forEach((button) => button.addEventListener("click", () => { groupCount = Number(button.dataset.groupCount); document.querySelectorAll("[data-group-count]").forEach((item) => item.classList.toggle("is-selected", item === button)); syncSetup(); }));
els.groupNameFields.addEventListener("change", (event) => { if (!event.target.matches("[data-group-name]")) return; groupNames[Number(event.target.dataset.groupName)] = event.target.value.toUpperCase() || `TEAM ${Number(event.target.dataset.groupName) + 1}`; syncSetup(); });
els.teamEditor.addEventListener("click", (event) => { const target = event.target.closest("[data-remove-student]"); if (!target) return; const [groupIndex, studentIndex] = target.dataset.removeStudent.split(":").map(Number); setupGroups[groupIndex].splice(studentIndex, 1); syncSetup(); });
$("#open-roster-button").addEventListener("click", openRosterPicker); document.querySelectorAll("[data-close-roster]").forEach((button) => button.addEventListener("click", () => { els.rosterDialog.hidden = true; }));
$("#add-student-button").addEventListener("click", () => { const name = els.manualName.value.trim(); const team = Number(els.manualTeam.value); if (!name) return; setupGroups[team].push(name); els.manualName.value = ""; syncSetup(); });
els.start.addEventListener("click", beginGame); els.difficultyButtons.forEach((button) => button.addEventListener("click", () => { if (setDifficulty(state, button.dataset.difficulty)) { setDifficultySelection(state.difficulty); playVideo(); } })); els.playVideo.addEventListener("click", () => playVideo()); els.replay.addEventListener("click", () => playVideo()); els.answerNow.addEventListener("click", finishVideoSegment); els.overrideReplay.addEventListener("click", () => { if (state?.phase === "video" && els.video.paused && !els.decisionOverlay.hidden) playVideo(true); }); els.video.addEventListener("play", () => { duckBackgroundMusic(); els.playVideo.hidden = true; els.fallback.hidden = true; els.replay.disabled = true; els.answerNow.disabled = false; els.overrideReplay.disabled = true; renderJokers(state); }); els.video.addEventListener("ended", finishVideoSegment); els.video.addEventListener("error", () => { stopSegmentMonitor(); restoreBackgroundMusic(); if (!retryVideoFromR2()) replaceMissingVideo(); });
els.videoVolume.addEventListener("input", () => { els.video.volume = Number(els.videoVolume.value); });
els.characterGrid.addEventListener("click", (event) => { const choice = event.target.closest("[data-character-id]"); if (!choice || !state || !isCharacterBasedMode()) return; const item = state.itemPicker.pickForCharacter?.(choice.dataset.characterId); if (!item) return showCharacterSelection("No unused videos remain for that character. Choose another one."); els.characterDialog.hidden = true; loadCurrentQuestion(startQuestion(state, item)); });
els.characterRandom.addEventListener("click", () => { if (!state || !isCharacterBasedMode()) return; const item = state.itemPicker(); els.characterDialog.hidden = true; loadCurrentQuestion(startQuestion(state, item)); });
els.characterScores.addEventListener("click", () => { if (!state) return; renderRoundScores(state, els.liveScores); els.scoreDialog.hidden = false; });
$("#reset-video-history-button").addEventListener("click", () => { $("#reset-video-history-dialog").hidden = false; }); document.querySelectorAll("[data-close-video-history-reset]").forEach((button) => button.addEventListener("click", closeVideoHistoryResetDialog)); $("#confirm-video-history-reset").addEventListener("click", resetVideoHistory);
$("#lite-mode-button").addEventListener("click", () => setLiteMode(!document.body.classList.contains("lite-mode")));
$("#scores-button").addEventListener("click", () => { if (!state) return; renderRoundScores(state, els.liveScores); els.scoreDialog.hidden = false; }); document.querySelectorAll("[data-close-score-dialog]").forEach((button) => button.addEventListener("click", () => { els.scoreDialog.hidden = true; }));
els.jokerButtons.forEach((button) => button.addEventListener("click", () => { if (button.dataset.joker === "echo") useEchoJoker(); else if (button.dataset.joker === "timeFreeze") useTimeFreezeJoker(); else if (button.dataset.joker === "slowTime") useSlowTimeJoker(); else useDoubleOrNothingJoker(); }));
$("#previous-track-button").addEventListener("click", previousBackgroundTrack); $("#next-track-button").addEventListener("click", nextBackgroundTrack); $("#mute-music-button").addEventListener("click", (event) => { const isMuted = toggleBackgroundMusic(); event.currentTarget.textContent = isMuted ? "🔇" : "♫"; event.currentTarget.setAttribute("aria-label", isMuted ? "Unmute background music" : "Mute background music"); event.currentTarget.title = isMuted ? "Unmute music" : "Mute music"; });
$("#no-subtitle-button").addEventListener("click", () => beginAnswerPhase(false)); $("#show-subtitle-button").addEventListener("click", () => beginAnswerPhase(true)); els.answers.querySelectorAll("button").forEach((button) => button.addEventListener("click", selectAnswer)); els.evidenceReplay.addEventListener("click", handleEvidenceControl); els.next.addEventListener("click", handleNextControl);
els.evidence.addEventListener("click", (event) => { if (event.button !== 0 || els.evidence.hidden || !state?.answered) return; evidenceSkipRequested = true; els.video.dispatchEvent(new Event("evidence-skip")); });
$("#continue-round-button").addEventListener("click", () => { if (continueRound(state)) { showScreen("game"); showAnnouncement(); } else finishGame(); }); $("#finish-game-button").addEventListener("click", finishGame); $("#transfer-points-button").addEventListener("click", (event) => { const result = transferRosterPoints(state.groups, classroomId, GAME_CONFIG.rosterPointRatio); event.currentTarget.disabled = true; event.currentTarget.textContent = result.awarded?.length ? "✓ POINTS TRANSFERRED" : "NO POINTS TO TRANSFER"; }); $("#new-game-button").addEventListener("click", () => location.reload()); $("#exit-game-button").addEventListener("click", () => { if (confirm("Exit the game and return to setup?")) { clearInterval(state?.timerId); showScreen("setup"); } });

prepareStudentMode();
setLiteMode(localStorage.getItem(liteModeStorageKey) === "1");
syncSetup();
})();
