(() => {
window.LeagueListening = window.LeagueListening || {};
const { GAME_CONFIG } = window.LeagueListening;

const $ = (selector) => document.querySelector(selector);
const els = Object.freeze({
  setup: $("#setup-screen"), game: $("#game-screen"), round: $("#round-screen"), final: $("#final-screen"),
  teamEditor: $("#team-editor"), groupNameFields: $("#group-name-fields"), rosterStatus: $("#roster-status"), manualName: $("#manual-student-input"), manualTeam: $("#manual-student-team"), roundLimit: $("#round-limit"), start: $("#start-game-button"),
  scoreboard: $("#scoreboard"), roundLabel: $("#round-label"), turnLabel: $("#turn-label"), dialogueCharacters: $("#dialogue-characters"), videoFunction: $("#video-function"), videoFunctionName: $("#video-function-name"), teamChip: $("#active-team-chip"), studentName: $("#active-student-name"), studentAvatar: $("#active-student-avatar"), instruction: $("#turn-instruction"), jokerRemaining: $("#joker-remaining"), jokerButtons: document.querySelectorAll("[data-joker]"), noSubtitle: $("#no-subtitle-button"), showSubtitle: $("#show-subtitle-button"), videoWrap: $("#video-wrap"), video: $("#listening-video"), fallback: $("#video-fallback"), difficultySelector: $("#difficulty-selector"), difficultyButtons: document.querySelectorAll("[data-difficulty]"), playVideo: $("#play-video-button"), watchCounter: $("#watch-counter"), videoStatus: $("#video-status"), replay: $("#replay-button"), answerNow: $("#answer-now-button"), overrideReplay: $("#override-replay-button"), decisionOverlay: $("#decision-overlay"), answerOverlay: $("#answer-overlay"), evidence: $("#evidence-overlay"), evidenceText: $("#evidence-text"), transcript: $("#transcript-panel"), transcriptText: $("#transcript-text"), answers: $("#answer-panel"), feedback: $("#feedback-panel"), feedbackTitle: $("#feedback-title"), feedbackMessage: $("#feedback-message"), evidenceReplay: $("#evidence-replay-button"), next: $("#next-turn-button"), timer: $("#answer-timer"),
  rosterDialog: $("#roster-dialog"), classroomList: $("#classroom-list"), classroomMessage: $("#classroom-message"), roundTitle: $("#round-complete-title"), roundMessage: $("#round-complete-message"), winnerName: $("#winner-team-name"), winnerScore: $("#winner-team-score"), finalTeams: $("#final-team-scores"), finalStudents: $("#final-student-scores")
});
els.studentAvatar.addEventListener("error", () => { els.studentAvatar.hidden = true; els.studentAvatar.removeAttribute("src"); });

function showScreen(name) { ["setup", "game", "round", "final"].forEach((key) => { els[key].hidden = key !== name; }); }
function renderSetup(groups, names) { els.groupNameFields.innerHTML = groups.map((_, i) => `<label class="field-label">Team ${i + 1}<input data-group-name="${i}" maxlength="16" value="${names[i] || `TEAM ${i + 1}`}"></label>`).join(""); els.manualTeam.innerHTML = groups.map((_, i) => `<option value="${i}">${names[i] || `TEAM ${i + 1}`}</option>`).join(""); renderTeams(groups, names); }
function renderTeams(groups, names) { els.teamEditor.innerHTML = groups.map((students, groupIndex) => `<div class="team-edit-card team-${groupIndex}"><strong>${names[groupIndex] || `TEAM ${groupIndex + 1}`}</strong><div>${students.map((student, index) => `<button type="button" class="student-pill" data-remove-student="${groupIndex}:${index}" title="Click to remove">${typeof student === "string" ? student : student.name} ×</button>`).join("") || "<span class=\"muted\">No players yet</span>"}</div></div>`).join(""); }
function renderGame(state, player) { const total = state.groups.reduce((sum, group) => sum + group.students.length, 0); els.roundLabel.textContent = `ROUND ${state.round}`; els.turnLabel.textContent = `${state.turnsInRound + 1} / ${total}`; els.scoreboard.innerHTML = state.groups.map((group) => `<div class="score-card ${group.color} ${group.id === state.groupIndex ? "active" : ""}" data-group-id="${group.id}"><span>${group.name}${group.streak ? ` · 🔥${group.streak}` : ""}</span><strong>${group.score}</strong></div>`).join(""); els.dialogueCharacters.replaceChildren(); (state.question?.characterIds || []).forEach((id) => { const character = document.createElement("div"); const portrait = document.createElement("img"); const name = document.createElement("span"); character.className = "dialogue-character"; portrait.src = `assets/portraits/${id}.webp`; portrait.alt = `${id} portrait`; portrait.addEventListener("error", () => character.remove()); name.textContent = `${id.charAt(0).toUpperCase()}${id.slice(1)}`; character.append(portrait, name); els.dialogueCharacters.append(character); }); const functionKeys = Array.isArray(state.question?.functions) ? state.question.functions : [state.question?.functions]; const functions = functionKeys.filter(Boolean).map((key) => window.LEAGUE_OF_LISTENING_FUNCTIONS?.[key] || key).join("\n"); els.videoFunction.hidden = !functions; els.videoFunctionName.textContent = functions; els.teamChip.className = `team-chip ${player.group.color}`; els.teamChip.textContent = player.group.name; els.studentName.textContent = player.student.name; els.studentAvatar.hidden = !player.student.avatarPath; els.studentAvatar.removeAttribute("src"); if (player.student.avatarPath) { els.studentAvatar.src = player.student.avatarPath; els.studentAvatar.alt = `${player.student.name} avatar`; } renderJokers(state); }
function renderJokers(state) { const group = state?.groups?.[state.groupIndex]; const jokers = group?.jokers; if (!jokers) return; els.jokerRemaining.textContent = `${jokers.remaining} LEFT`; els.jokerButtons.forEach((button) => { const type = button.dataset.joker; const used = jokers.used.includes(type); const phaseAllowed = type === "echo" ? state.videoPlays > 0 && els.video.paused && ["video", "answer"].includes(state.phase) : type === "timeFreeze" ? state.phase === "answer" && Boolean(state.timerId) : state.phase === "answer" && !state.doubleOrNothing; button.disabled = used || jokers.remaining <= 0 || !phaseAllowed || state.answered; button.classList.toggle("is-used", used); button.classList.toggle("is-active", type === "doubleOrNothing" && state.doubleOrNothing); }); }
function animateScoreAward(source, groupId, points, score) { const target = els.scoreboard.querySelector(`[data-group-id="${groupId}"]`); if (!source || !target || points <= 0) return; const sourceRect = source.getBoundingClientRect(); const targetRect = target.getBoundingClientRect(); const token = document.createElement("div"); let completed = false; const complete = () => { if (completed) return; completed = true; target.querySelector("strong").textContent = score; target.classList.add("score-pulse"); setTimeout(() => { target.classList.remove("score-pulse"); token.remove(); }, 420); }; token.className = "score-fly"; token.textContent = `+${points}`; token.style.left = `${sourceRect.left + sourceRect.width / 2}px`; token.style.top = `${sourceRect.top + sourceRect.height / 2}px`; token.addEventListener("transitionend", (event) => { if (event.propertyName === "left") complete(); }); document.body.append(token); requestAnimationFrame(() => { token.style.left = `${targetRect.left + targetRect.width / 2}px`; token.style.top = `${targetRect.top + targetRect.height / 2}px`; }); setTimeout(complete, 1000); }
function resetQuestionView() { els.decisionOverlay.hidden = true; els.answerOverlay.hidden = true; els.evidence.hidden = true; els.transcript.hidden = true; els.answers.hidden = true; els.answers.querySelectorAll("button").forEach((button) => { button.textContent = ""; button.disabled = true; button.className = "answer-card"; }); els.feedback.hidden = true; els.evidenceReplay.hidden = true; els.next.hidden = true; els.timer.hidden = true; els.replay.disabled = true; els.answerNow.disabled = true; els.overrideReplay.disabled = true; els.playVideo.hidden = true; els.fallback.hidden = false; els.video.hidden = false; els.videoWrap.classList.remove("is-black-stage", "is-dark-stage"); els.video.removeAttribute("src"); els.video.load(); }
function loadQuestion(item) { resetQuestionView(); els.video.src = item.videoSrc; els.video.hidden = true; els.fallback.hidden = true; els.videoWrap.classList.add("is-black-stage"); els.difficultySelector.hidden = false; els.playVideo.hidden = true; els.playVideo.disabled = true; els.videoStatus.textContent = "Choose a difficulty to start."; }
function setDifficultySelection(difficulty) { els.difficultyButtons.forEach((button) => button.classList.toggle("is-selected", button.dataset.difficulty === difficulty)); els.difficultySelector.hidden = Boolean(difficulty); els.playVideo.disabled = !difficulty; }
function showVideoPlayback() { els.video.hidden = false; els.videoWrap.classList.remove("is-black-stage", "is-dark-stage"); }
function concealVideo() { els.video.hidden = false; els.fallback.hidden = true; els.videoWrap.classList.remove("is-black-stage"); els.videoWrap.classList.add("is-dark-stage"); }
function updateWatchCounter(plays) { const replaysLeft = GAME_CONFIG.maxVideoPlays - plays; els.watchCounter.textContent = plays === 0 ? "REGULAR REPLAY AVAILABLE: 1" : replaysLeft > 0 ? "REGULAR REPLAY LEFT: 1" : "REGULAR REPLAY LIMIT REACHED"; els.replay.disabled = plays === 0 || replaysLeft <= 0; }
function showDecision() { els.decisionOverlay.hidden = false; els.videoStatus.textContent = "Choose how to answer."; }
function appendMarkedText(container, text, highlightStyle = "none") { String(text || "").split(/(\/[^/]+\/)/g).forEach((part) => { if (!part) return; const marked = part.startsWith("/") && part.endsWith("/"); if (marked && highlightStyle !== "none") { const highlight = document.createElement("span"); highlight.className = highlightStyle === "evidence" ? "evidence-target" : "answer-highlight"; highlight.textContent = part.slice(1, -1); container.append(highlight); return; } container.append(document.createTextNode(marked ? part.slice(1, -1) : part)); }); }
function renderDialogueText(container, text, speakerClass, highlightStyle = "none") { const lines = String(text || "").replace(/([.!?])\s+/g, "$1\n").split("\n"); container.replaceChildren(); lines.forEach((line, index) => { const match = line.match(/^([^:]+:)\s*/); if (match) { const speaker = document.createElement("span"); speaker.className = speakerClass; speaker.textContent = match[1]; container.append(speaker); appendMarkedText(container, line.slice(match[0].length), highlightStyle); } else appendMarkedText(container, line, highlightStyle); if (index < lines.length - 1) container.append(document.createElement("br")); }); }
function showTranscript(text) { els.transcript.hidden = false; renderDialogueText(els.transcriptText, text, "transcript-speaker"); }
function showAnswers(item, difficulty) { const distractor = window.LEAGUE_OF_LISTENING_DIFFICULTY_DISTRACTORS?.[item.id]?.[difficulty]; els.decisionOverlay.hidden = true; els.replay.disabled = true; els.answerNow.disabled = true; els.overrideReplay.disabled = true; els.videoWrap.classList.remove("is-dark-stage"); els.answerOverlay.hidden = false; els.answers.hidden = false; item.answerOptions.forEach((option) => { const button = els.answers.querySelector(`[data-answer="${option.id}"]`); if (button) { renderDialogueText(button, option.id === item.correctOptionId ? option.text : distractor || option.text, "answer-speaker"); button.disabled = false; button.className = "answer-card"; } }); }
function showFeedback(item, result, timedOut = false) { showTranscript(item.transcript); els.answers.querySelectorAll("button").forEach((button) => { button.disabled = true; button.classList.toggle("correct", button.dataset.answer === result.correctOptionId); if (!timedOut && !result.correct && button.dataset.answer !== result.correctOptionId) button.classList.add("incorrect"); }); const correctOption = item.answerOptions.find((option) => option.id === result.correctOptionId); const correctButton = els.answers.querySelector(`[data-answer="${result.correctOptionId}"]`); if (correctOption && correctButton) renderDialogueText(correctButton, correctOption.text, "answer-speaker", "answer"); const isWrong = !timedOut && !result.correct; const feedbackText = timedOut ? "Time ran out. The answer was not scored." : result.correct ? item.explanation || "" : ""; els.feedbackTitle.textContent = timedOut ? "TIME'S UP" : result.correct ? `${result.doubleOrNothing ? "DOUBLE! " : ""}CORRECT! +${result.points}` : "NOT THIS TIME"; els.feedbackMessage.textContent = feedbackText; els.feedbackMessage.hidden = !feedbackText; els.feedback.classList.toggle("not-this-time", isWrong); els.evidenceReplay.hidden = timedOut; els.evidenceReplay.disabled = false; els.evidenceReplay.textContent = "▶ EVIDENCE REPLAY"; els.next.hidden = !timedOut; els.next.disabled = false; els.next.textContent = "NEXT →"; els.feedback.hidden = false; }
function activateAnswerEvidenceHighlight(item, correctOptionId) { const correctOption = item.answerOptions.find((option) => option.id === correctOptionId); const correctButton = els.answers.querySelector(`[data-answer="${correctOptionId}"]`); if (correctOption && correctButton) renderDialogueText(correctButton, correctOption.text, "answer-speaker", "evidence"); }
function activateTranscriptEvidenceHighlight(item) { renderDialogueText(els.transcriptText, item.transcript, "transcript-speaker", "evidence"); }
function setTimer(seconds) { els.timer.hidden = false; els.timer.textContent = seconds; els.timer.classList.toggle("danger", seconds <= 5); }
function suspendQuestionOverlays() { const snapshot = { decision: els.decisionOverlay.hidden, answer: els.answerOverlay.hidden, feedback: els.feedback.hidden }; els.decisionOverlay.hidden = true; els.answerOverlay.hidden = true; els.feedback.hidden = true; return snapshot; }
function restoreQuestionOverlays(snapshot) { els.decisionOverlay.hidden = snapshot.decision; els.answerOverlay.hidden = snapshot.answer; els.feedback.hidden = snapshot.feedback; }
function appendEvidenceText(container, text) { const value = String(text || ""); const hasHighlight = /\/[^/]+\//.test(value); const appendPart = (part, highlighted) => { if (!part) return; const span = document.createElement(highlighted ? "mark" : "span"); if (highlighted) span.className = "evidence-target"; span.textContent = part; container.append(span); }; value.replace(/([.!?])\s+/g, "$1\n").split("\n").forEach((line, index, lines) => { const speakerMatch = line.match(/^([^:]+:)\s*/); if (speakerMatch) { const speaker = document.createElement("span"); speaker.className = "evidence-speaker"; speaker.textContent = `${speakerMatch[1]} `; container.append(speaker); line = line.slice(speakerMatch[0].length); } if (hasHighlight) { line.split(/(\/[^/]+\/)/g).forEach((part) => { const marked = part.startsWith("/") && part.endsWith("/"); appendPart(marked ? part.slice(1, -1) : part, marked); }); } else appendPart(line, true); if (index < lines.length - 1) container.append(document.createElement("br")); }); }
function showEvidenceView(text, fullTranscript = false) { els.evidenceText.replaceChildren(); if (fullTranscript) renderDialogueText(els.evidenceText, text, "evidence-speaker"); else { const match = String(text || "").match(/^([^:]+:)\s*(.*)$/); if (match) { const speaker = document.createElement("span"); speaker.className = "evidence-speaker"; speaker.textContent = `${match[1]} `; els.evidenceText.append(speaker); appendEvidenceText(els.evidenceText, match[2]); } else appendEvidenceText(els.evidenceText, text); } els.evidence.hidden = false; showVideoPlayback(); }
function hideEvidenceView() { els.evidence.hidden = true; concealVideo(); }
function renderFinal(state) { const winner = [...state.groups].sort((a, b) => b.score - a.score)[0]; els.winnerName.textContent = `${winner.name} WINS!`; els.winnerScore.textContent = `${winner.score} game points`; els.finalTeams.innerHTML = state.groups.map((group) => `<div class="summary-row"><span>${group.name}</span><strong>${group.score}</strong></div>`).join(""); els.finalStudents.innerHTML = state.groups.flatMap((group) => group.students.map((student) => `<div class="summary-row"><span>${student.name} <small>${group.name}</small></span><strong>${student.score}</strong></div>`)).join(""); }

Object.assign(window.LeagueListening, { activateAnswerEvidenceHighlight, activateTranscriptEvidenceHighlight, animateScoreAward, concealVideo, els, hideEvidenceView, loadQuestion, renderFinal, renderGame, renderJokers, renderSetup, resetQuestionView, restoreQuestionOverlays, setDifficultySelection, setTimer, showAnswers, showDecision, showEvidenceView, showFeedback, showScreen, showTranscript, showVideoPlayback, suspendQuestionOverlays, updateWatchCounter });
})();
