/*
  LEAGUE OF LISTENING CONTENT
  Her video kaydı yalnızca bu dosyada tutulur; arayüz veya oyun mantığına
  eğitim içeriği yazılmaz. Bir kaydın oyuna girmesi için transcript / iki
  seçenek / correctOptionId alanları dolu olmalıdır.
*/
window.LEAGUE_OF_LISTENING_ITEMS = [
{
    id: "5_classroom_life_chloe_ella",
    status: "published",
    videoSrc: "assets/video/5_classroom_life_chloe_ella.mp4",
    thumbnail: "0:06.066",
    title: "Ella checks the time before music begins.",
    transcript: "Ella : Is it /two o'clock/ already? Chloe : Yes, it is, Music starts now.",
    answerOptions: [
      { id: "a", text: "Ella : Saat /iki/ oldu mu? Chloe : Evet, Oldu, Müzik şimdi başlıyor." },
      { id: "b", text: "Ella : Saat ikiyi çeyrek geçti mi? Chloe : Evet, geçti, Müzik biraz sonra başlıyor." }
    ],
    easyDistractor: "Ella : Saat üç oldu mu bile? Chloe : Evet, Oldu, Müzik şimdi başlıyor.",
    correctOptionId: "a", // TODO: "a" veya "b"
    explanation: "",
    characterIds: ["chloe", "ella"],
    grades: [5, 6],
    functions: ["telling_time"],
    theme: "Classroom_life",
    evidenceStart: "0:00.636",
evidenceEnd: "0:02.406",
    evidenceSentence: "Ella : Is it /two o'clock/ already?",
  },
{
    id: "5_classroom_life_chloe_noah",
    status: "published",
    videoSrc: "assets/video/5_classroom_life_chloe_noah.mp4",
    thumbnail: "0:05.671",
    title: "Chloe and Noah check when double science starts.",
    transcript: "Chloe : /What time/ does double science start? Noah : At /half past ten/. Chloe : Oh no, That's now, Thanks!",
    answerOptions: [
      { id: "a", text: "Chloe : Çift fen dersi ne zaman başlıyor? Noah : Saat onu yirmi geçe. Chloe : Oh hayır, Şimdi başlıyor, Teşekkürler!" },
      { id: "b", text: "Chloe : Çift fen dersi /saat kaçta/ başlıyor? Noah : Saat /on buçukta/. Chloe : Oh hayır, Şimdi başlıyor, Teşekkürler!" }
    ],
    easyDistractor: "Chloe : Çift fen dersi kaçta başlıyor? Noah : Saat onda. Chloe : Oh hayır, Şimdi başlıyor, Teşekkürler!",
    correctOptionId: "b", // TODO: "a" veya "b"
    explanation: "",
    characterIds: ["chloe", "noah"],
    grades: [5, 6],
    functions: ["use_of_wh_questions_what_time","telling_time"],
    theme: "Classroom_life",
    evidenceStart: "0:00.000",
evidenceEnd: "0:03.680",
    evidenceSentence: "Chloe : /What time/ does double science start? Noah : At /half past ten/",
  },
{
    id: "5_classroom_life_ella_olivia",
    status: "published",
    videoSrc: "assets/video/5_classroom_life_ella_olivia.mp4",
    thumbnail: "0:05.152",
    title: "Ella asks Olivia about a dictionary in her bag.",
    transcript: "Ella : /Is there/ a dictionary in your bag? Olivia : Yes, there is, You can borrow it.",
    answerOptions: [
      { id: "a", text: "Ella : Çantanda bir sözlük /var mı/? Olivia : Evet, Var, Ödünç alabilirsin." },
      { id: "b", text: "Ella : Sözlüğünü getirdin mi? Olivia : Evet getirdim, Ödünç alabilirsin." }
    ],
    easyDistractor: "Ella : Çantanda cetvel var mı? Olivia : Evet, Var, Ödünç alabilirsin.",
    correctOptionId: "a", // TODO: "a" veya "b"
    explanation: "",
    characterIds: ["ella", "olivia"],
    grades: [5, 6],
    functions: ["use_of_there_is_there_are"],
    theme: "Classroom_life",
    evidenceStart: "0:00.331",
evidenceEnd: "0:02.592",
    evidenceSentence: "Ella : /Is there/ a dictionary in your bag?",
  },
{
    id: "5_classroom_life_hannah_mia",
    status: "published",
    videoSrc: "assets/video/5_classroom_life_hannah_mia.mp4",
    thumbnail: "0:06.085",
    title: "Hannah and Mia check the time before hurrying.",
    transcript: "Hannah : What time is it now? Mia : It's /twenty past ten/. Hannah : We should hurry!",
    answerOptions: [
      { id: "a", text: "Hannah : Şimdi saat kaç? Mia : Saat /onu yirmi geçiyor/. Hannah : Acele etmeliyiz!" },
      { id: "b", text: "Hannah : Şimdi saat kaç? Mia : Saat onu çeyrek geçiyor. Hannah : Acele etmeliyiz!" }
    ],
    easyDistractor: "Hannah : Şimdi saat kaç? Mia : Saat on. Hannah : Acele etmeliyiz!",
    correctOptionId: "a", // TODO: "a" veya "b"
    explanation: "",
    characterIds: ["hannah", "mia"],
    grades: [5, 6],
    functions: ["telling_time"],
    theme: "Classroom_life",
    evidenceStart: "0:01.677",
evidenceEnd: "0:03.137",
    evidenceSentence: "Mia : It's /twenty past ten/",
  },
{
    id: "5_classroom_life_olivia",
    status: "published",
    videoSrc: "assets/video/5_classroom_life_olivia.mp4",
    thumbnail: "0:05.377",
    title: "Olivia hurries to finish her drawing but pours the paint bottle.",
    transcript: "Olivia : /What time/ does the lesson finish? Teacher : At quarter past two. Olivia : I must hurry!",
    answerOptions: [
      { id: "a", text: "Olivia : Ders /saat kaçta/ bitecek? Öğretmen : İkiyi çeyrek geçe. Olivia : Acele etmeliyim!" },
      { id: "b", text: "Olivia : Sonraki ders ne zaman başlayacak? Öğretmen : İkiyi çeyrek geçe. Olivia : Acele etmeliyim!" }
    ],
    easyDistractor: "Öğretmen : Olivia, Konuşmak için ayağa kalk. Olivia : Tamam!",
    correctOptionId: "a", // TODO: "a" veya "b"
    explanation: "",
    characterIds: ["olivia"],
    grades: [5, 6],
    functions: ["askinginformationabouttime"],
    theme: "School_life",
    evidenceStart: "0:01.344",
evidenceEnd: "0:02.985",
evidenceSentence: "Olivia : /What time/ does the lesson finish?",
  },
{
    id: "5_classroom_zoe_hannah",
    status: "published",
    videoSrc: "assets/video/5_classroom_zoe_hannah.mp4",
    thumbnail: "0:05.916",
    title: "Hannah asks Zoe when lunch break begins.",
    transcript: "Hannah : /What time/ does lunch break start? Zoe : At /ten past twelve/. Hannah : Great! I'm so hungry.",
    answerOptions: [
      { id: "a", text: "Hannah : Öğle arası /saat kaçta/ başlıyor? Zoe : /On ikiyi on geçe/. Hannah : Harika, Çok acıktım." },
      { id: "b", text: "Hannah : Öğle arası ne zaman başlıyor? Zoe : Onu oniki geçe. Hannah : Harika, Çok acıktım." }
    ],
    easyDistractor: "Hannah : Öğle arası kaçta başlıyor? Zoe : Saat on ikide. Hannah : Harika, Çok acıktım.",
    correctOptionId: "a", // TODO: "a" veya "b"
    explanation: "",
    characterIds: ["hannah", "zoe"],
    grades: [5, 6],
    functions: ["use_of_wh_questions_what_time","telling_time"],
    theme: "Classroom_life",
    evidenceStart: "0:00.621",
evidenceEnd: "0:03.976",
    evidenceSentence: "Hannah : /What time/ does lunch break start? Zoe : At /ten past twelve/.",
  },
{
    id: "5_family_life_hannah_lars",
    status: "published",
    videoSrc: "assets/video/5_family_life_hannah_lars.mp4",
    thumbnail: "0:06.619",
    title: "Hannah asks Lars about the camping bags.",
    transcript: "Hannah : What are you packing, Dad? Lars : I'm /preparing/ our camping bags. Hannah : We /are going/ camping, Yeyy!",
    answerOptions: [
      { id: "a", text: "Hannah : Ne hazırlıyorsun, baba? Lars : Kamp çantalarımızı /hazırlıyorum/. Hannah : Kamp yapacağız, Yaşasın!" },
      { id: "b", text: "Hannah : Ne hazırlıyorsun, baba? Lars : Kamp çantalarımızı hazırlayacağım. Hannah : Kampa gidiyoruz, Yaşasın!" }
    ],
    easyDistractor: "Hannah : Ne hazırlıyorsun, baba? Lars : Kamp çantalarımızı hazırlıyorum. Hannah : Evde mi kalıyoruz, Yaşasın!",
    correctOptionId: "b", // TODO: "a" veya "b"
    explanation: "",
    characterIds: ["hannah", "lars"],
    grades: [5, 6],
    functions: ["present_progressive"],
    theme: "family_life",
    evidenceStart: "0:02.857",
evidenceEnd: "0:07.665",
    evidenceSentence: "Lars : I'm /preparing/ our camping bags. Hannah : We /are going/ camping, Yeyy!",
  },
{
    id: "5_personal_life_appearance_hannah",
    status: "published",
    videoSrc: "assets/video/5_personal_life_appearance_hannah.mp4",
    thumbnail: "0:03.220",
    title: "Hannah describes her physical appearance.",
    transcript: "Hannah : Hi, I'm Hannah, I have /long straight/ blonde hair and /blue/ eyes.",
    answerOptions: [
      { id: "a", text: "Hannah : Merhaba, ben Hannah, orta uzunlukta düz sarı saçlarım ve yeşil gözlerim var." },
      { id: "b", text: "Hannah : Merhaba, ben Hannah, /uzun düz/ sarı saçlarım ve /mavi/ gözlerim var." }
    ],
    easyDistractor: "Hannah : Merhaba, ben Hannah, uzun sarı saçlarım ve kahverengi gözlerim var.",
    correctOptionId: "b", // TODO: "a" veya "b"
    explanation: "",
    characterIds: ["hannah"],
    grades: [5, 6],
    functions: ["describing_physical_appearance"],
    theme: "introduction",
    evidenceStart: "0:02.336",
evidenceEnd: "0:07.155",
evidenceSentence: "I have /long straight/ blonde hair and /blue/ eyes.",
  },
{
    id: "5_personal_life_ava_olivia",
    status: "published",
    videoSrc: "assets/video/5_personal_life_ava_olivia.mp4",
    thumbnail: "0:09.798",
    title: "Ava notices yellow paint on Olivia's nose.",
    transcript: "Ava : Do you paint in the evenings? Olivia : I sometimes paint before bed. Ava : There is a yellow paint on your nose.",
    answerOptions: [
      { id: "a", text: "Ava : Akşamları resim yapar mısın? Olivia : /Bazen/ yatmadan önce resim yaparım. Ava : Burnunda sarı boya /var/." },
      { id: "b", text: "Ava : Akşamları resim yapar mısın? Olivia : Her sabah resim yaparım. Ava : Burnun sarıya boyanmış." }
    ],
    easyDistractor: "Ava : Akşamları resim yapar mısın? Olivia : Hiç resim yapmam. Ava : Burnunda boya yok.",
    correctOptionId: "a", // TODO: "a" veya "b"
    explanation: "",
    characterIds: ["ava", "olivia"],
    grades: [5, 6],
    functions: ["use_of_there_is_there_are","frequency adverbs"],
    theme: "personal_life",
    evidenceStart: "0:05.669",
evidenceEnd: "0:08.614",
    evidenceSentence: "Ava : /There is/ a yellow paint on your nose.",
  },
{
    id: "5_personal_life_chloe_emma",
    status: "published",
    videoSrc: "assets/video/5_personal_life_chloe_emma.mp4",
    thumbnail: "0:06.834",
    title: "Emma asks Chloe about her piano habit.",
    transcript: "Emma : You play the piano every evening, /don't you/? Chloe : Yes, I do.",
    answerOptions: [
      { id: "a", text: "Emma : Her akşam piyano çalarsın, /öyle değil mi/? Chloe : Evet, çalarım." },
      { id: "b", text: "Emma : Her akşam piyano çalar mısın? Chloe : Evet, çalarım." }
    ],
    easyDistractor: "Emma : Her akşam piyano çalarsın, öyle değil mi? Chloe : Hayır, çalmam.",
    correctOptionId: "a", // TODO: "a" veya "b"
    explanation: "",
    characterIds: ["chloe", "emma", "luna"],
    grades: [5, 6],
    functions: ["use_of_simple_present_tense_for_habbits","tag_questions"],
    theme: "personal_life",
    evidenceStart: "0:00.000",
evidenceEnd: "0:03.146",
    evidenceSentence: "Emma : You play the piano every evening, /don't you/?",
  },
{
    id: "5_personal_life_daniel_benjamin",
    status: "published",
    videoSrc: "assets/video/5_personal_life_daniel_benjamin.mp4",
    thumbnail: "0:05.061",
    title: "Benjamin asks Daniel about his scooter routine.",
    transcript: "Benjamin : How often do you ride your scooter? Daniel : I ride it /every afternoon/.",
    answerOptions: [
      { id: "a", text: "Benjamin : Scooterını ne sıklıkla sürersin? Daniel : /Her öğleden sonra/ sürerim." },
      { id: "b", text: "Benjamin : Scooterını ne sıklıkla sürersin? Daniel : Bazen öğleden sonraları sürerim." }
    ],
    easyDistractor: "Benjamin : Scooterını ne sıklıkla sürersin? Daniel : Bazen sabahları sürerim.",
    correctOptionId: "a", // TODO: "a" veya "b"
    explanation: "",
    characterIds: ["daniel", "benjamin"],
    grades: [5, 6],
    functions: ["frequency_adverbs"],
    theme: "personal_life",
    evidenceStart: "0:02.015",
evidenceEnd: "0:04.158",
    evidenceSentence: "Daniel : I ride it /every afternoon/",
  },
{
    id: "5_personal_life_david_daniel",
    status: "published",
    videoSrc: "assets/video/5_personal_life_david_daniel.mp4",
    thumbnail: "0:07.051",
    title: "Daniel asks David about his holiday photos.",
    transcript: "Daniel : Are these your photos? David : Yes, I was 7 years old in that picture. Daniel : You were very cute",
    answerOptions: [
      { id: "a", text: "Daniel : Bunlar senin fotoğrafların mı? David : Evet, o fotoğrafta 12 yaşındaydım. Daniel : Çok şirinmişsin." },
      { id: "b", text: "Daniel : Bunlar senin fotoğrafların mı? David : Evet, o fotoğrafta /7/ yaşındaydım. Daniel : Çok şirinmişsin." }
    ],
    easyDistractor: "Daniel : Bunlar senin fotoğrafların mı? David : Evet, o fotoğrafta 7 yaşındaydım. Daniel : Çok uzunmuşsun.",
    correctOptionId: "b", // TODO: "a" veya "b"
    explanation: "",
    characterIds: ["david", "daniel"],
    grades: [5, 6],
    functions: ["possessive_adjective"],
    theme: "personal_life",
    evidenceStart: "0:02",
    evidenceEnd: "0:04.5",
    evidenceSentence: "Yes,I was /seven/ years old in that picture",
  },
{
    id: "5_personal_life_ella_chloe",
    status: "published",
    videoSrc: "assets/video/5_personal_life_ella_chloe.mp4",
    thumbnail: "0:05.178",
    title: "Ella asks Chloe about eating cupcakes for breakfast.",
    transcript: "Ella : Do you eat cupcakes for breakfast? Chloe : No, I /rarely/ eat /them/ in the morning.",
    answerOptions: [
      { id: "a", text: "Ella : Kahvaltıda cupcake yer misin? Chloe : Hayır, sabahları onu bazen yerim." },
      { id: "b", text: "Ella : Kahvaltıda cupcake yer misin? Chloe : Hayır, sabahları /onları nadiren/ yerim." }
    ],
    easyDistractor: "Ella : Kahvaltıda cupcake yer misin? Chloe : Hayır, onları sadece akşam yerim.",
    correctOptionId: "b", // TODO: "a" veya "b"
    explanation: "",
    characterIds: ["ella", "chloe"],
    grades: [5, 6],
    functions: ["frequency_adverbs","use_of_object_pronouns"],
    theme: "personal_life",
  evidenceStart: "0:02.314",
evidenceEnd: "0:05.711",
    evidenceSentence: "Chloe : No, I /rarely/ eat /them/ in the morning.",
  },
{
    id: "5_personal_life_emma_mia",
    status: "published",
    videoSrc: "assets/video/5_personal_life_emma_mia.mp4",
    thumbnail: "0:06.999",
    title: "Mia asks Emma about baking cookies.",
    transcript: "Mia : How often do you bake cookies? Emma : I usually bake on Sundays. Mia : What's that smell? Emma : Oh my god it is burning!",
    answerOptions: [
      { id: "a", text: "Mia : Ne sıklıkla kurabiye yaparsın? Emma : Genellikle /pazar/ günleri yaparım. Mia : Bu koku ne? Emma : Aman Tanrım, yanıyor!" },
      { id: "b", text: "Mia : Ne sıklıkla kurabiye yaparsın? Emma : Genellikle pazartesi günleri yaparım. Mia : Bu koku ne? Emma : Aman Tanrım, yanıyor!" }
    ],
    easyDistractor: "Mia : Ne sıklıkla kurabiye yaparsın? Emma : Genellikle pazar günleri yaparım. Mia : Bu koku ne? Emma : Aman Tanrım, fırın kapalı!",
    correctOptionId: "a", // TODO: "a" veya "b"
    explanation: "",
    characterIds: ["emma", "mia"],
    grades: [5, 6],
    functions: ["frequency_adverbs"],
    theme: "personal_life",
    evidenceStart: "0:02.243",
evidenceEnd: "0:04.299",
    evidenceSentence: "Emma : I usually bake on /Sundays/.",
  },
{
    id: "5_personal_life_olivia_chloe",
    status: "published",
    videoSrc: "assets/video/5_personal_life_olivia_chloe.mp4",
    thumbnail: "0:04.703",
    title: "Olivia asks Chloe about Luna's toy mouse.",
    transcript: "Olivia : Is that Luna's toy mouse? Chloe : Yes, it's her favorite toy.",
    answerOptions: [
      { id: "a", text: "Olivia : Bu Luna'nın oyuncağı mı? Chloe : Hayır, o benim en sevdiğim oyuncak." },
      { id: "b", text: "Olivia : Bu Luna'nın oyuncak faresi mi? Chloe : Evet, /onun/ en sevdiği oyuncak." }
    ],
    easyDistractor: "Olivia : Bu Luna'nın oyuncak faresi mi? Chloe : Hayır, onun en sevdiği oyuncak değil.",
    correctOptionId: "b", // TODO: "a" veya "b"
    explanation: "",
    characterIds: ["chloe", "olivia", "luna"],
    grades: [5, 6],
    functions: ["possessive_adjective"],
    theme: "personal_life",
    evidenceStart: "0:02.520",
evidenceEnd: "0:04.524",
    evidenceSentence: "Chloe : Yes, it's /her/ favorite toy.",
  },
{
    id: "5_personal_life_zoe_mia",
    status: "published",
    videoSrc: "assets/video/5_personal_life_zoe_mia.mp4",
    thumbnail: "0:06.589",
    title: "Mia asks Zoe about her telescope.",
    transcript: "Mia : Is this your telescope? Zoe : Yes, my father bought it. Mia : Can I use it? Zoe : sure",
    answerOptions: [
      { id: "a", text: "Mia : Bu senin teleskobun mu? Zoe : Evet, /babam/ aldı. Mia : Kullanabilir miyim? Zoe : Tabii." },
      { id: "b", text: "Mia : Bu senin teleskobun mu? Zoe : Evet, arkadaşım aldı. Mia : Kullanabilir miyim? Zoe : Tabii." }
    ],
    easyDistractor: "Mia : Bu senin teleskobun mu? Zoe : Evet, babam aldı. Mia : Kullanabilir miyim? Zoe : Hayır.",
    correctOptionId: "a", // TODO: "a" veya "b"
    explanation: "",
    characterIds: ["zoe", "mia"],
    grades: [5, 6],
    functions: ["possessive_adjective"],
    theme: "personal_life",
    evidenceStart: "0:02",
    evidenceEnd: "0:03",
    evidenceSentence: "Yes, /my father/ bought it",
  },
{
    id: "5_school_life_olivia_ella",
    status: "published",
    videoSrc: "assets/video/5_school_life_olivia_ella.mp4",
    thumbnail: "0:03.937",
    title: "Olivia asks Ella whether she is ready for the concert.",
    transcript: "Olivia : /Are you ready/ for the concert? Ella : Yes, I am, I'm really /excited/!",
    answerOptions: [
      { id: "a", text: "Olivia : Konser vakti geldi mi? Ella : Evet, öyle, Çok gerginim." },
      { id: "b", text: "Olivia : Konser için /hazır mısın/? Ella : Evet, Hazırım, Gerçekten /heyecanlıyım/!" }
    ],
    easyDistractor: "Olivia : Yarın için hazır mısın? Ella : Evet, Hazırım.",
    correctOptionId: "b", // TODO: "a" veya "b"
    explanation: "",
    characterIds: ["olivia", "ella"],
    grades: [5, 6],
    functions: ["asking_about_condition", "expressing_feelings"],
    theme: "School_life",
   evidenceStart: "0:00.479",
evidenceEnd: "0:04.598",
evidenceSentence: "Olivia : /Are you ready/ for the concert? Ella : Yes, I am, I'm really /excited/!",
  },
{
    id: "classroom_life_emma_david",
    status: "published",
    videoSrc: "assets/video/classroom_life_emma_david.mp4",
    thumbnail: "0:05.451",
    title: "Emma and David collect worksheets in the classroom.",
    transcript: "Emma : The worksheets /are/ fly/ing/ everywhere, David : I've got the last one!",
    answerOptions: [
      { id: "a", text: "Emma : Çalışma kağıtları dışarı uçtu, David : Sonuncusunu bende!" },
      { id: "b", text: "Emma : Çalışma kağıtları her yere uçuşu/yor/, David : Sonuncusu bende!" }
    ],
    easyDistractor: "Emma : Çalışma kağıtları her yere uçuşuyor! David : İlkini aldım!",
    correctOptionId: "b", // TODO: "a" veya "b"
    explanation: "",
    characterIds: ["emma", "david"],
    grades: [5, 6],
    functions: ["present_progressive"],
    theme: "Classroom_life",
    evidenceStart: "0:04.820",
evidenceEnd: "0:07.188",
    evidenceSentence: "Emma : The worksheets /are/ fly/ing/ everywhere,",
  },
{
    id: "countries_australia",
    status: "published",
    videoSrc: "assets/video/countries_australia.mp4",
    thumbnail: "0:06.080",
    title: "Ella introduces herself and shares a fact about Australia.",
    transcript: "Ella : Hi, I'm Ella, I/'m from Australia/, Australia is home to kangaroos and koalas!",
    answerOptions: [
      { id: "a", text: "Ella : Merhaba, Ben Ella, Avusturya'lıyım, Avustralya kanguruların ve koalaların ülkesidir!" },
      { id: "b", text: "Ella : Merhaba, Ben Ella, /Avustralya'danım/, Avustralya kanguruların ve koalaların ülkesidir!" }
    ],
    easyDistractor: "Ella : Merhaba, Ben Ella, Avustralya'danım, Avustralya kutup ayılarının ülkesidir!",
    correctOptionId: "b", // TODO: "a" veya "b"
    explanation: "",
    characterIds: ["ella"],
    grades: [5, 6],
    functions: ["introductions", "givinglocationinformation","countries"],
    theme: "introduction",
    evidenceStart: "0:01.502",
evidenceEnd: "0:02.642",
evidenceSentence: "I/'m from Australia/",
  },
{
    id: "countries_turkiye",
    status: "published",
    videoSrc: "assets/video/countries_turkiye.mp4",
    thumbnail: "0:06.080",
    title: "Mia introduces herself and shares a fact about Türkiye.",
    transcript: "Mia : Hi, I'm Mia, I'm from Türkiye, Türkiye is the only country in the /world/ on two continents!",
    answerOptions: [
      { id: "a", text: "Mia : Merhaba, Ben Mia, Türkiye'denim, Türkiye avrupada iki kıta üzerinde bulunan tek ülkedir!" },
      { id: "b", text: "Mia : Merhaba, Ben Mia, Türkiye'denim, Türkiye /dünyada/ iki kıta üzerinde bulunan tek ülkedir!" }
    ],
    easyDistractor: "Mia : Merhaba, Ben Mia, Türkiye'denim, Türkiye dünyada üç kıta üzerinde bulunan tek ülkedir!",
    correctOptionId: "b", // TODO: "a" veya "b"
    explanation: "",
    characterIds: ["mia"],
    grades: [5, 6],
    functions: ["introductions", "givinglocationinformation"],
    theme: "introduction",
    evidenceStart: "0:02.642",
evidenceEnd: null,
evidenceSentence: "Türkiye is the only country in the /world/ on two continents!",
  }



];

window.LEAGUE_OF_LISTENING_DIFFICULTY_DISTRACTORS = Object.freeze(
  Object.fromEntries(window.LEAGUE_OF_LISTENING_ITEMS.filter((item) => item.easyDistractor).map((item) => [item.id, Object.freeze({
    easy: item.easyDistractor,
    medium: item.answerOptions.find((option) => option.id !== item.correctOptionId)?.text || ""
  })]))
);

window.LEAGUE_OF_LISTENING_FUNCTIONS = Object.freeze({
  accepting: "Accepting",
  accepting: "Accepting",
  "agree-disagree": "Agreeing and Disagreeing",
  asking_about: "Asking about people, things, actions, time and ideas",
  asking_about_condition: "Asking About one's condition",
  asking_for_price: "Asking for price",
  asking_permission: "Asking Permission",
  asking_preferences_about_activities: "Asking Preferences About Activities",
  askingaboutlocation: "Asking About Location",
  askingaboutsomeone: "Asking About Someone",
  askingfordirections: "Asking for directions",
  askingforhelp: "Asking for Help",
  askinginformationabouttime: "Asking for Information About Time",
  confirming_information: "Confirming Information",
  correcting_behaviour: "Correcting Behaviour",
  countries: "Naming countries",
  describing_a_regular_habit: "Describing a Regular Habit",
  describing_physical_appearance: "Describing Physical Appearance",
  describing_roles: "Describing the responsibilities of different roles in the classroom",
  describing_study_routines: "Describing study routines",
  expressing_a_favorite_activity: "Expressing a Favorite Activity",
  expressing_a_preference: "Expressing a Preference",
  expressing_a_school_rule: "Expressing a School Rule",
  expressing_and_comparing_personal_preferences: "Expressing and Comparing Personal Preferences",
  expressing_feelings: "Expressing Feelings",
  expressing_hopes: "Expressing hopes",
  expressing_obligations_or_rules: "Expressing Obligations or Rules",
  expressing_prohibition: "Expressing Prohibition",
  expressingsurprise: "Expressing Surprise",
  expressingtime: "Time expressions",
  frequency_adverbs: "Frequency Adverbs",
  future_response_ill: "Future Response with 'will'",
  giving_a_warning: "Giving a Warning",
  giving_commands: "Imperatives : Giving Commands",
  givingdirections: "Giving directions",
  givinginformation: "Giving Information",
  givinglocationinformation: "Giving Location Information",
  imperatives: "Giving Instructions",
  introductions: "Introducing Yourself",
  makingasuggestion: "Making a Suggestion",
  makingrequests: "Making Requests",
  numbers: "Numbers",
  offeringhelp: "Offering Help",
  ordering_something: "Ordering something",
  permission: "Asking for and Giving Permission",
  possessive_adjective: "Possessive Adjective",
  present_progressive: "Present Progressive Tense",
  present_progressive_vs_present_simple: "Use of Present Progressive vs Present Simple",
  refusing: "Refusing",
  responding_appropriately: "Responding Appropriately",
  suggesting: "Making Suggestions",
  tag_questions: "Tag questions",
  talking_about_hobbies: "Talking about hobbies",
  telling_time: "Telling time",
  use_of_modals_mustnt_and_cant_prohibition: "Use of Modals Mustn't and Can't (Prohibition)",
  use_of_object_pronouns: "Use of Object Pronouns",
  use_of_simple_present_tense: "Use of the Simple Present Tense",
  use_of_simple_present_tense_for_habbits: "Use of the Simple Present Tense For Habits",
  use_of_there_is_there_are: "Use of There Is/There Are",
  use_of_to_be_for_time: "Use of To Be for Time",
  use_of_to_be_present: "Use of To Be Present",
  use_of_wh_questions_what_time: "Use of Wh- Questions (What Time)",
  use_of_wh_questions_who_what: "Use of Wh- Questions (Who, What)",
});
