/*
 * Vocab Presenter Turkish adapter
 *
 * Direct Turkish equivalents for every unique grade 6, 7 and 8 answer in
 * word_master/questions.js. Grade 0 special categories are intentionally excluded.
 * Turkish definitions are never used.
 */
(function () {
  "use strict";

  const TRANSLATIONS = {
    "2 MONTHS AGO": "2 AY ÖNCE",
    "ABROAD": "YURT DIŞI",
    "ACCEPT": "KABUL ETMEK",
    "ACCESS": "ERİŞİM",
    "ACCIDENT": "KAZA",
    "ACCOMMODATION": "KONAKLAMA",
    "ACCOUNT": "HESAP",
    "ACHIEVE": "BAŞARMAK",
    "ACHIEVEMENT": "BAŞARI",
    "ACTRESS": "AKTRİS",
    "ADD": "EKLEMEK",
    "ADDICTION": "BAĞIMLILIK",
    "ADOPT": "EVLAT EDİNMEK",
    "ADVENTURE": "MACERA",
    "ADVENTUROUS": "MACERAci",
    "AFRAID": "KORKMUŞ",
    "AFTER": "SONRA",
    "AFTER THAT": "ONDAN SONRA",
    "AFTERNOON": "ÖĞLEDEN SONRA",
    "AGREE": "KATILMAK",
    "AIRPORT": "HAVALİMANI",
    "ALIEN": "UZAYLI",
    "ALL-INCLUSIVE": "HER ŞEY DAHİL",
    "ALLOWANCE": "HARÇLIK",
    "ALONE": "YALNIZ",
    "ALWAYS": "HER ZAMAN",
    "AMAZING": "ŞAŞIRTICI",
    "AMPHIBIAN": "İKİYASAMLI",
    "AMUSEMENT PARK": "EĞLENCE PARKI",
    "AMUSING": "EĞLENCELİ",
    "ANCIENT": "ANTİK / ESKİ",
    "ANGRY": "KIZGIN",
    "ANNOYED": "SİNİRLİ / RAHATSIZ",
    "ANSWER": "CEVAP VERMEK",
    "ANXIOUS": "ENDİŞELİ / GERGİN",
    "APOLOGIZE": "ÖZÜR DİLEMEK",
    "APPEAR": "GÖRÜNMEK",
    "APPEARANCE": "GÖRÜNÜŞ",
    "APPLICATION": "UYGULAMA",
    "APPOINTMENT": "RANDEVU",
    "ARCHERY": "OKÇULUK",
    "ARCHITECT": "MİMAR",
    "ARCHITECTURE": "MİMARİ",
    "ARGUE": "TARTIŞMAK",
    "ARRANGE": "DÜZENLEMEK",
    "ARRIVE ON TIME": "ZAMANINDA GELMEK",
    "ARRIVE SCHOOL": "OKULA VARMAK",
    "ARROGANT": "KİBİRLİ",
    "ART GALLERY": "SANAT GALERİSİ",
    "ASTEROID": "GÖKTAŞI",
    "AT THE MOMENT": "ŞU ANDA",
    "ATTACHMENT": "EK DOSYA",
    "ATTACK": "SALDIRMAK",
    "ATTEND": "KATILMAK",
    "ATTEND COURSE": "KURSA GİTMEK",
    "ATTRACTION": "TURİSTİK YER",
    "ATTRACTIVE": "ÇEKİCİ",
    "AUTHOR": "YAZAR",
    "AUTUMN": "SONBAHAR",
    "AVAILABLE": "MÜSAİT",
    "AWARD": "ÖDÜL",
    "AWESOME": "MUHTEŞEM",
    "AWFUL": "KORKUNÇ / BERBAT",
    "BACK UP": "DESTEKLEMEK",
    "BAD": "KÖTÜ",
    "BAD LINE": "KÖTÜ BAĞLANTI",
    "BAD LUCK": "KÖTÜ ŞANS",
    "BAGEL": "SİMİT",
    "BAKE": "FINDA PİŞİRMEK",
    "BAKED": "FIRINLANMIŞ",
    "BAKER": "FIRINICI",
    "BAKERY": "PASTANE / FIRIN",
    "BAKING POWDER": "KABARTMA TOZU",
    "BAKING TRAY": "FIRIN TEPSİSİ",
    "BALANCE": "DENGE",
    "BALD": "KEL",
    "BEACH": "PLAJ",
    "BEANS": "FASULYE",
    "BEARD": "SAKAL",
    "BEAT": "YENMEK",
    "BEAUTIFUL": "GÜZEL",
    "BEFORE": "ÖNCE",
    "BEGINNER": "YENİ BAŞLAYAN",
    "BEHIND": "ARKASINDA",
    "BELIEVE": "İNANMAK",
    "BEST FRIEND": "EN İYİ ARKADAŞ",
    "BETTER": "DAHA İYİ",
    "BETWEEN": "ARASINDA",
    "BEVERAGE": "İÇECEK",
    "BIG": "BÜYÜK",
    "BIRTHDAY": "DOĞUM GÜNÜ",
    "BITTER": "ACI",
    "BLOND": "SARIŞIN",
    "BOIL": "KAYNATMAK",
    "BOILED": "HAŞLANMIŞ",
    "BOOK A ROOM": "ODA AYIRTMAK",
    "BOOK SHELF": "KİTAP RAFI",
    "BOOKSHOP": "KİTAPÇI",
    "BOOTS": "ÇİZME",
    "BORED": "SIKILMIŞ",
    "BORING": "SIKI",
    "BORN": "DOĞMAK",
    "BORROW": "ÖDÜNÇ ALMAK",
    "BOWL": "KASE",
    "BRAVE": "CESUR / KORKUSUZ",
    "BREAD": "EKMEK",
    "BREAK": "KIRMAK",
    "BREAKFAST": "KAHVALTI",
    "BRIDGE": "KÖPRÜ",
    "BRIGHT": "PARLAK",
    "BRILLIANT": "DAHİ / PARLAK",
    "BRING": "GETİRMEK",
    "BROWSE": "İNTERNETTE GEZMEK",
    "BROWSER": "İNTERNET TARAYICI",
    "BRUSH TEETH": "DİŞ FIRCALAMAK",
    "BUDDY": "YAKIN ARKADAŞ",
    "BUILDING": "BİNA",
    "BUMPER CAR": "ÇARPIŞAN ARABA",
    "BUNGEE JUMPING": "BUNJİ ATLAMA",
    "BUSINESSMAN": "İŞ ADAMI",
    "BUSY": "MEŞGUL",
    "BUTCHER": "KASAP",
    "BUTTER": "TEREYAĞI",
    "BUTTON": "TUŞ / DÜĞME",
    "BUY": "SATIN ALMAK",
    "CAGE": "KAFES",
    "CALL": "ARAMAK",
    "CALL CENTER": "ÇAĞRI MERKEZİ",
    "CAMPAIGN": "KAMPANYA",
    "CAMPING": "KAMP YAPMA",
    "CANDLE": "MUM",
    "CANOEING": "KANO",
    "CAPITAL": "BAŞKENT",
    "CAREER": "KARİYER",
    "CARING": "SEVECen",
    "CARNIVAL": "KARNAVAL",
    "CARNIVORE": "ETÇİL",
    "CARROUSEL": "ATLIKARÜSEL",
    "CARTOON": "ÇİZGİ FİLM",
    "CASTLE": "KALE",
    "CASUAL": "GÜNLÜK GİYİM",
    "CAVING": "MAĞARA GEZİSİ",
    "CELEBRATE": "KUTLAMAK",
    "CELL PHONE": "CEP TELEFONU",
    "CEMETERY": "MEZARLIK",
    "CEREAL": "TAHIL GEVREĞİ",
    "CHALLENGING": "ZORLU",
    "CHEAP": "UCUZ",
    "CHEERFUL": "NEŞELİ",
    "CHEESE": "PEYNİR",
    "CHEF": "ŞEF AŞÇI",
    "CHEMICAL": "KİMYASAL",
    "CHEMIST": "KİMYAGER",
    "CHILLY": "SERİN / SOĞUK",
    "CHOP": "DOĞRAMAK",
    "CHURCH": "KİLİSE",
    "CIRCUS": "SİRK",
    "CITY": "ŞEHİR",
    "CITY HALL": "BELEDİYE BİNASI",
    "CIVILIZATION": "MEDENİYET",
    "CLAW": "PENÇE",
    "CLEAN": "TEMİZ",
    "CLEAN WINDOWS": "PENCERE SİLMEK",
    "CLEVER": "ZEKI",
    "CLIFF": "UÇURUM",
    "CLIMATE": "İKLİM",
    "CLOCK": "SAAT",
    "CLOSE FRIEND": "YAKIN ARKADAŞ",
    "CLOWN": "PALYAÇO",
    "CLUMSY": "SAKAR",
    "COAST": "KIYILAR",
    "COFFEE": "KAHVE",
    "COFFEE SHOP": "KAFE",
    "COLD": "SOĞUK",
    "COME BACK HOME": "EVE DÖNMEK",
    "COME OVER": "UĞRAMAK",
    "COMEDY": "KOMEDİ",
    "COMET": "KUYRUKLU YILDIZ",
    "COMFORTABLE": "RAHAT",
    "COMMENT": "YORUM",
    "COMMERCIAL": "REKLAM",
    "COMMUNICATION": "İLETİŞİM",
    "COMPANY": "ŞİRKET",
    "COMPARE": "KARŞILAŞTIRMAK",
    "COMPETE": "REKABET ETMEK",
    "COMPLAIN": "ŞİKAYET ETMEK",
    "COMPOSE": "BESTELEMEK",
    "COMPUTER TOWER": "BİLGİSAYAR KASASI",
    "CONCERT HALL": "KONSER SALONU",
    "CONFIRM": "ONAYLAMAK",
    "CONNECT": "BAĞLANMAK",
    "CONNECTION": "BAĞLANTI",
    "CONTACT": "İLETİŞİME GEÇMEK",
    "CONVERSATION": "KONUŞMA",
    "COOK": "YEMEK PİŞİRMEK",
    "COOKERY": "YEMEK PİŞİRME",
    "COOL": "HAVALİ",
    "COOPERATE": "İŞBİRLİĞİ YAPMAK",
    "COTTON CANDY": "PAMUK ŞEKER",
    "COUCH POTATO": "TV BAĞIMLISI",
    "COUNT ON": "GÜVENMEK",
    "COUNTRY LIFE": "KIRSAL HAYAT",
    "COUNTRYSIDE": "KIRSAL",
    "CRACK": "KIRMAK",
    "CREATE": "OLUŞTURMAK",
    "CREATURE": "YARATIK",
    "CREW": "MÜRETTEBAT",
    "CROISSANT": "KROİSAN",
    "CROSS": "KARŞIYA GEÇMEK",
    "CROWDED": "KALABALİK",
    "CUCUMBER": "SALATALIK",
    "CUISINE": "MUTFAK",
    "CUP": "BARDAK",
    "CURE DISEASE": "HASTALIĞI İYİLEŞTİRMEK",
    "CURLY": "KIVIRCIK",
    "CURRENCY": "PARA BİRİMİ",
    "CUSTOMER": "MÜŞTERİ",
    "CUT": "KESMEK",
    "DAILY ROUTINE": "GÜNLÜK RUTİN",
    "DANGEROUS": "TEHLİKELİ",
    "DATE": "TARİH",
    "DATE OF BIRTH": "DOĞUM TARİHİ",
    "DEACTIVATE": "DEVRE DIŞI BIRAKMAK",
    "DEADLINE": "SON TARİH",
    "DEBATE": "TARTIŞMA",
    "DECIDE": "KARAR VERMEK",
    "DECORATE": "SÜSLEMEK",
    "DEFEAT": "YENMEK",
    "DEFINITELY": "KESİNLİKLE",
    "DEFORESTATION": "ORMANSIZLAŞMA",
    "DEGREE": "DERECE",
    "DELETE": "SİLMEK",
    "DELICIOUS": "LEZZETLİ",
    "DENTIST": "DİŞ HEKİMİ",
    "DEPEND ON": "BAĞIMLI OLMAK",
    "DESERT": "ÇÖL",
    "DESKTOP": "MASAÜSTÜ BİLGİSAYAR",
    "DESTINATION": "GİDİLECEK YER",
    "DESTROY": "YOK ETMEK",
    "DETERMINED": "KARARLI",
    "DEVICE": "CİHAZ",
    "DIAL": "NUMARA ÇEVİRMEK",
    "DICE": "KÜÇÜK KUPLER KES",
    "DICTIONARY": "SÖZLÜK",
    "DIED": "ÖLDÜ",
    "DIFFICULT": "ZOR",
    "DINNER": "AKŞAM YEMEĞİ",
    "DIRECTOR": "YÖNETMEN",
    "DIRTY": "KİRLİ",
    "DISAGREE": "KATILMAMAK",
    "DISAPPOINTING": "HAYAl KIRIKLIGI",
    "DISCOVER": "KEŞFETMEK",
    "DISCUSSION": "TARTIŞMA",
    "DISH": "YEMEK",
    "DO HOMEWORK": "ÖDEV YAPMAK",
    "DO IRONING": "ÜTÜ YAPMAK",
    "DO LAUNDRY": "ÇAMAŞIR YIKAMAK",
    "DO SHOPPING": "ALIŞVERİŞ YAPMAK",
    "DOCTOR": "DOKTOR",
    "DOCUMENTARY": "BELGESEL",
    "DOING CHORES": "EV İŞİ YAPMAK",
    "DONATE": "BAĞIŞ YAPMAK",
    "DOWNLOAD": "İNDİRMEK",
    "DOWNTOWN": "ŞEHİR MERKEZİ",
    "DRAW": "BERABERLİK",
    "DREAM": "RÜYA",
    "DRIVER": "ŞOFÖR",
    "DROUGHT": "KURAKLIK",
    "DRY DISHES": "BULAŞIK KURULAMAK",
    "DULL": "NEŞESİZ",
    "DUST FURNITURE": "MOBİLYA SİLMEK",
    "DUST SHELVES": "RAF SİLMEK",
    "DUTY": "GÖREV",
    "DWARF": "CÜCE",
    "EAGER": "İSTEKLİ",
    "EARTH": "DÜNYA",
    "EASYGOING": "UYUMLU",
    "ECO-FRIENDLY": "ÇEVRE DOSTU",
    "EDUCATION": "EĞİTİM",
    "EDUCATIONAL": "EĞİTİCİ",
    "EFFICIENT": "VERİMLİ",
    "EGG": "YUMURTA",
    "EMBARRASSING": "UTANDIRICI",
    "EMOTION": "DUYGU",
    "ENDANGERED": "TEHLİKE ALTINDA",
    "ENERGETIC": "ENERJİK",
    "ENGAGED": "MEŞGUL",
    "ENGINEER": "MÜHENDİS",
    "ENJOY": "ZEVK ALMAK",
    "ENJOYABLE": "EĞLENCELİ",
    "ENORMOUS": "DEV GİBİ",
    "ENTERTAINING": "EĞLENCELİ",
    "ENTRANCE FEE": "GİRİŞ ÜCRETİ",
    "ENVIRONMENT": "ÇEVRE",
    "EPISODE": "BÖLÜM",
    "EQUIPMENT": "EKİPMAN",
    "ERASE": "SİLMEK",
    "EVENING": "AKŞAM",
    "EVENT": "ETKİNLİK",
    "EVERY DAY": "HER GÜN",
    "EVIDENCE": "KANIT",
    "EXAMINE": "MUAYENE ETMEK",
    "EXCELLENT": "MÜKEMMEL",
    "EXCITED": "HEYECANLI",
    "EXCITING": "HEYECANLI",
    "EXHIBITION": "SERGİ",
    "EXIT": "ÇIKIŞ",
    "EXPECT": "BEKLEMEK",
    "EXPENSIVE": "PAHALI",
    "EXPERIENCED": "DENEYİMLİ",
    "EXPERIMENT": "DENEY",
    "EXPLORE": "KEŞFETMEK",
    "EXTINCT": "NESLİ TÜKENMİŞ",
    "EXTRAORDINARY": "OLAĞANÜSTÜ",
    "FABULOUS": "HARİKA",
    "FACE TO FACE": "YÜZYÜZE",
    "FAIR": "PANAYIR",
    "FALL": "SONBAHAR",
    "FAMOUS": "ÜNLÜ",
    "FANCY DRESS": "KOSTÜM",
    "FANTASTIC": "HARİKA",
    "FAREWELL": "VEDA",
    "FARM": "ÇİFTLİK",
    "FARMER": "ÇİFTÇİ",
    "FASCINATING": "BÜYÜLEYİCİ",
    "FASHIONABLE": "MODALİ",
    "FAST": "HIZLI",
    "FEARLESS": "CESUR / KORKUSUZ",
    "FEATHER": "TÜY",
    "FEED": "BESLEMEK",
    "FEED PET": "EVCİL HAYVANI BESLEMEK",
    "FEEL": "HİSSETMEK",
    "FERRIS WHEEL": "DÖNME DOLAP",
    "FEWER": "DAHA AZ",
    "FINALLY": "SONUNDA",
    "FINISH": "BİTİRMEK",
    "FIRE STATION": "İTFAİYE İSTASYONU",
    "FIREFIGHTER": "İTFAİYECİ",
    "FIREWORK": "HAVAİ FİŞEK",
    "FIRST": "İLK",
    "FIX": "TAMİR ETMEK",
    "FLAT": "DAİRE",
    "FLIGHT": "UÇUŞ",
    "FLORIST": "ÇİÇEKÇİ",
    "FLOUR": "UN",
    "FLOWER": "ÇİÇEK",
    "FOGGY": "SİSLİ",
    "FOLD CLOTHES": "ÇAMAŞIR KATLAMAK",
    "FOLDER": "KLASÖR",
    "FOLLOW": "TAKİP ETMEK",
    "FOND OF": "SEVMEK",
    "FOREST": "ORMAN",
    "FORGETFUL": "UNUTKAN",
    "FORK": "ÇATAL",
    "FORMAL OUTFIT": "RESMİ KIYAFEt",
    "FOUNTAIN": "FIŞKIYE / ÇEŞME",
    "FREE TIME": "BOŞ ZAMAN",
    "FREEZER": "DERİN DONDURUCU",
    "FREEZING": "BUZ GİBİ SOĞUK",
    "FRESH FRUIT": "TAZE MEYVE",
    "FRIDGE": "BUZDOLABI",
    "FRIED": "KIZARTILMIŞ",
    "FRIENDLY": "ARKADAŞ CANLISI",
    "FRIENDSHIP": "ARKADAŞLIK",
    "FRIGHTENING": "KORKUTUCU",
    "FROZEN": "DONMUŞ",
    "FRUIT JUICE": "MEYVE SUYU",
    "FRY": "KIZARTMAK",
    "FUN": "EĞLENCELİ",
    "FUNFAIR": "LUNAPARK",
    "FUR": "KÜRK",
    "FUTURE": "GELECEK",
    "GARBAGE": "ÇÖP",
    "GARLIC": "SARIMSAK",
    "GENEROUS": "CÖMERT",
    "GET DRESSED": "GİYİNMEK",
    "GET ENGAGED": "NİŞANLANMAK",
    "GET IN TOUCH": "İLETİŞİME GEÇMEK",
    "GET MARRIED": "EVLENMEK",
    "GET ON WELL": "İYİ GEÇİNMEK",
    "GHOST TRAIN": "HAYALET TRENİ",
    "GIANT": "DEV",
    "GINGER": "ZENCEFİL",
    "GLASSES": "GÖZLÜK",
    "GLOVES": "ELDİVEN",
    "GO ON A DIET": "DİYETE GİRMEK",
    "GO ONLINE": "İNTERNETE GİRMEK",
    "GO SHOPPING": "ALIŞVERİŞE GİTMEK",
    "GO TO GYM": "SPOR SALONUNA GİTMEK",
    "GOAL KEEPER": "KALECI",
    "GOGGLES": "YÜZÜCÜ GÖZLÜĞÜ",
    "GOOD": "İYİ",
    "GOOD LUCK": "İYİ ŞANSLAR",
    "GOVERNORSHIP": "VALİLİK",
    "GRADUATE": "MEZUN OLMAK",
    "GRATER": "RENDE",
    "GRAVITY": "YERÇEKİMİ",
    "GREASY": "YAĞLI",
    "GREENGROCER": "MANAV",
    "GREENHOUSE": "SERA",
    "GRILL": "IZGARA YAPMAK",
    "GRILLED": "IZGARADA PİŞİRİLMİŞ",
    "GROCER": "BAKKAL",
    "GROW UP": "BÜYÜMEK",
    "GUESS": "TAHMİN ETMEK",
    "GUEST": "MİSAFİR",
    "GUEST LIST": "MİSAFİR LİSTESİ",
    "GUEST TEAM": "MİSAFİR TAKIM",
    "HABIT": "ALIŞKANLIK",
    "HABITABLE": "YAŞANILABİLİR",
    "HABITAT": "YAŞAM ALANI",
    "HAILING": "DOLU YAĞIYOR",
    "HAIRDRESSER": "KUAFÖR",
    "HALF PAST": "BUÇUK",
    "HALLOWEEN": "CADILLAR BAYRAMI",
    "HANDSOME": "YAKIŞIKLI",
    "HANG GLIDING": "YELKEN KANAT",
    "HANG ON": "BEKLEMEK",
    "HANG UP": "TELEFONU KAPATMAK",
    "HAPPY": "MUTLU",
    "HARD": "ZOR",
    "HARDLY EVER": "NEREDEYSE HİÇ",
    "HARDWORKING": "ÇALIŞKAN",
    "HARM": "ZARAR VERMEK",
    "HARMFUL": "ZARARLI",
    "HAVE A REST": "DİNLENMEK",
    "HAVE BATH": "BANYO YAPMAK",
    "HEADPHONES": "KULAKLIK",
    "HEALTH": "SAĞLIK",
    "HEALTHY": "SAĞLIKLI",
    "HEAT": "ISITMAK",
    "HELI-SKIING": "HELİKOPTER KAYAĞI",
    "HELMET": "KASK",
    "HELPFUL": "YARDIMCI",
    "HERBIVORE": "OTÇİL",
    "HIGH": "YÜKSEK",
    "HIKING": "DOĞA YÜRÜYÜŞÜ",
    "HISTORIC SITE": "TARİHİ YER",
    "HOLD ON": "BEKLEMEK",
    "HOLD THE LINE": "HATTA BEKLEMEK",
    "HOLIDAY": "TATİL",
    "HOME TEAM": "EV SAHİBİ TAKIM",
    "HOMETOWN": "MEMLEKET",
    "HONEST": "DÜRÜST",
    "HONEY": "BAL",
    "HOOP": "ÇEMBER",
    "HOPE": "UMUT",
    "HORN": "BOYNUZ",
    "HORRIBLE": "KORKUNÇ / BERBAT",
    "HORROR": "KORKU",
    "HOSPITAL": "HASTANE",
    "HOST": "EV SAHİBİ",
    "HOT": "SICAK",
    "HOUSEWIFE": "EV KADINI",
    "HOUSEWORK": "EV İŞİ",
    "HOW OFTEN": "NE SIKLIKTA",
    "HUMAN": "İNSAN",
    "HUNGRY": "AÇ",
    "HUNT": "AV YAPMAK",
    "IMAGINE": "HAYAL ETMEK",
    "IMPORTANT": "ÖNEMLİ",
    "IMPRESSIVE": "ETKİLEYİCİ",
    "INCREASE": "ARTMAK",
    "INCREDIBLE": "İNANILMAZ",
    "INDIVIDUAL": "BİREYSEL",
    "INDOOR": "KAPALI ALAN",
    "INFORM": "BİLGİLENDİRMEK",
    "INGREDIENT": "MALZEME",
    "INJURY": "SAKATLK",
    "INSECT": "BÖCEK",
    "INSTALL": "YÜKLEMEK",
    "INSTRUCTOR": "EĞİTMEN",
    "INTELLIGENT": "ZEKI",
    "INTERACTION": "ETKİLEŞİM",
    "INTERESTED IN": "İLGİLENMEK",
    "INTERESTING": "İLGİNÇ",
    "INVENT": "İCAT ETMEK",
    "INVENTION": "İCAT",
    "INVITATION": "DAVET",
    "INVITE": "DAVET ETMEK",
    "ISLAND": "ADA",
    "IVORY": "FİL DİŞİ",
    "JAM": "REÇEL",
    "JEALOUS": "KISKANÇI",
    "JOGGING": "KOŞU",
    "JOIN": "KATILMAK",
    "JOURNEY": "YOLCULUK",
    "JUNGLE": "TROPIKAL ORMAN",
    "JUNK FOOD": "ABUR CUBUR",
    "KAYAKING": "KANO / KAYAK",
    "KEEN ON": "HEVESLİ OLMAK",
    "KEEP IN TOUCH": "İLETİŞİMDE KALMAK",
    "KEEP QUIET": "SESSIZ OLMAK",
    "KEEP SECRET": "SIR SAKLAMAK",
    "KEY": "TUŞ / DÜĞME",
    "KEYBOARD": "KLAVYE",
    "KIOSK": "BÜFE",
    "KNIFE": "BÇAK",
    "LAID BACK": "SAKİN / RAHAT",
    "LAKE": "GÖL",
    "LAND": "İNMEK",
    "LANDMARK": "SİMGE YAPI",
    "LARGE": "BÜYÜK",
    "LAST WEEK": "GEÇEN HAFTA",
    "LAUNCH": "FIRLATMAK",
    "LAWYER": "AVUKAT",
    "LAZY": "TEMBEL",
    "LEAVE MESSAGE": "MESAJ BIRAKMAK",
    "LEND": "ÖDÜNÇ VERMEK",
    "LIBRARY": "KÜTÜPhane",
    "LIFE": "HAYAT",
    "LIFE FORM": "YAŞAM FORMU",
    "LIGHT BULB": "AMPUL",
    "LIGHTNING": "ŞIMŞEK",
    "LINE": "SIRA",
    "LINK": "BAĞLANTI / LİNK",
    "LOCAL FOOD": "YÖRESEL YEMEK",
    "LOCATION": "KONUM",
    "LOG IN": "GİRİŞ YAPMAK",
    "LOG OFF": "ÇIKIŞ YAPMAK",
    "LOG ON": "GİRİŞ YAPMAK",
    "LOG OUT": "ÇIKIŞ YAPMAK",
    "LONG": "UZUN",
    "LOSE": "KAYBETMEK",
    "LOW": "ALÇAK",
    "LUCKY": "ŞANSLI",
    "LUNCH": "ÖĞLE YEMEĞİ",
    "MAGAZINE": "DERGİ",
    "MAGICIAN": "SİHİRBAZ",
    "MAGNIFICENT": "GÖRKEMLİ",
    "MAJESTIC": "GÖRKEMLİ",
    "MAKE AN EXCUSE": "BAHANE ÜRETMEK",
    "MAKE BED": "YATAK TOPLAMAK",
    "MANAGER": "YÖNETİCİ",
    "MAP": "HARİTA",
    "MARRIAGE": "EVLİLİK",
    "MASH": "EZMEK",
    "MEAL": "ÖĞÜN",
    "MEAN": "KÖTÜ KALPLİ",
    "MEAT": "ET",
    "MECHANIC": "TAMİRCİ",
    "MEDICINE": "İLAÇ",
    "MEET FRIENDS": "ARKADAŞLARLA BULUŞMAK",
    "MELT": "ERİMEK",
    "MEMO": "NOT",
    "MESSENGER BIRD": "GÜVERCİN İLE MESAJ",
    "MESSY": "DAĞINIK / KİRLİ",
    "METEOR SHOWER": "METEORİT YAĞMURU",
    "MIDDLE AGED": "ORTA YAŞLI",
    "MILD": "ILIMAN",
    "MILK": "SÜT",
    "MILKY": "SÜTLÜ",
    "MISSION": "GÖREV",
    "MITTENS": "KAR ELDİVENİ",
    "MIX": "KARISTIRMAK",
    "MOBILE": "CEP TELEFONU",
    "MONSTER": "CANAVAR",
    "MONUMENT": "ANIT",
    "MOODY": "HUYSUZ / DEĞİŞKEN",
    "MOON": "AY",
    "MOP THE FLOOR": "PASPAS ÇEKMEK",
    "MORNING": "SABAH",
    "MOSQUE": "CAMİ",
    "MOTOR RACING": "MOTOR YARIŞI",
    "MOUNTAIN": "DAĞ",
    "MOUSTACHE": "BIYIK",
    "MOVE": "TAŞINMAK",
    "MOVIE": "FİLM",
    "MOVIE THEATER": "SİNEMA",
    "MOW LAWN": "ÇİMEN BİÇMEK",
    "MUFFIN": "MAFİN",
    "MUNICIPALITY": "BELEDİYE",
    "MUSEUM": "MÜZE",
    "MUSIC BAND": "MÜZİK GRUBU",
    "MYSTERIOUS": "GİZEMLİ",
    "NATURE": "DOĞA",
    "NEARLY": "NEREDEYSE",
    "NEAT": "DÜZENLİ",
    "NECESSARY": "GEREKLİ",
    "NEIGHBORHOOD": "MAHALLE",
    "NERD": "KİTAP KURDU",
    "NERVOUS": "GERGİN / ENDİŞELİ",
    "NEVER": "HİÇBİR ZAMAN",
    "NEWS": "HABER",
    "NEWSAGENT": "GAZETE BAYİİ",
    "NEWSPAPER": "GAZETE",
    "NEXT": "SONRA / SONRAKİ",
    "NEXT TO": "YANINDA",
    "NICKNAME": "TAKMAİSİM",
    "NIGHT": "GECE",
    "NOISY": "GÜRÜLTÜLÜ",
    "NOVEL": "ROMAN",
    "NOW": "ŞİMDİ",
    "NURSE": "HEMŞİRE",
    "NUTRITIOUS": "BESLEYİCİ",
    "O CLOCK": "TAM (SAAT)",
    "OAT": "YULAF",
    "OBEY THE RULES": "KURALLARA UYMAK",
    "OBLIGATION": "YÜKÜMLÜLÜK",
    "OBSERVE": "GÖZLEMLEMEK",
    "OCCUPATION": "MESLEK",
    "OCEAN": "OKYANUS",
    "OFFER": "TEKLİF ETMEK",
    "OFFLINE": "ÇEVRİMDIŞI",
    "OFTEN": "SIKLIKLA",
    "OILY": "YAĞLI",
    "OLIVES": "ZEYTİN",
    "OMELETTE": "OMLET",
    "OMNIVORE": "HEPÇİL",
    "ONCE": "BİR KEZ",
    "ONION": "SOĞAN",
    "ONLINE": "ÇEVRİMİÇİ",
    "OPINION": "GÖRÜŞ",
    "OPPOSITE": "KARŞISINDA",
    "ORBIT": "YÖRÜNGE",
    "ORDER": "SİPARİŞ VERMEK",
    "ORGANIZE": "DÜZENLEMEK",
    "OUT OF ORDER": "BOZUK",
    "OUTDOOR": "AÇIK ALAN",
    "OUTGOING": "GİRİŞKEN",
    "OVEN": "FIRIN",
    "OVER": "ÜSTÜNDE",
    "OVERWEIGHT": "KİLOLU",
    "OZONE LAYER": "OZON TABAKASI",
    "PALACE": "SARAY",
    "PAN": "TAVA",
    "PANCAKE": "KREP",
    "PARADE": "GEÇİT TÖRENİ",
    "PARAGLIDING": "YAMAÇ PARAŞÜTÜ",
    "PARTLY CLOUDY": "PARÇALI BULUTLU",
    "PASSWORD": "ŞİFRE",
    "PASTA": "MAKARNA",
    "PAY BILLS": "FATURA ÖDEMEK",
    "PEACEFUL": "HUZURLU",
    "PEEL": "SOYMAK",
    "PEPPER": "BİBER",
    "PERSONALITY": "KİŞİLİK",
    "PESTICIDE": "BÖCEK İLACI",
    "PHARMACY": "ECZANE",
    "PICK FRUIT": "MEYVE TOPLAMAK",
    "PICK UP": "TELEFONU AÇMAK",
    "PLACE": "YER",
    "PLANE": "UÇAK",
    "PLANET": "GEZEGEN",
    "PLATE": "TABAK",
    "PLAY GAMES": "OYUN OYNAMAK",
    "PLAYGROUND": "OYUN PARKI",
    "PLEASANT": "HOŞ / GÜZEL",
    "PLUMP": "TOMBUL",
    "POCKET MONEY": "HARÇLIK",
    "POETRY": "ŞİİR",
    "POISONOUS": "ZEHİRLİ",
    "POLICE STATION": "POLİS KARAKOLU",
    "POLITE": "NAZIK",
    "POLLUTE": "KİRLETMEK",
    "POOL": "HAVUZ",
    "POPULATION": "NÜFUS",
    "POST": "PAYLAŞMAK",
    "POST OFFICE": "POSTANE",
    "POTATO": "PATATES",
    "POUR": "DÖKMEK",
    "PRECAUTION": "ÖNLEM",
    "PREDICT": "TAHMİN ETMEK",
    "PREFER": "TERCİH ETMEK",
    "PREFERENCE": "TERCİH",
    "PREPARE": "HAZIRLAMAK",
    "PREPARE MEAL": "YEMEK HAZIRLAMAK",
    "PRESENT": "HEDİYE",
    "PREVENT": "ÖNLEMEK",
    "PREY": "AV",
    "PRINTER": "YAZICI",
    "PRIVACY": "GİZLİLİK",
    "PRIVATE": "ÖZEL",
    "PRIZE": "ÖDÜL",
    "PROBABLY": "MUHTEMELEN",
    "PROFESSION": "MESLEK",
    "PROOF": "KANIT",
    "PROTECT": "KORUMAK",
    "PROVINCE": "İL / VİLAYET",
    "PUBLIC": "HERKESE AÇIK",
    "PUNCTUAL": "DAKİK",
    "QUARTER PAST": "ÇEYREĞİ GEÇİYOR",
    "QUESTIONNAIRE": "ANKET",
    "QUEUE": "KUYRUK",
    "QUIET": "SAKİN",
    "QUIZ SHOW": "YARIŞMA PROGRAMI",
    "RAFTING": "RAFTİNG",
    "RAINCOAT": "YAĞMURLUK",
    "RAINY": "YAĞMURLU",
    "RAISE KIDS": "ÇOCUK YETİŞTİRMEK",
    "RAPIDLY": "HIZLA",
    "RARELY": "NADİREN",
    "READ BOOK": "KİTAP OKUMAK",
    "REALITY SHOW": "REALİTE PROGRAMI",
    "RECEIVE": "ALMAK",
    "RECEIVER": "ALAN KİŞİ",
    "RECIPE": "TARİF",
    "RECOMMEND": "TAVSİYE ETMEK",
    "RECYCLE": "GERİ DÖNÜŞTÜRMEK",
    "REDUCE": "AZALTMAK",
    "REFEREE": "HAKEM",
    "REFRIGERATOR": "BUZDOLABI",
    "REFUSE": "REDDETMEK",
    "REGION": "BÖLGE",
    "REGISTER": "KAYIT OLMAK",
    "RELAXED": "RAHAT",
    "RELAXING": "DİNLENDİRİCİ",
    "RELIABLE": "GÜVENİLİR",
    "RELY ON": "GÜVENİP DAYANMAK",
    "REMOTE CONTROL": "UZAKTAN KUMANDA",
    "RENEWABLE": "YENİLENEBİLİR",
    "RENT": "KİRA",
    "REPAIR": "TAMİR ETMEK",
    "REPEAT": "TEKRARLAMAK",
    "REPLY": "YANIT VERMEK",
    "REPTILE": "SÜRÜNGEN",
    "RESCUE": "KURTARMAK",
    "RESEARCH": "ARAŞTIRMAK",
    "RESERVATION": "REZERVASYON",
    "RESORT": "TATİL KÖYÜ",
    "RESPOND": "YANIT VERMEK",
    "RESPONSE": "CEVAP / TEPKİ",
    "RESPONSIBILITY": "SORUMLULUK",
    "RETIRED": "EMEKLİ",
    "RETURN BOOKS": "KİTAP İADE ETMEK",
    "RETURN TICKET": "GİDİŞ-DÖNÜŞ BİLETİ",
    "REUSE": "YENİDEN KULLANMAK",
    "RICE": "PİRİNÇ",
    "RIDICULOUS": "SAÇMA",
    "RIGHT NOW": "ŞU AN",
    "RING": "HALKA",
    "RIVER": "NEHİR",
    "ROAST": "FIRINDA KAVURMAK",
    "ROCK CLIMBING": "KAYA TIRMANIŞI",
    "ROCKY": "KAYALIK",
    "ROLLER COASTER": "HIZLI TREN",
    "ROLLERBLADING": "PALETLI PATEN",
    "RUBBISH": "ÇÖP",
    "RURAL": "KIRSAL ALAN",
    "SAD": "ÜZGÜN",
    "SADDLE": "EĞR",
    "SAFE": "GÜVENLİ",
    "SAFETY": "GÜVENLİK",
    "SAILING": "YELKEN",
    "SALAMI": "SALAM",
    "SALESWOMAN": "SATIŞ ELEMANI",
    "SALT": "TUZ",
    "SALTY": "TUZLU",
    "SANDCASTLE": "KUM KALESİ",
    "SATELLITE": "UYDU",
    "SAUCEPAN": "TENCERE",
    "SAUSAGE": "SOSİS",
    "SAVANNAH": "SAVAN",
    "SAVE": "KURTARMAK",
    "SCANNER": "TARAYICI",
    "SCARED": "KORKMUŞ",
    "SCARY": "KORKUTUCU",
    "SCHOLARSHIP": "BURS",
    "SCIENTIST": "BİLİM İNSANI",
    "SCREEN": "EKRAN",
    "SCREEN TIME": "EKRAN SÜRESİ",
    "SCUBA DIVING": "TÜPLÜ DALMA",
    "SEARCH ENGINE": "ARAMA MOTORU",
    "SEASIDE": "SAHİL",
    "SEASON": "MEVSİM",
    "SEAWEED": "DENİZ YOSUNU",
    "SECOND": "İKİNCİ",
    "SECRETARY": "SEKRETER",
    "SELDOM": "NADİREN",
    "SELFISH": "BENCİL",
    "SELL": "SATMAK",
    "SEND AN E-MAIL": "E-POSTA GÖNDERMEK",
    "SEND MESSAGE": "MESAJLAŞMAK",
    "SENDER": "GÖNDEREN",
    "SERIES": "DİZİ",
    "SERIOUS": "CİDDİ",
    "SERVE": "SERVİS YAPMAK",
    "SET TABLE": "MASA KURMAK",
    "SHARE": "PAYLAŞMAK",
    "SHOE SHOP": "AYAKKABICI",
    "SHOPPING MALL": "ALIŞVERİŞ MERKEZİ",
    "SHORT": "KISA",
    "SHUTTLE": "UZAY MEKİĞİ",
    "SHUTTLECOCK": "TÜY TOP",
    "SIGHTSEEING": "TURİSTİK GEZİ",
    "SIGN": "İŞARET / TABELA",
    "SIGN IN": "GİRİŞ YAPMAK",
    "SIGN UP": "ÜYE OLMAK",
    "SINGER": "ŞARKICI",
    "SINGLE TICKET": "GİDİŞ BİLETİ",
    "SIT COM": "SİTKOM",
    "SKATEBOARDING": "KAYKAY",
    "SKATING": "PATEN KAYMA",
    "SKELETON": "İSKELET",
    "SKIING": "KAYAK",
    "SKIN": "DERİ",
    "SKY DIVING": "SERBEST ATLAMA",
    "SKYSCRAPER": "GÖKDELEn",
    "SLEEPOVER": "GECELEME PARTİSİ",
    "SLEEPY": "UYKULU",
    "SLICE": "DİLİMLEMEK",
    "SLIM": "ZAYIF",
    "SLIPPERY": "KAYGAN",
    "SLOW": "YAVAŞ",
    "SLUMBER": "GECELEME",
    "SMALL": "KÜÇÜK",
    "SMOKE SIGNAL": "DUMAN İŞARETİ",
    "SNACK": "ATİŞTİRMELİK",
    "SNEAKY": "KURNAZ",
    "SNOB": "SNOB",
    "SNOWMAN": "KARDAN ADAM",
    "SOAP OPERA": "PEMBE DİZİ",
    "SOCIABLE": "SOSYAL",
    "SOCIAL NETWORK": "SOSYAL A?",
    "SOFTWARE": "YAZILIM",
    "SOLAR ENERGY": "GÜNEŞ ENERJİSİ",
    "SOLAR SYSTEM": "GÜNEŞ SİSTEMİ",
    "SOMETIMES": "BAZEN",
    "SOUR": "EKŞİ",
    "SOUVENIR": "HATİRA EŞYASI",
    "SPACE": "UZAY",
    "SPACECRAFT": "UZAY ARACI",
    "SPEAK LOUDER": "DAHA YÜKSEK SES",
    "SPEAKERS": "HOPARLÖR",
    "SPECTACULAR": "MUHTEŞEM",
    "SPECTATOR": "SEYİRCİ",
    "SPICY": "BAHARLI",
    "SPREAD": "SÜRMEK",
    "SPRING": "İLKBAHAR",
    "SPRINKLE": "SERPMEK",
    "SQUARE": "MEYDAN",
    "STAR": "YILDIZ",
    "START": "BAŞLAMAK",
    "STATUE": "HEYKEL",
    "STEAM": "BUHARDA PİŞİRMEK",
    "STEP": "ADIM",
    "STINGY": "CİMRİ",
    "STIR": "KARISTIRMAK",
    "STORMY": "FIRTINALI",
    "STRAIGHT": "DÜZ (SAÇ)",
    "STRAINER": "SÜZGEÇ",
    "STREET": "SOKAK",
    "STRIPE": "ÇİZGİ",
    "STRUCTURE": "YAPI",
    "STUBBORN": "İNATÇI",
    "STUDY LESSON": "DERS ÇALIŞMAK",
    "STUMPY": "BODUR",
    "STYLISH": "ŞIK",
    "SUBSCRIBE": "ABONE OLMAK",
    "SUCCESS": "BAŞARI",
    "SUCCESSFUL": "BAŞARILI",
    "SUGAR": "ŞEKER",
    "SUGGEST": "ÖNERMEK",
    "SUITCASE": "BAVUL",
    "SUMMER": "YAZ",
    "SUNNY": "GÜNEŞLI",
    "SUPPORT": "DESTEKLEMEK",
    "SURFACE": "YÜZEY",
    "SURPRISED": "ŞAŞKIN",
    "SURVIVE": "HAYATTA KALMAK",
    "SWEEP FLOOR": "YER SÜPÜRMEK",
    "SWEET": "TATLI",
    "TABLESPOON": "YEMEK KAŞIĞI",
    "TACTFUL": "DİPLOMATİK",
    "TAIL": "KUYRUK",
    "TAKE A NAP": "KESTIRMEK",
    "TAKE ACTION": "HAREKETE GEÇMEK",
    "TAKE CARE OF": "BAKMAK / İLGİLENMEK",
    "TAKE ORDER": "SİPARİŞ ALMAK",
    "TAKE OUT TRASH": "ÇÖP ÇIKARMAK",
    "TAKE RISKS": "RİSK ALMAK",
    "TAKE SHOWER": "DUŞ ALMAK",
    "TALENTED": "YETENEKLİ",
    "TALK SHOW": "TALK SHOW",
    "TALL": "UZUN BOYLU",
    "TASK": "GÖREV",
    "TASTE": "TAT",
    "TASTY": "LEZZETLİ",
    "TEA": "ÇAY",
    "TEACHER": "ÖĞRETMEN",
    "TEAMWORK": "TAKIM ÇALIŞMASI",
    "TEASPOON": "ÇAY KAŞIĞI",
    "TEENAGER": "GENÇ",
    "TELEGRAM": "TELGRAF",
    "TELESCOPE": "TELESKOP",
    "TELL LIES": "YALAN SÖYLEMEK",
    "TELL TRUTH": "DOĞRUYU SÖYLEMEK",
    "TELLY ADDICT": "TV BAĞIMLISI",
    "TEMPERATURE": "SICAKLIK",
    "TEMPLE": "TAPINAK",
    "TENT": "ÇADIR",
    "TERRIBLE": "KORKUNÇ",
    "TERRIFIC": "HARIKA",
    "TERRIFYING": "KORKUNÇ",
    "TEXTING": "MESAJLAŞMAK",
    "THEN": "SONRA",
    "THIRSTY": "SUSUZ",
    "THOUGHTFUL": "DÜŞÜNCELI",
    "THREATEN": "TEHDİT ETMEK",
    "THRILLER": "GERİLİM",
    "THRILLING": "HEYECAN VERİCİ",
    "THUNDER": "GÖKGÜRÜLTÜSÜ",
    "TICKET": "BİLET",
    "TIDY UP ROOM": "ODA TOPLAMAK",
    "TIME": "SAAT / ZAMAN",
    "TIRED": "YORGUN",
    "TO DO LIST": "YAPILACAKLAR LİSTESİ",
    "TOGETHER": "BİRLİKTE",
    "TOKEN": "JETON",
    "TOMATO": "DOMATES",
    "TOMB": "TÜRBE / MEZAR",
    "TOUR GUIDE": "TURİST REHBERİ",
    "TOWER": "KULE",
    "TOWN": "KASABA",
    "TOY SHOP": "OYUNCAKÇI",
    "TRADITIONAL": "GELENEKSEL",
    "TRAFFIC JAM": "TRAFİK TIKANIKLIĞI",
    "TRAIN": "ANTRENMAN YAPMAK",
    "TRANSMISSION": "İLETİM",
    "TRANSPORTATION": "ULAŞIM",
    "TRAVEL": "SEYAHAT",
    "TREKKING": "DOĞA YÜRÜYÜŞÜ",
    "TRENDY": "MODA",
    "TRIP": "GEZİ",
    "TRUE FRIEND": "GERÇEK ARKADAŞ",
    "TRUNK": "HORTUM",
    "TRUST": "GÜVENMEK",
    "TWICE": "İKİ KEZ",
    "TYPE": "YAZMAK",
    "UGLY": "ÇİRKİN",
    "UMBRELLA": "ŞEMSİYE",
    "UNAVAILABLE": "MÜSAİT DEĞİL",
    "UNBEARABLE": "DAYANILMAZ",
    "UNDER": "ALTINDA",
    "UNHEALTHY": "SAĞLIKSIZ",
    "UNIVERSE": "EVREN",
    "UNLUCKY": "ŞANSSIZ",
    "UNPLUG": "FİŞİ ÇEKMEK",
    "UNRELIABLE": "GÜVENİLMEZ",
    "UNTIDY": "DAĞINIK",
    "UNTIL": "KADAR",
    "UPLOAD": "YÜKLEMEK",
    "UPSET": "ÜZGÜN / KIZGIN",
    "URBAN": "KENTSEL",
    "USER": "KULLANICI",
    "USUALLY": "GENELLİKLE",
    "VACATION": "TATİL",
    "VACUUM FLOOR": "ELEKTRİKLİ SÜPÜRGE ÇEKMEK",
    "VEGETABLE": "SEBZE",
    "VET": "VETERİNER",
    "VILLAGE": "KÖY",
    "VIOLENCE": "ŞİDDET",
    "VISITOR": "ZİYARETÇİ",
    "VOYAGE": "YOLCULUK",
    "WAIT": "BEKLEMEK",
    "WAITRESS": "GARSON",
    "WAKE UP": "UYANMAK",
    "WALK THE DOG": "KÖPEĞİ GEZDİRMEK",
    "WALL": "DUVAR",
    "WARM": "ILIK",
    "WASH CLOTHES": "ÇAMAŞIR YIKAMAK",
    "WASH DISHES": "BULAŞIK YIKAMAK",
    "WASH FACE": "YÜZÜNÜ YIKAMAK",
    "WASTE": "İSRAF ETMEK",
    "WATCH TV": "TV İZLEMEK",
    "WATER PLANTS": "ÇİÇEK SULAMAK",
    "WATERFALL": "ŞELALE",
    "WAVE SWINGER": "SALLANAN SALINCAK",
    "WAVY": "DALGALI",
    "WEAR": "GİYMEK",
    "WEATHER": "HAVA DURUMU",
    "WEBCAM": "WEB KAMERASI",
    "WEBSITE": "WEB SİTESİ",
    "WEDDING": "DÜĞÜN",
    "WEEKDAY": "HAFTA İÇİ",
    "WEEKEND": "HAFTA SONU",
    "WEIGHT": "AĞIRLIK",
    "WELCOME": "HOŞ GELDİNİZ",
    "WELL BUILT": "ATLETİK",
    "WELL KNOWN": "ÇOK BİLİNEN",
    "WELL-KNOWN": "TANINMIŞ",
    "WILD LIFE": "YABAN HAYATI",
    "WIN": "KAZANMAK",
    "WIND ENERGY": "RÜZGAR ENERJİSİ",
    "WINDY": "RÜZGARLI",
    "WING": "KANAT",
    "WINTER": "KIŞ",
    "WIRELESS": "KABLOSUZ",
    "WONDERFUL": "HARİKA",
    "WORKER": "İŞÇİ",
    "WORLDWIDE": "DÜNYA ÇAPINDA",
    "WORRIED": "ENDİŞELİ",
    "WORSE": "DAHA KÖTÜ",
    "WRAP": "SARMAK",
    "WRESTLING": "GÜREŞ",
    "WRITE A LETTER": "MEKTUP YAZMAK",
    "YEAST": "MAYA",
    "YESTERDAY": "DÜN",
    "ZOO": "HAYVANAT BAHÇESİ",
  };

  function getContestTranslation(record, word) {
    if (typeof WORD_BANK === "undefined") return null;
    const grade = Array.isArray(record) ? record[3] : null;
    const unit = Array.isArray(record) ? record[5] : null;
    const normalized = String(word || "").trim().toUpperCase();
    const exactMatch = WORD_BANK.find((item) =>
      String(item.en || "").trim().toUpperCase() === normalized
      && item.grade === grade
      && item.unit === unit
    );
    const wordMatch = exactMatch || WORD_BANK.find((item) =>
      String(item.en || "").trim().toUpperCase() === normalized
    );
    return wordMatch?.tr || null;
  }

  window.TurkishAdapter = {
    getMeaning(recordOrWord) {
      const word = Array.isArray(recordOrWord) ? recordOrWord[2] : recordOrWord;
      const key = String(word || "").trim().toUpperCase();
      return getContestTranslation(recordOrWord, key)
        || TRANSLATIONS[key]
        || "T?RK?E KAR?ILIK EKS?K";
    },
    has(word) {
      const key = String(word || "").trim().toUpperCase();
      return Boolean(getContestTranslation(null, key))
        || Object.prototype.hasOwnProperty.call(TRANSLATIONS, key);
    },
    size: Object.keys(TRANSLATIONS).length
  };
})();
